// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: google/api/serviceusage/v1/resources.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-03-23 13:58:03 UTC

package v1

const ()
