// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: standards/open/statementm/v1/gams.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-07-14 07:48:27 UTC

package v1

const ()
