// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: google/api/field_behavior.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-03-24 07:46:07 UTC

package api

const ()
