// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: google/api/servicemanagement/v1/servicemanager.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-03-23 15:17:29 UTC

package v1

const (
	// ServiceManager_ListServices_FullMethodDescription returns the description of the google.api.servicemanagement.v1.ServiceManager.ListServices method.
	ServiceManager_ListServices_FullMethodDescription = "Lists managed services. Returns all public services. For authenticated users, also returns all\n services the calling user has \"servicemanagement.services.get\" permission\n for."
	// ServiceManager_GetService_FullMethodDescription returns the description of the google.api.servicemanagement.v1.ServiceManager.GetService method.
	ServiceManager_GetService_FullMethodDescription = "Gets a managed service. Authentication is required unless the service is\n public."
	// ServiceManager_CreateService_FullMethodDescription returns the description of the google.api.servicemanagement.v1.ServiceManager.CreateService method.
	ServiceManager_CreateService_FullMethodDescription = "Creates a new managed service. A managed service is immutable, and is subject to mandatory 30-day\n data retention. You cannot move a service or recreate it within 30 days\n after deletion.\n\n One producer project can own no more than 500 services. For security and\n reliability purposes, a production service should be hosted in a\n dedicated producer project.\n\n Operation<response: ManagedService>"
	// ServiceManager_DeleteService_FullMethodDescription returns the description of the google.api.servicemanagement.v1.ServiceManager.DeleteService method.
	ServiceManager_DeleteService_FullMethodDescription = "Deletes a managed service. This method will change the service to the\n `Soft-Delete` state for 30 days. Within this period, service producers may\n call\n [UndeleteService][google.api.servicemanagement.v1.ServiceManager.UndeleteService]\n to restore the service. After 30 days, the service will be permanently\n deleted. Operation<response: google.protobuf.Empty>"
	// ServiceManager_UndeleteService_FullMethodDescription returns the description of the google.api.servicemanagement.v1.ServiceManager.UndeleteService method.
	ServiceManager_UndeleteService_FullMethodDescription = "Revives a previously deleted managed service. The method restores the\n service using the configuration at the time the service was deleted.\n The target service must exist and must have been deleted within the\n last 30 days. Operation<response: UndeleteServiceResponse>"
	// ServiceManager_ListServiceConfigs_FullMethodDescription returns the description of the google.api.servicemanagement.v1.ServiceManager.ListServiceConfigs method.
	ServiceManager_ListServiceConfigs_FullMethodDescription = "Lists the history of the service configuration for a managed service,\n from the newest to the oldest."
	// ServiceManager_GetServiceConfig_FullMethodDescription returns the description of the google.api.servicemanagement.v1.ServiceManager.GetServiceConfig method.
	ServiceManager_GetServiceConfig_FullMethodDescription = "Gets a service configuration (version) for a managed service."
	// ServiceManager_CreateServiceConfig_FullMethodDescription returns the description of the google.api.servicemanagement.v1.ServiceManager.CreateServiceConfig method.
	ServiceManager_CreateServiceConfig_FullMethodDescription = "Creates a new service configuration (version) for a managed service.\n This method only stores the service configuration. To roll out the service\n configuration to backend systems please call\n [CreateServiceRollout][google.api.servicemanagement.v1.ServiceManager.CreateServiceRollout]. Only the 100 most recent service configurations and ones referenced by\n existing rollouts are kept for each service. The rest will be deleted\n eventually."
	// ServiceManager_SubmitConfigSource_FullMethodDescription returns the description of the google.api.servicemanagement.v1.ServiceManager.SubmitConfigSource method.
	ServiceManager_SubmitConfigSource_FullMethodDescription = "Creates a new service configuration (version) for a managed service based\n on\n user-supplied configuration source files (for example: OpenAPI\n Specification). This method stores the source configurations as well as the\n generated service configuration. To rollout the service configuration to\n other services,\n please call\n [CreateServiceRollout][google.api.servicemanagement.v1.ServiceManager.CreateServiceRollout]. Only the 100 most recent configuration sources and ones referenced by\n existing service configurtions are kept for each service. The rest will be\n deleted eventually.\n\n Operation<response: SubmitConfigSourceResponse>"
	// ServiceManager_ListServiceRollouts_FullMethodDescription returns the description of the google.api.servicemanagement.v1.ServiceManager.ListServiceRollouts method.
	ServiceManager_ListServiceRollouts_FullMethodDescription = "Lists the history of the service configuration rollouts for a managed\n service, from the newest to the oldest."
	// ServiceManager_GetServiceRollout_FullMethodDescription returns the description of the google.api.servicemanagement.v1.ServiceManager.GetServiceRollout method.
	ServiceManager_GetServiceRollout_FullMethodDescription = "Gets a service configuration\n [rollout][google.api.servicemanagement.v1.Rollout]."
	// ServiceManager_CreateServiceRollout_FullMethodDescription returns the description of the google.api.servicemanagement.v1.ServiceManager.CreateServiceRollout method.
	ServiceManager_CreateServiceRollout_FullMethodDescription = "Creates a new service configuration rollout. Based on rollout, the\n Google Service Management will roll out the service configurations to\n different backend services. For example, the logging configuration will be\n pushed to Google Cloud Logging. Please note that any previous pending and running Rollouts and associated\n Operations will be automatically cancelled so that the latest Rollout will\n not be blocked by previous Rollouts.\n\n Only the 100 most recent (in any state) and the last 10 successful (if not\n already part of the set of 100 most recent) rollouts are kept for each\n service. The rest will be deleted eventually.\n\n Operation<response: Rollout>"
	// ServiceManager_GenerateConfigReport_FullMethodDescription returns the description of the google.api.servicemanagement.v1.ServiceManager.GenerateConfigReport method.
	ServiceManager_GenerateConfigReport_FullMethodDescription = "Generates and returns a report (errors, warnings and changes from\n existing configurations) associated with\n GenerateConfigReportRequest.new_value If GenerateConfigReportRequest.old_value is specified,\n GenerateConfigReportRequest will contain a single ChangeReport based on the\n comparison between GenerateConfigReportRequest.new_value and\n GenerateConfigReportRequest.old_value.\n If GenerateConfigReportRequest.old_value is not specified, this method\n will compare GenerateConfigReportRequest.new_value with the last pushed\n service configuration."
)
