// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: standards/open/v1/RT000H944.proto

package v1

import (
	date "google.golang.org/genproto/googleapis/type/date"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CSSF report containing Identifiers of Luxembourg-based UCI/SIF/SICAR compartments or share classes
type RT000H944 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The records provided in the report
	Records       []*RT000H944_Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RT000H944) Reset() {
	*x = RT000H944{}
	mi := &file_standards_open_v1_RT000H944_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RT000H944) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RT000H944) ProtoMessage() {}

func (x *RT000H944) ProtoReflect() protoreflect.Message {
	mi := &file_standards_open_v1_RT000H944_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RT000H944.ProtoReflect.Descriptor instead.
func (*RT000H944) Descriptor() ([]byte, []int) {
	return file_standards_open_v1_RT000H944_proto_rawDescGZIP(), []int{0}
}

func (x *RT000H944) GetRecords() []*RT000H944_Record {
	if x != nil {
		return x.Records
	}
	return nil
}

// Definition of an individual record in the report
type RT000H944_Record struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata
	E string `protobuf:"bytes,1,opt,name=e,proto3" json:"e,omitempty"`
	// The CSSF's idenfifier for the umbrella
	Nnnnnnnn string `protobuf:"bytes,2,opt,name=nnnnnnnn,proto3" json:"nnnnnnnn,omitempty"`
	// The CSSF's idenfifier for the umbrella
	// NOMOPC
	Nomopc string `protobuf:"bytes,3,opt,name=nomopc,proto3" json:"nomopc,omitempty"`
	// The CSSF's identifier for the fund
	Cccccccc string `protobuf:"bytes,4,opt,name=cccccccc,proto3" json:"cccccccc,omitempty"`
	// The name of the sub-fund / compartment
	// NOMCOMPARTIMENT
	Nomcompartiment string `protobuf:"bytes,5,opt,name=nomcompartiment,proto3" json:"nomcompartiment,omitempty"`
	// AGREEMENTCOMP
	Agreementcomp *date.Date `protobuf:"bytes,6,opt,name=agreementcomp,proto3" json:"agreementcomp,omitempty"`
	// DEVISECOMP
	Devisecomp string `protobuf:"bytes,7,opt,name=devisecomp,proto3" json:"devisecomp,omitempty"`
	// PPPP
	Pppp string `protobuf:"bytes,8,opt,name=pppp,proto3" json:"pppp,omitempty"`
	// NOMTYPEPART
	Nomtypepart   string `protobuf:"bytes,9,opt,name=nomtypepart,proto3" json:"nomtypepart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RT000H944_Record) Reset() {
	*x = RT000H944_Record{}
	mi := &file_standards_open_v1_RT000H944_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RT000H944_Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RT000H944_Record) ProtoMessage() {}

func (x *RT000H944_Record) ProtoReflect() protoreflect.Message {
	mi := &file_standards_open_v1_RT000H944_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RT000H944_Record.ProtoReflect.Descriptor instead.
func (*RT000H944_Record) Descriptor() ([]byte, []int) {
	return file_standards_open_v1_RT000H944_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RT000H944_Record) GetE() string {
	if x != nil {
		return x.E
	}
	return ""
}

func (x *RT000H944_Record) GetNnnnnnnn() string {
	if x != nil {
		return x.Nnnnnnnn
	}
	return ""
}

func (x *RT000H944_Record) GetNomopc() string {
	if x != nil {
		return x.Nomopc
	}
	return ""
}

func (x *RT000H944_Record) GetCccccccc() string {
	if x != nil {
		return x.Cccccccc
	}
	return ""
}

func (x *RT000H944_Record) GetNomcompartiment() string {
	if x != nil {
		return x.Nomcompartiment
	}
	return ""
}

func (x *RT000H944_Record) GetAgreementcomp() *date.Date {
	if x != nil {
		return x.Agreementcomp
	}
	return nil
}

func (x *RT000H944_Record) GetDevisecomp() string {
	if x != nil {
		return x.Devisecomp
	}
	return ""
}

func (x *RT000H944_Record) GetPppp() string {
	if x != nil {
		return x.Pppp
	}
	return ""
}

func (x *RT000H944_Record) GetNomtypepart() string {
	if x != nil {
		return x.Nomtypepart
	}
	return ""
}

var File_standards_open_v1_RT000H944_proto protoreflect.FileDescriptor

const file_standards_open_v1_RT000H944_proto_rawDesc = "" +
	"\n" +
	"!standards/open/v1/RT000H944.proto\x12\x11standards.open.v1\x1a\x16google/type/date.proto\"\xec\x02\n" +
	"\tRT000H944\x12=\n" +
	"\arecords\x18\x01 \x03(\v2#.standards.open.v1.RT000H944.RecordR\arecords\x1a\x9f\x02\n" +
	"\x06Record\x12\f\n" +
	"\x01e\x18\x01 \x01(\tR\x01e\x12\x1a\n" +
	"\bnnnnnnnn\x18\x02 \x01(\tR\bnnnnnnnn\x12\x16\n" +
	"\x06nomopc\x18\x03 \x01(\tR\x06nomopc\x12\x1a\n" +
	"\bcccccccc\x18\x04 \x01(\tR\bcccccccc\x12(\n" +
	"\x0fnomcompartiment\x18\x05 \x01(\tR\x0fnomcompartiment\x127\n" +
	"\ragreementcomp\x18\x06 \x01(\v2\x11.google.type.DateR\ragreementcomp\x12\x1e\n" +
	"\n" +
	"devisecomp\x18\a \x01(\tR\n" +
	"devisecomp\x12\x12\n" +
	"\x04pppp\x18\b \x01(\tR\x04pppp\x12 \n" +
	"\vnomtypepart\x18\t \x01(\tR\vnomtypepartB(Z&go.alis.build/common/standards/open/v1b\x06proto3"

var (
	file_standards_open_v1_RT000H944_proto_rawDescOnce sync.Once
	file_standards_open_v1_RT000H944_proto_rawDescData []byte
)

func file_standards_open_v1_RT000H944_proto_rawDescGZIP() []byte {
	file_standards_open_v1_RT000H944_proto_rawDescOnce.Do(func() {
		file_standards_open_v1_RT000H944_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_standards_open_v1_RT000H944_proto_rawDesc), len(file_standards_open_v1_RT000H944_proto_rawDesc)))
	})
	return file_standards_open_v1_RT000H944_proto_rawDescData
}

var file_standards_open_v1_RT000H944_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_standards_open_v1_RT000H944_proto_goTypes = []any{
	(*RT000H944)(nil),        // 0: standards.open.v1.RT000H944
	(*RT000H944_Record)(nil), // 1: standards.open.v1.RT000H944.Record
	(*date.Date)(nil),        // 2: google.type.Date
}
var file_standards_open_v1_RT000H944_proto_depIdxs = []int32{
	1, // 0: standards.open.v1.RT000H944.records:type_name -> standards.open.v1.RT000H944.Record
	2, // 1: standards.open.v1.RT000H944.Record.agreementcomp:type_name -> google.type.Date
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_standards_open_v1_RT000H944_proto_init() }
func file_standards_open_v1_RT000H944_proto_init() {
	if File_standards_open_v1_RT000H944_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_standards_open_v1_RT000H944_proto_rawDesc), len(file_standards_open_v1_RT000H944_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_standards_open_v1_RT000H944_proto_goTypes,
		DependencyIndexes: file_standards_open_v1_RT000H944_proto_depIdxs,
		MessageInfos:      file_standards_open_v1_RT000H944_proto_msgTypes,
	}.Build()
	File_standards_open_v1_RT000H944_proto = out.File
	file_standards_open_v1_RT000H944_proto_goTypes = nil
	file_standards_open_v1_RT000H944_proto_depIdxs = nil
}
