// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: standards/open/v1/RT000K4S9.proto

package v1

import (
	date "google.golang.org/genproto/googleapis/type/date"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CSSF report containing identifiers of registered AIFMs
type RT000K4S9 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The records provided in the report
	Records       []*RT000K4S9_Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RT000K4S9) Reset() {
	*x = RT000K4S9{}
	mi := &file_standards_open_v1_RT000K4S9_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RT000K4S9) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RT000K4S9) ProtoMessage() {}

func (x *RT000K4S9) ProtoReflect() protoreflect.Message {
	mi := &file_standards_open_v1_RT000K4S9_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RT000K4S9.ProtoReflect.Descriptor instead.
func (*RT000K4S9) Descriptor() ([]byte, []int) {
	return file_standards_open_v1_RT000K4S9_proto_rawDescGZIP(), []int{0}
}

func (x *RT000K4S9) GetRecords() []*RT000K4S9_Record {
	if x != nil {
		return x.Records
	}
	return nil
}

// Definition of an individual record in the report
type RT000K4S9_Record struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata
	A string `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	// The CSSF's indenfifier for the AIFM
	Nnnnnnnn string `protobuf:"bytes,2,opt,name=nnnnnnnn,proto3" json:"nnnnnnnn,omitempty"`
	// The name of the Aifm
	AifmName string `protobuf:"bytes,3,opt,name=aifm_name,json=aifmName,proto3" json:"aifm_name,omitempty"`
	// The status of the Aifm
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// Classification information related to the AIFM
	F string `protobuf:"bytes,5,opt,name=f,proto3" json:"f,omitempty"`
	// Classification information related to the AIFM
	Mmmmmmmm string `protobuf:"bytes,6,opt,name=mmmmmmmm,proto3" json:"mmmmmmmm,omitempty"`
	// The name of the AIF
	AifName string `protobuf:"bytes,7,opt,name=aif_name,json=aifName,proto3" json:"aif_name,omitempty"`
	// The identifier of the sub-fund
	// For compartments or standalone funds, this will be 0
	Cccccccc string `protobuf:"bytes,8,opt,name=cccccccc,proto3" json:"cccccccc,omitempty"`
	// The name of the sub-fund
	SubFundName string `protobuf:"bytes,9,opt,name=sub_fund_name,json=subFundName,proto3" json:"sub_fund_name,omitempty"`
	// The starting management date of the AIF
	StartingManagementDateOfTheAif *date.Date `protobuf:"bytes,10,opt,name=starting_management_date_of_the_aif,json=startingManagementDateOfTheAif,proto3" json:"starting_management_date_of_the_aif,omitempty"`
	// The ending management date of the AIF
	EndingManagementDateOfTheAif *date.Date `protobuf:"bytes,11,opt,name=ending_management_date_of_the_aif,json=endingManagementDateOfTheAif,proto3" json:"ending_management_date_of_the_aif,omitempty"`
	// The REGISTRATION_DATE_OR_INCEPTION_DATE_OF_THE_SUBFUND_OR_AIF the AIF
	RegistrationDateOrInceptionDateOfTheSubfundOrAif *date.Date `protobuf:"bytes,12,opt,name=registration_date_or_inception_date_of_the_subfund_or_aif,json=registrationDateOrInceptionDateOfTheSubfundOrAif,proto3" json:"registration_date_or_inception_date_of_the_subfund_or_aif,omitempty"`
	// The CLOSING_DATE_OF_THE_SUBFUND_OR_AIF the AIF
	ClosingDateOrInceptionDateOfTheSubfundOrAif *date.Date `protobuf:"bytes,13,opt,name=closing_date_or_inception_date_of_the_subfund_or_aif,json=closingDateOrInceptionDateOfTheSubfundOrAif,proto3" json:"closing_date_or_inception_date_of_the_subfund_or_aif,omitempty"`
	unknownFields                               protoimpl.UnknownFields
	sizeCache                                   protoimpl.SizeCache
}

func (x *RT000K4S9_Record) Reset() {
	*x = RT000K4S9_Record{}
	mi := &file_standards_open_v1_RT000K4S9_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RT000K4S9_Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RT000K4S9_Record) ProtoMessage() {}

func (x *RT000K4S9_Record) ProtoReflect() protoreflect.Message {
	mi := &file_standards_open_v1_RT000K4S9_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RT000K4S9_Record.ProtoReflect.Descriptor instead.
func (*RT000K4S9_Record) Descriptor() ([]byte, []int) {
	return file_standards_open_v1_RT000K4S9_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RT000K4S9_Record) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *RT000K4S9_Record) GetNnnnnnnn() string {
	if x != nil {
		return x.Nnnnnnnn
	}
	return ""
}

func (x *RT000K4S9_Record) GetAifmName() string {
	if x != nil {
		return x.AifmName
	}
	return ""
}

func (x *RT000K4S9_Record) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RT000K4S9_Record) GetF() string {
	if x != nil {
		return x.F
	}
	return ""
}

func (x *RT000K4S9_Record) GetMmmmmmmm() string {
	if x != nil {
		return x.Mmmmmmmm
	}
	return ""
}

func (x *RT000K4S9_Record) GetAifName() string {
	if x != nil {
		return x.AifName
	}
	return ""
}

func (x *RT000K4S9_Record) GetCccccccc() string {
	if x != nil {
		return x.Cccccccc
	}
	return ""
}

func (x *RT000K4S9_Record) GetSubFundName() string {
	if x != nil {
		return x.SubFundName
	}
	return ""
}

func (x *RT000K4S9_Record) GetStartingManagementDateOfTheAif() *date.Date {
	if x != nil {
		return x.StartingManagementDateOfTheAif
	}
	return nil
}

func (x *RT000K4S9_Record) GetEndingManagementDateOfTheAif() *date.Date {
	if x != nil {
		return x.EndingManagementDateOfTheAif
	}
	return nil
}

func (x *RT000K4S9_Record) GetRegistrationDateOrInceptionDateOfTheSubfundOrAif() *date.Date {
	if x != nil {
		return x.RegistrationDateOrInceptionDateOfTheSubfundOrAif
	}
	return nil
}

func (x *RT000K4S9_Record) GetClosingDateOrInceptionDateOfTheSubfundOrAif() *date.Date {
	if x != nil {
		return x.ClosingDateOrInceptionDateOfTheSubfundOrAif
	}
	return nil
}

var File_standards_open_v1_RT000K4S9_proto protoreflect.FileDescriptor

const file_standards_open_v1_RT000K4S9_proto_rawDesc = "" +
	"\n" +
	"!standards/open/v1/RT000K4S9.proto\x12\x11standards.open.v1\x1a\x16google/type/date.proto\"\xfc\x05\n" +
	"\tRT000K4S9\x12=\n" +
	"\arecords\x18\x01 \x03(\v2#.standards.open.v1.RT000K4S9.RecordR\arecords\x1a\xaf\x05\n" +
	"\x06Record\x12\f\n" +
	"\x01a\x18\x01 \x01(\tR\x01a\x12\x1a\n" +
	"\bnnnnnnnn\x18\x02 \x01(\tR\bnnnnnnnn\x12\x1b\n" +
	"\taifm_name\x18\x03 \x01(\tR\baifmName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\f\n" +
	"\x01f\x18\x05 \x01(\tR\x01f\x12\x1a\n" +
	"\bmmmmmmmm\x18\x06 \x01(\tR\bmmmmmmmm\x12\x19\n" +
	"\baif_name\x18\a \x01(\tR\aaifName\x12\x1a\n" +
	"\bcccccccc\x18\b \x01(\tR\bcccccccc\x12\"\n" +
	"\rsub_fund_name\x18\t \x01(\tR\vsubFundName\x12^\n" +
	"#starting_management_date_of_the_aif\x18\n" +
	" \x01(\v2\x11.google.type.DateR\x1estartingManagementDateOfTheAif\x12Z\n" +
	"!ending_management_date_of_the_aif\x18\v \x01(\v2\x11.google.type.DateR\x1cendingManagementDateOfTheAif\x12\x86\x01\n" +
	"9registration_date_or_inception_date_of_the_subfund_or_aif\x18\f \x01(\v2\x11.google.type.DateR0registrationDateOrInceptionDateOfTheSubfundOrAif\x12|\n" +
	"4closing_date_or_inception_date_of_the_subfund_or_aif\x18\r \x01(\v2\x11.google.type.DateR+closingDateOrInceptionDateOfTheSubfundOrAifB(Z&go.alis.build/common/standards/open/v1b\x06proto3"

var (
	file_standards_open_v1_RT000K4S9_proto_rawDescOnce sync.Once
	file_standards_open_v1_RT000K4S9_proto_rawDescData []byte
)

func file_standards_open_v1_RT000K4S9_proto_rawDescGZIP() []byte {
	file_standards_open_v1_RT000K4S9_proto_rawDescOnce.Do(func() {
		file_standards_open_v1_RT000K4S9_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_standards_open_v1_RT000K4S9_proto_rawDesc), len(file_standards_open_v1_RT000K4S9_proto_rawDesc)))
	})
	return file_standards_open_v1_RT000K4S9_proto_rawDescData
}

var file_standards_open_v1_RT000K4S9_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_standards_open_v1_RT000K4S9_proto_goTypes = []any{
	(*RT000K4S9)(nil),        // 0: standards.open.v1.RT000K4S9
	(*RT000K4S9_Record)(nil), // 1: standards.open.v1.RT000K4S9.Record
	(*date.Date)(nil),        // 2: google.type.Date
}
var file_standards_open_v1_RT000K4S9_proto_depIdxs = []int32{
	1, // 0: standards.open.v1.RT000K4S9.records:type_name -> standards.open.v1.RT000K4S9.Record
	2, // 1: standards.open.v1.RT000K4S9.Record.starting_management_date_of_the_aif:type_name -> google.type.Date
	2, // 2: standards.open.v1.RT000K4S9.Record.ending_management_date_of_the_aif:type_name -> google.type.Date
	2, // 3: standards.open.v1.RT000K4S9.Record.registration_date_or_inception_date_of_the_subfund_or_aif:type_name -> google.type.Date
	2, // 4: standards.open.v1.RT000K4S9.Record.closing_date_or_inception_date_of_the_subfund_or_aif:type_name -> google.type.Date
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_standards_open_v1_RT000K4S9_proto_init() }
func file_standards_open_v1_RT000K4S9_proto_init() {
	if File_standards_open_v1_RT000K4S9_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_standards_open_v1_RT000K4S9_proto_rawDesc), len(file_standards_open_v1_RT000K4S9_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_standards_open_v1_RT000K4S9_proto_goTypes,
		DependencyIndexes: file_standards_open_v1_RT000K4S9_proto_depIdxs,
		MessageInfos:      file_standards_open_v1_RT000K4S9_proto_msgTypes,
	}.Build()
	File_standards_open_v1_RT000K4S9_proto = out.File
	file_standards_open_v1_RT000K4S9_proto_goTypes = nil
	file_standards_open_v1_RT000K4S9_proto_depIdxs = nil
}
