// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: standards/open/v1/RT000NVJ3.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-07-07 14:20:06 UTC

package v1

const ()
