// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: standards/open/v1/RT00026H1.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	date "google.golang.org/genproto/googleapis/type/date"
	_ "google.golang.org/genproto/googleapis/type/money"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/fieldmaskpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enumerations of asset categories
type RT00026H1_AssetCategory int32

const (
	// Source not specified by the user.
	RT00026H1_ASSET_CATEGORY_UNSPECIFIED RT00026H1_AssetCategory = 0
	// Asset
	RT00026H1_ASSET RT00026H1_AssetCategory = 1
	// Cash
	RT00026H1_CASH RT00026H1_AssetCategory = 2
	// Cash Equivalent
	RT00026H1_CASH_EQUIVALENT RT00026H1_AssetCategory = 3
	// Equity
	RT00026H1_EQUITY RT00026H1_AssetCategory = 4
	// Fixed Income
	RT00026H1_FIXED_INCOME RT00026H1_AssetCategory = 7
	// Forex
	RT00026H1_FOREIGN_EXCHANGE RT00026H1_AssetCategory = 8
	// Future
	RT00026H1_FUTURE RT00026H1_AssetCategory = 9
	// Other Liabilities
	RT00026H1_LIABILITY RT00026H1_AssetCategory = 10
	// Options
	RT00026H1_OPTION RT00026H1_AssetCategory = 11
)

// Enum value maps for RT00026H1_AssetCategory.
var (
	RT00026H1_AssetCategory_name = map[int32]string{
		0:  "ASSET_CATEGORY_UNSPECIFIED",
		1:  "ASSET",
		2:  "CASH",
		3:  "CASH_EQUIVALENT",
		4:  "EQUITY",
		7:  "FIXED_INCOME",
		8:  "FOREIGN_EXCHANGE",
		9:  "FUTURE",
		10: "LIABILITY",
		11: "OPTION",
	}
	RT00026H1_AssetCategory_value = map[string]int32{
		"ASSET_CATEGORY_UNSPECIFIED": 0,
		"ASSET":                      1,
		"CASH":                       2,
		"CASH_EQUIVALENT":            3,
		"EQUITY":                     4,
		"FIXED_INCOME":               7,
		"FOREIGN_EXCHANGE":           8,
		"FUTURE":                     9,
		"LIABILITY":                  10,
		"OPTION":                     11,
	}
)

func (x RT00026H1_AssetCategory) Enum() *RT00026H1_AssetCategory {
	p := new(RT00026H1_AssetCategory)
	*p = x
	return p
}

func (x RT00026H1_AssetCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RT00026H1_AssetCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_standards_open_v1_RT00026H1_proto_enumTypes[0].Descriptor()
}

func (RT00026H1_AssetCategory) Type() protoreflect.EnumType {
	return &file_standards_open_v1_RT00026H1_proto_enumTypes[0]
}

func (x RT00026H1_AssetCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RT00026H1_AssetCategory.Descriptor instead.
func (RT00026H1_AssetCategory) EnumDescriptor() ([]byte, []int) {
	return file_standards_open_v1_RT00026H1_proto_rawDescGZIP(), []int{0, 0}
}

// Fund Holding
type RT00026H1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The effective date of the holding.
	// The holdings are as of market close on the effective date
	EffectiveDate *date.Date `protobuf:"bytes,1,opt,name=effective_date,json=effectiveDate,proto3" json:"effective_date,omitempty"`
	// The legal identifier of the umbrella
	// Should conform to: https://openfunds.org/OFST005010 (Umbrella)
	// See: https://openfunds.org/knowledge/whitepapers/fundnames/ for more information
	UmbrellaFund string `protobuf:"bytes,2,opt,name=umbrella_fund,json=umbrellaFund,proto3" json:"umbrella_fund,omitempty"`
	// Name of the relevant sub-fund
	// Should conform to: https://openfunds.org/OFST010110 (Legal Fund Name Only)
	// Refers to the Sub-Fund in the case of an umbrella structure
	// or Fund in the case of a standalone structure
	// See: https://openfunds.org/knowledge/whitepapers/fundnames/ for more information
	Fund string `protobuf:"bytes,3,opt,name=fund,proto3" json:"fund,omitempty"`
	// The ISO compliant three character code for the base currency of the fund
	FundCurrency string `protobuf:"bytes,4,opt,name=fund_currency,json=fundCurrency,proto3" json:"fund_currency,omitempty"`
	// The internalID used by the system producing the data
	InternalAssetId string `protobuf:"bytes,5,opt,name=internal_asset_id,json=internalAssetId,proto3" json:"internal_asset_id,omitempty"`
	// ISO 6166 code of ISIN when available. If an ISIN is used, it is recommended that the MIC or Bloomberg Exchange Code should additionally be populated. This combination allows for a fund holding to be uniquely identified.
	ExternalAssetIdIsin string `protobuf:"bytes,101,opt,name=external_asset_id_isin,json=externalAssetIdIsin,proto3" json:"external_asset_id_isin,omitempty"`
	// CUSIP - The Committee on Uniform Securities Identification Procedures number assigned by the CUSIP Service Bureau for U.S. and Canadian companies when available. If a CUSIP is used, it is recommended that the MIC or Bloomberg Exchange Code should additionally be populated. This combination allows for a fund holding to be uniquely identified.
	ExternalAssetIdCusip string `protobuf:"bytes,102,opt,name=external_asset_id_cusip,json=externalAssetIdCusip,proto3" json:"external_asset_id_cusip,omitempty"`
	// SEDOL - Stock Exchange Daily Official List for the London Stock Exchange (when available). If a SEDOL is used, it is recommended that the MIC or Bloomberg Exchange Code should additionally be populated. This combination allows for a fund holding to be uniquely identified.
	ExternalAssetIdSedol string `protobuf:"bytes,103,opt,name=external_asset_id_sedol,json=externalAssetIdSedol,proto3" json:"external_asset_id_sedol,omitempty"`
	// FIGI - Financial Instrument Global Identifier (when available)
	ExternalAssetIdFigi string `protobuf:"bytes,104,opt,name=external_asset_id_figi,json=externalAssetIdFigi,proto3" json:"external_asset_id_figi,omitempty"`
	// PermID - Refinitiv Permanent Identifiers (when available)
	ExternalAssetIdPermid string `protobuf:"bytes,105,opt,name=external_asset_id_permid,json=externalAssetIdPermid,proto3" json:"external_asset_id_permid,omitempty"`
	// MIC - Market identifier code as defined by ISO 10383 (available at https://www.iso20022.org/market-identifier-codes) (when available)
	ExternalExchangeIdMic string `protobuf:"bytes,201,opt,name=external_exchange_id_mic,json=externalExchangeIdMic,proto3" json:"external_exchange_id_mic,omitempty"`
	// Bloomberg Exchange Code - Two digit market identifier code as defined by Bloomberg (when available)
	ExternalExchangeIdBbExchangeCode string `protobuf:"bytes,202,opt,name=external_exchange_id_bb_exchange_code,json=externalExchangeIdBbExchangeCode,proto3" json:"external_exchange_id_bb_exchange_code,omitempty"`
	// The asset category of the holding
	AssetCategory RT00026H1_AssetCategory `protobuf:"varint,6,opt,name=asset_category,json=assetCategory,proto3,enum=standards.open.v1.RT00026H1_AssetCategory" json:"asset_category,omitempty"`
	// The ISO compliant three character local currency code of the asset
	LocalCurrencyCode string `protobuf:"bytes,7,opt,name=local_currency_code,json=localCurrencyCode,proto3" json:"local_currency_code,omitempty"`
	// The quantity of the asset held
	Quantity float64 `protobuf:"fixed64,8,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// price in local currency units
	PriceLcu float64 `protobuf:"fixed64,9,opt,name=price_lcu,json=priceLcu,proto3" json:"price_lcu,omitempty"`
	// price in fund currency units
	PriceBase float64 `protobuf:"fixed64,10,opt,name=price_base,json=priceBase,proto3" json:"price_base,omitempty"`
	// the total market value in fund currency units
	MarketValueBase float64 `protobuf:"fixed64,11,opt,name=market_value_base,json=marketValueBase,proto3" json:"market_value_base,omitempty"`
	// the total net asset value of the fund on the effective date in base currency units
	FundNav float64 `protobuf:"fixed64,12,opt,name=fund_nav,json=fundNav,proto3" json:"fund_nav,omitempty"`
	// the percentage weight of total net asset value
	PercentNav float64 `protobuf:"fixed64,13,opt,name=percent_nav,json=percentNav,proto3" json:"percent_nav,omitempty"`
	// The date as of which the holdings record was produced.
	AsOfDate      *date.Date `protobuf:"bytes,301,opt,name=as_of_date,json=asOfDate,proto3" json:"as_of_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RT00026H1) Reset() {
	*x = RT00026H1{}
	mi := &file_standards_open_v1_RT00026H1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RT00026H1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RT00026H1) ProtoMessage() {}

func (x *RT00026H1) ProtoReflect() protoreflect.Message {
	mi := &file_standards_open_v1_RT00026H1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RT00026H1.ProtoReflect.Descriptor instead.
func (*RT00026H1) Descriptor() ([]byte, []int) {
	return file_standards_open_v1_RT00026H1_proto_rawDescGZIP(), []int{0}
}

func (x *RT00026H1) GetEffectiveDate() *date.Date {
	if x != nil {
		return x.EffectiveDate
	}
	return nil
}

func (x *RT00026H1) GetUmbrellaFund() string {
	if x != nil {
		return x.UmbrellaFund
	}
	return ""
}

func (x *RT00026H1) GetFund() string {
	if x != nil {
		return x.Fund
	}
	return ""
}

func (x *RT00026H1) GetFundCurrency() string {
	if x != nil {
		return x.FundCurrency
	}
	return ""
}

func (x *RT00026H1) GetInternalAssetId() string {
	if x != nil {
		return x.InternalAssetId
	}
	return ""
}

func (x *RT00026H1) GetExternalAssetIdIsin() string {
	if x != nil {
		return x.ExternalAssetIdIsin
	}
	return ""
}

func (x *RT00026H1) GetExternalAssetIdCusip() string {
	if x != nil {
		return x.ExternalAssetIdCusip
	}
	return ""
}

func (x *RT00026H1) GetExternalAssetIdSedol() string {
	if x != nil {
		return x.ExternalAssetIdSedol
	}
	return ""
}

func (x *RT00026H1) GetExternalAssetIdFigi() string {
	if x != nil {
		return x.ExternalAssetIdFigi
	}
	return ""
}

func (x *RT00026H1) GetExternalAssetIdPermid() string {
	if x != nil {
		return x.ExternalAssetIdPermid
	}
	return ""
}

func (x *RT00026H1) GetExternalExchangeIdMic() string {
	if x != nil {
		return x.ExternalExchangeIdMic
	}
	return ""
}

func (x *RT00026H1) GetExternalExchangeIdBbExchangeCode() string {
	if x != nil {
		return x.ExternalExchangeIdBbExchangeCode
	}
	return ""
}

func (x *RT00026H1) GetAssetCategory() RT00026H1_AssetCategory {
	if x != nil {
		return x.AssetCategory
	}
	return RT00026H1_ASSET_CATEGORY_UNSPECIFIED
}

func (x *RT00026H1) GetLocalCurrencyCode() string {
	if x != nil {
		return x.LocalCurrencyCode
	}
	return ""
}

func (x *RT00026H1) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *RT00026H1) GetPriceLcu() float64 {
	if x != nil {
		return x.PriceLcu
	}
	return 0
}

func (x *RT00026H1) GetPriceBase() float64 {
	if x != nil {
		return x.PriceBase
	}
	return 0
}

func (x *RT00026H1) GetMarketValueBase() float64 {
	if x != nil {
		return x.MarketValueBase
	}
	return 0
}

func (x *RT00026H1) GetFundNav() float64 {
	if x != nil {
		return x.FundNav
	}
	return 0
}

func (x *RT00026H1) GetPercentNav() float64 {
	if x != nil {
		return x.PercentNav
	}
	return 0
}

func (x *RT00026H1) GetAsOfDate() *date.Date {
	if x != nil {
		return x.AsOfDate
	}
	return nil
}

// Batch set of RT00026H1 responses
type RT00026H1Batch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      []*RT00026H1           `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RT00026H1Batch) Reset() {
	*x = RT00026H1Batch{}
	mi := &file_standards_open_v1_RT00026H1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RT00026H1Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RT00026H1Batch) ProtoMessage() {}

func (x *RT00026H1Batch) ProtoReflect() protoreflect.Message {
	mi := &file_standards_open_v1_RT00026H1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RT00026H1Batch.ProtoReflect.Descriptor instead.
func (*RT00026H1Batch) Descriptor() ([]byte, []int) {
	return file_standards_open_v1_RT00026H1_proto_rawDescGZIP(), []int{1}
}

func (x *RT00026H1Batch) GetResponse() []*RT00026H1 {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_standards_open_v1_RT00026H1_proto protoreflect.FileDescriptor

const file_standards_open_v1_RT00026H1_proto_rawDesc = "" +
	"\n" +
	"!standards/open/v1/RT00026H1.proto\x12\x11standards.open.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x19google/api/resource.proto\x1a\x17google/type/money.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16google/type/date.proto\"\x98\t\n" +
	"\tRT00026H1\x128\n" +
	"\x0eeffective_date\x18\x01 \x01(\v2\x11.google.type.DateR\reffectiveDate\x12#\n" +
	"\rumbrella_fund\x18\x02 \x01(\tR\fumbrellaFund\x12\x12\n" +
	"\x04fund\x18\x03 \x01(\tR\x04fund\x12#\n" +
	"\rfund_currency\x18\x04 \x01(\tR\ffundCurrency\x12*\n" +
	"\x11internal_asset_id\x18\x05 \x01(\tR\x0finternalAssetId\x123\n" +
	"\x16external_asset_id_isin\x18e \x01(\tR\x13externalAssetIdIsin\x125\n" +
	"\x17external_asset_id_cusip\x18f \x01(\tR\x14externalAssetIdCusip\x125\n" +
	"\x17external_asset_id_sedol\x18g \x01(\tR\x14externalAssetIdSedol\x123\n" +
	"\x16external_asset_id_figi\x18h \x01(\tR\x13externalAssetIdFigi\x127\n" +
	"\x18external_asset_id_permid\x18i \x01(\tR\x15externalAssetIdPermid\x128\n" +
	"\x18external_exchange_id_mic\x18\xc9\x01 \x01(\tR\x15externalExchangeIdMic\x12P\n" +
	"%external_exchange_id_bb_exchange_code\x18\xca\x01 \x01(\tR externalExchangeIdBbExchangeCode\x12Q\n" +
	"\x0easset_category\x18\x06 \x01(\x0e2*.standards.open.v1.RT00026H1.AssetCategoryR\rassetCategory\x12.\n" +
	"\x13local_currency_code\x18\a \x01(\tR\x11localCurrencyCode\x12\x1a\n" +
	"\bquantity\x18\b \x01(\x01R\bquantity\x12\x1b\n" +
	"\tprice_lcu\x18\t \x01(\x01R\bpriceLcu\x12\x1d\n" +
	"\n" +
	"price_base\x18\n" +
	" \x01(\x01R\tpriceBase\x12*\n" +
	"\x11market_value_base\x18\v \x01(\x01R\x0fmarketValueBase\x12\x19\n" +
	"\bfund_nav\x18\f \x01(\x01R\afundNav\x12\x1f\n" +
	"\vpercent_nav\x18\r \x01(\x01R\n" +
	"percentNav\x120\n" +
	"\n" +
	"as_of_date\x18\xad\x02 \x01(\v2\x11.google.type.DateR\basOfDate\"\xb4\x01\n" +
	"\rAssetCategory\x12\x1e\n" +
	"\x1aASSET_CATEGORY_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05ASSET\x10\x01\x12\b\n" +
	"\x04CASH\x10\x02\x12\x13\n" +
	"\x0fCASH_EQUIVALENT\x10\x03\x12\n" +
	"\n" +
	"\x06EQUITY\x10\x04\x12\x10\n" +
	"\fFIXED_INCOME\x10\a\x12\x14\n" +
	"\x10FOREIGN_EXCHANGE\x10\b\x12\n" +
	"\n" +
	"\x06FUTURE\x10\t\x12\r\n" +
	"\tLIABILITY\x10\n" +
	"\x12\n" +
	"\n" +
	"\x06OPTION\x10\v\"K\n" +
	"\x0fRT00026H1_batch\x128\n" +
	"\bresponse\x18\x01 \x03(\v2\x1c.standards.open.v1.RT00026H1R\bresponseB(Z&go.alis.build/common/standards/open/v1b\x06proto3"

var (
	file_standards_open_v1_RT00026H1_proto_rawDescOnce sync.Once
	file_standards_open_v1_RT00026H1_proto_rawDescData []byte
)

func file_standards_open_v1_RT00026H1_proto_rawDescGZIP() []byte {
	file_standards_open_v1_RT00026H1_proto_rawDescOnce.Do(func() {
		file_standards_open_v1_RT00026H1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_standards_open_v1_RT00026H1_proto_rawDesc), len(file_standards_open_v1_RT00026H1_proto_rawDesc)))
	})
	return file_standards_open_v1_RT00026H1_proto_rawDescData
}

var file_standards_open_v1_RT00026H1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_standards_open_v1_RT00026H1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_standards_open_v1_RT00026H1_proto_goTypes = []any{
	(RT00026H1_AssetCategory)(0), // 0: standards.open.v1.RT00026H1.AssetCategory
	(*RT00026H1)(nil),            // 1: standards.open.v1.RT00026H1
	(*RT00026H1Batch)(nil),       // 2: standards.open.v1.RT00026H1_batch
	(*date.Date)(nil),            // 3: google.type.Date
}
var file_standards_open_v1_RT00026H1_proto_depIdxs = []int32{
	3, // 0: standards.open.v1.RT00026H1.effective_date:type_name -> google.type.Date
	0, // 1: standards.open.v1.RT00026H1.asset_category:type_name -> standards.open.v1.RT00026H1.AssetCategory
	3, // 2: standards.open.v1.RT00026H1.as_of_date:type_name -> google.type.Date
	1, // 3: standards.open.v1.RT00026H1_batch.response:type_name -> standards.open.v1.RT00026H1
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_standards_open_v1_RT00026H1_proto_init() }
func file_standards_open_v1_RT00026H1_proto_init() {
	if File_standards_open_v1_RT00026H1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_standards_open_v1_RT00026H1_proto_rawDesc), len(file_standards_open_v1_RT00026H1_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_standards_open_v1_RT00026H1_proto_goTypes,
		DependencyIndexes: file_standards_open_v1_RT00026H1_proto_depIdxs,
		EnumInfos:         file_standards_open_v1_RT00026H1_proto_enumTypes,
		MessageInfos:      file_standards_open_v1_RT00026H1_proto_msgTypes,
	}.Build()
	File_standards_open_v1_RT00026H1_proto = out.File
	file_standards_open_v1_RT00026H1_proto_goTypes = nil
	file_standards_open_v1_RT00026H1_proto_depIdxs = nil
}
