// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: standards/open/v1/RT000K4S9.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-05-28 08:24:42 UTC

package v1

const ()
