// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: standards/open/v1/RT000LFR7.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	date "google.golang.org/genproto/googleapis/type/date"
	_ "google.golang.org/genproto/googleapis/type/month"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/fieldmaskpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enumeration of metricIDs
type RT000LFR7_Metric_MetricID int32

const (
	// The enumeration of the metrics measured
	RT000LFR7_Metric_METRIC_ID_UNSPECIFIED RT000LFR7_Metric_MetricID = 0
	// Number of NAVs calculated during the month
	RT000LFR7_Metric_NAVS_CALCULATED RT000LFR7_Metric_MetricID = 1
	// Count of the number of delays in the period caused by the provider
	RT000LFR7_Metric_NAVS_PROVIDER_DELAYED RT000LFR7_Metric_MetricID = 2
	// Count of the number of delays in the period not caused by the provider
	RT000LFR7_Metric_NAVS_NON_PROVIDER_DELAYED RT000LFR7_Metric_MetricID = 3
	// Percentage of total NAVs delivered within the agreed timescale during the reporting month.
	// NAV_TIMELINESS should equal  1- (NAVS_PROVIDER_DELAYED + NAVS_NON_PROVIDER_DELAYED) / NAVS_CALCULATED
	// in a period
	RT000LFR7_Metric_NAV_TIMELINESS RT000LFR7_Metric_MetricID = 4
	// Percentage of total NAVs delivered within the agreed timescale during the reporting month,
	// excluding non-provider caused delays.
	// NAVS_TIMELINESS_PROVIDER should equal 1 - (NAVS_PROVIDER_DELAYED / NAVS_CALCULATED)
	RT000LFR7_Metric_NAV_TIMELINESS_PROVIDER RT000LFR7_Metric_MetricID = 5
	// Percentage of valuations produced during the reporting month where no error(s) has been identified.
	RT000LFR7_Metric_NAV_ACCURACY RT000LFR7_Metric_MetricID = 6
	// Percentage of valuations produced during the reporting month where no error(s) has been identified.
	// This percentage is not impacted by errors where the root cause was identified as not the delegate.
	RT000LFR7_Metric_NAV_ACCURACY_PROVIDER RT000LFR7_Metric_MetricID = 7
	// The count of material nav errors where the delegate was responsible
	RT000LFR7_Metric_NAV_ERRORS_MATERIAL_PROVIDER RT000LFR7_Metric_MetricID = 8
	// The count of material nav errors where the delegate was not responsible
	RT000LFR7_Metric_NAV_ERRORS_MATERIAL_NON_PROVIDER RT000LFR7_Metric_MetricID = 9
	// The count of material nav errors where the delegate was responsible
	RT000LFR7_Metric_NAV_ERRORS_NON_MATERIAL_PROVIDER RT000LFR7_Metric_MetricID = 10
	// The count of material nav errors where the delegate was not responsible
	RT000LFR7_Metric_NAV_ERRORS_NON_MATERIAL_NON_PROVIDER RT000LFR7_Metric_MetricID = 11
	// The number of securities for which there has not been a price movement for an agreed number of consecutive business days.
	RT000LFR7_Metric_STALE_SECURITIES RT000LFR7_Metric_MetricID = 12
	// Total number of
	// Number of cash reconciliations reported between 31 to 60 days
	RT000LFR7_Metric_CASH_RECONCILIATIONS_31_TO_60_DAYS RT000LFR7_Metric_MetricID = 13
	// Number of cash reconciliations reported greater than or equal to 61 days
	RT000LFR7_Metric_CASH_RECONCILIATIONS_GREATER_THAN_60_DAYS RT000LFR7_Metric_MetricID = 14
	// Number of stock reconciliations reported between 31 to 60 days
	RT000LFR7_Metric_STOCK_RECONCILIATIONS_31_TO_60_DAYS RT000LFR7_Metric_MetricID = 15
	// Number of stock reconciliations reported greater than or equal to 61 days
	RT000LFR7_Metric_STOCK_RECONCILIATIONS_GREATER_THAN_60_DAYS RT000LFR7_Metric_MetricID = 16
	// The count of system issues that occurred during the period
	RT000LFR7_Metric_COUNT_SYSTEM_ISSUES RT000LFR7_Metric_MetricID = 17
	// The number of late financial reports
	RT000LFR7_Metric_NUMBER_LATE_FINANCIAL_REPORTS RT000LFR7_Metric_MetricID = 18
	// The net asset value at the end of the period in reporting currency
	RT000LFR7_Metric_NET_ASSET_VALUE_REPORTING_CURRENCY RT000LFR7_Metric_MetricID = 19
	// The net asset value at the end of the period in subject currency
	RT000LFR7_Metric_NET_ASSET_VALUE_SUBJECT_CURRENCY RT000LFR7_Metric_MetricID = 20
	// A security is considered difficult to price when (a) the security is fair-valued, (b) there is a single broker price, (d) stale or unchanged price, (d) it is suspended or delisted, (e) distressed fixed income, (f) defaulted fixed income as of the reporting date
	RT000LFR7_Metric_DIFFICULT_TO_PRICE_SECURITIES RT000LFR7_Metric_MetricID = 21
	// Number of securities where trading has been stopped as of the reporting date
	RT000LFR7_Metric_SUSPENDED_OR_DELISTED_SECURITIES RT000LFR7_Metric_MetricID = 22
	// Number of fixed income securities where the company or government entity is experiencing financial or operational distress, but has not defaulted as of the reporting date
	RT000LFR7_Metric_DISTRESSED_FIXED_INCOME_SECURITIES RT000LFR7_Metric_MetricID = 23
	// Number of fixed income securities where the company or government entity has defaulted as of the reporting date
	RT000LFR7_Metric_DEFAULTED_FIXED_INCOME_SECURITIES RT000LFR7_Metric_MetricID = 24
	// The number of securities held across portfolios
	RT000LFR7_Metric_SECURITIES_HELD RT000LFR7_Metric_MetricID = 25
	// The annualized TER for the reporting period
	RT000LFR7_Metric_ANNUALIZED_TER RT000LFR7_Metric_MetricID = 26
	// The annualized TER, year-to-date, as of the end of the reporting period
	RT000LFR7_Metric_ANNUALIZED_YTD_TER RT000LFR7_Metric_MetricID = 27
	// The self-assessment rating (typically on a scale of 1 - below expectations to 9 - well above expectations)
	RT000LFR7_Metric_PROVIDER_SELF_ASSESSMENT RT000LFR7_Metric_MetricID = 28
	// The service assessment rating (typically on a scale of 1 - below expectations to 9 - well above expectations)
	RT000LFR7_Metric_CUSTOMER_SERVICE_ASSESSMENT RT000LFR7_Metric_MetricID = 29
	// The number of nav delays caused by pricing
	RT000LFR7_Metric_NAV_DELAYS_PRICING RT000LFR7_Metric_MetricID = 30
	// The total number of nav delays
	RT000LFR7_Metric_NAV_DELAYS_TOTAL RT000LFR7_Metric_MetricID = 31
	// The total number of nav delays caused by trade inputs
	RT000LFR7_Metric_NAV_DELAYS_TRADE_INPUT RT000LFR7_Metric_MetricID = 32
	// The total number of nav delays caused by FX
	RT000LFR7_Metric_NAV_DELAYS_FX RT000LFR7_Metric_MetricID = 33
	// The total number of nav delays caused by cash income
	RT000LFR7_Metric_NAV_DELAYS_CASH_INCOME RT000LFR7_Metric_MetricID = 34
	// The total number of nav delays caused by corporate actions
	RT000LFR7_Metric_NAV_DELAYS_CORPORATE_ACTIONS RT000LFR7_Metric_MetricID = 35
	// The total number of nav delays caused by valuation validation
	RT000LFR7_Metric_NAV_DELAYS_VALUATION_VALIDATION RT000LFR7_Metric_MetricID = 36
	// The total number of nav delays caused by quality control
	RT000LFR7_Metric_NAV_DELAYS_QUALITY_CONTROL RT000LFR7_Metric_MetricID = 37
	// The total number of nav delays caused by system issues
	RT000LFR7_Metric_NAV_DELAYS_SYSTEM RT000LFR7_Metric_MetricID = 38
	// The total number of nav delays caused by client or third party
	RT000LFR7_Metric_NAV_DELAYS_CLIENT_OR_THIRD_PARTY RT000LFR7_Metric_MetricID = 39
	// The total number of nav delays caused by other causes
	RT000LFR7_Metric_NAV_DELAYS_OTHER RT000LFR7_Metric_MetricID = 40
	// The number of funds impacted by provider errors errors
	RT000LFR7_Metric_FUNDS_IMPACTED_BY_PROVIDER_ERRORS RT000LFR7_Metric_MetricID = 41
	// The number of funds impacted by provider errors errors
	RT000LFR7_Metric_FUNDS_IMPACTED_BY_PROVIDER_NON_PROVIDER_ERRORS RT000LFR7_Metric_MetricID = 42
	// The number of valuations impacted by provider errors
	RT000LFR7_Metric_VALUATIONS_IMPACTED_PROVIDER_ERRORS RT000LFR7_Metric_MetricID = 43
	// The number of valuations impacted by non-provider errors
	RT000LFR7_Metric_VALUATIONS_IMPACTED_NON_PROVIDER_ERRORS RT000LFR7_Metric_MetricID = 44
	// The number of valuations impacted in the current reporting period by provider errors
	RT000LFR7_Metric_VALUATIONS_IMPACTED_CURRENT_REPORTING_PERIOD_PROVIDER_ERRORS RT000LFR7_Metric_MetricID = 45
	// The number of valuations impacted in the current reporting period by non-provider errors
	RT000LFR7_Metric_VALUATIONS_IMPACTED_CURRENT_REPORTING_PERIOD_NON_PROVIDER_ERRORS RT000LFR7_Metric_MetricID = 46
	// The number of materially impacted valuations
	RT000LFR7_Metric_MATERIALLY_IMPACTED_VALUATIONS_PROVIDER_ERROR RT000LFR7_Metric_MetricID = 47
)

// Enum value maps for RT000LFR7_Metric_MetricID.
var (
	RT000LFR7_Metric_MetricID_name = map[int32]string{
		0:  "METRIC_ID_UNSPECIFIED",
		1:  "NAVS_CALCULATED",
		2:  "NAVS_PROVIDER_DELAYED",
		3:  "NAVS_NON_PROVIDER_DELAYED",
		4:  "NAV_TIMELINESS",
		5:  "NAV_TIMELINESS_PROVIDER",
		6:  "NAV_ACCURACY",
		7:  "NAV_ACCURACY_PROVIDER",
		8:  "NAV_ERRORS_MATERIAL_PROVIDER",
		9:  "NAV_ERRORS_MATERIAL_NON_PROVIDER",
		10: "NAV_ERRORS_NON_MATERIAL_PROVIDER",
		11: "NAV_ERRORS_NON_MATERIAL_NON_PROVIDER",
		12: "STALE_SECURITIES",
		13: "CASH_RECONCILIATIONS_31_TO_60_DAYS",
		14: "CASH_RECONCILIATIONS_GREATER_THAN_60_DAYS",
		15: "STOCK_RECONCILIATIONS_31_TO_60_DAYS",
		16: "STOCK_RECONCILIATIONS_GREATER_THAN_60_DAYS",
		17: "COUNT_SYSTEM_ISSUES",
		18: "NUMBER_LATE_FINANCIAL_REPORTS",
		19: "NET_ASSET_VALUE_REPORTING_CURRENCY",
		20: "NET_ASSET_VALUE_SUBJECT_CURRENCY",
		21: "DIFFICULT_TO_PRICE_SECURITIES",
		22: "SUSPENDED_OR_DELISTED_SECURITIES",
		23: "DISTRESSED_FIXED_INCOME_SECURITIES",
		24: "DEFAULTED_FIXED_INCOME_SECURITIES",
		25: "SECURITIES_HELD",
		26: "ANNUALIZED_TER",
		27: "ANNUALIZED_YTD_TER",
		28: "PROVIDER_SELF_ASSESSMENT",
		29: "CUSTOMER_SERVICE_ASSESSMENT",
		30: "NAV_DELAYS_PRICING",
		31: "NAV_DELAYS_TOTAL",
		32: "NAV_DELAYS_TRADE_INPUT",
		33: "NAV_DELAYS_FX",
		34: "NAV_DELAYS_CASH_INCOME",
		35: "NAV_DELAYS_CORPORATE_ACTIONS",
		36: "NAV_DELAYS_VALUATION_VALIDATION",
		37: "NAV_DELAYS_QUALITY_CONTROL",
		38: "NAV_DELAYS_SYSTEM",
		39: "NAV_DELAYS_CLIENT_OR_THIRD_PARTY",
		40: "NAV_DELAYS_OTHER",
		41: "FUNDS_IMPACTED_BY_PROVIDER_ERRORS",
		42: "FUNDS_IMPACTED_BY_PROVIDER_NON_PROVIDER_ERRORS",
		43: "VALUATIONS_IMPACTED_PROVIDER_ERRORS",
		44: "VALUATIONS_IMPACTED_NON_PROVIDER_ERRORS",
		45: "VALUATIONS_IMPACTED_CURRENT_REPORTING_PERIOD_PROVIDER_ERRORS",
		46: "VALUATIONS_IMPACTED_CURRENT_REPORTING_PERIOD_NON_PROVIDER_ERRORS",
		47: "MATERIALLY_IMPACTED_VALUATIONS_PROVIDER_ERROR",
	}
	RT000LFR7_Metric_MetricID_value = map[string]int32{
		"METRIC_ID_UNSPECIFIED":                                            0,
		"NAVS_CALCULATED":                                                  1,
		"NAVS_PROVIDER_DELAYED":                                            2,
		"NAVS_NON_PROVIDER_DELAYED":                                        3,
		"NAV_TIMELINESS":                                                   4,
		"NAV_TIMELINESS_PROVIDER":                                          5,
		"NAV_ACCURACY":                                                     6,
		"NAV_ACCURACY_PROVIDER":                                            7,
		"NAV_ERRORS_MATERIAL_PROVIDER":                                     8,
		"NAV_ERRORS_MATERIAL_NON_PROVIDER":                                 9,
		"NAV_ERRORS_NON_MATERIAL_PROVIDER":                                 10,
		"NAV_ERRORS_NON_MATERIAL_NON_PROVIDER":                             11,
		"STALE_SECURITIES":                                                 12,
		"CASH_RECONCILIATIONS_31_TO_60_DAYS":                               13,
		"CASH_RECONCILIATIONS_GREATER_THAN_60_DAYS":                        14,
		"STOCK_RECONCILIATIONS_31_TO_60_DAYS":                              15,
		"STOCK_RECONCILIATIONS_GREATER_THAN_60_DAYS":                       16,
		"COUNT_SYSTEM_ISSUES":                                              17,
		"NUMBER_LATE_FINANCIAL_REPORTS":                                    18,
		"NET_ASSET_VALUE_REPORTING_CURRENCY":                               19,
		"NET_ASSET_VALUE_SUBJECT_CURRENCY":                                 20,
		"DIFFICULT_TO_PRICE_SECURITIES":                                    21,
		"SUSPENDED_OR_DELISTED_SECURITIES":                                 22,
		"DISTRESSED_FIXED_INCOME_SECURITIES":                               23,
		"DEFAULTED_FIXED_INCOME_SECURITIES":                                24,
		"SECURITIES_HELD":                                                  25,
		"ANNUALIZED_TER":                                                   26,
		"ANNUALIZED_YTD_TER":                                               27,
		"PROVIDER_SELF_ASSESSMENT":                                         28,
		"CUSTOMER_SERVICE_ASSESSMENT":                                      29,
		"NAV_DELAYS_PRICING":                                               30,
		"NAV_DELAYS_TOTAL":                                                 31,
		"NAV_DELAYS_TRADE_INPUT":                                           32,
		"NAV_DELAYS_FX":                                                    33,
		"NAV_DELAYS_CASH_INCOME":                                           34,
		"NAV_DELAYS_CORPORATE_ACTIONS":                                     35,
		"NAV_DELAYS_VALUATION_VALIDATION":                                  36,
		"NAV_DELAYS_QUALITY_CONTROL":                                       37,
		"NAV_DELAYS_SYSTEM":                                                38,
		"NAV_DELAYS_CLIENT_OR_THIRD_PARTY":                                 39,
		"NAV_DELAYS_OTHER":                                                 40,
		"FUNDS_IMPACTED_BY_PROVIDER_ERRORS":                                41,
		"FUNDS_IMPACTED_BY_PROVIDER_NON_PROVIDER_ERRORS":                   42,
		"VALUATIONS_IMPACTED_PROVIDER_ERRORS":                              43,
		"VALUATIONS_IMPACTED_NON_PROVIDER_ERRORS":                          44,
		"VALUATIONS_IMPACTED_CURRENT_REPORTING_PERIOD_PROVIDER_ERRORS":     45,
		"VALUATIONS_IMPACTED_CURRENT_REPORTING_PERIOD_NON_PROVIDER_ERRORS": 46,
		"MATERIALLY_IMPACTED_VALUATIONS_PROVIDER_ERROR":                    47,
	}
)

func (x RT000LFR7_Metric_MetricID) Enum() *RT000LFR7_Metric_MetricID {
	p := new(RT000LFR7_Metric_MetricID)
	*p = x
	return p
}

func (x RT000LFR7_Metric_MetricID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RT000LFR7_Metric_MetricID) Descriptor() protoreflect.EnumDescriptor {
	return file_standards_open_v1_RT000LFR7_proto_enumTypes[0].Descriptor()
}

func (RT000LFR7_Metric_MetricID) Type() protoreflect.EnumType {
	return &file_standards_open_v1_RT000LFR7_proto_enumTypes[0]
}

func (x RT000LFR7_Metric_MetricID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RT000LFR7_Metric_MetricID.Descriptor instead.
func (RT000LFR7_Metric_MetricID) EnumDescriptor() ([]byte, []int) {
	return file_standards_open_v1_RT000LFR7_proto_rawDescGZIP(), []int{0, 0, 0}
}

// The type of value used to measure the metric
type RT000LFR7_Metric_ValueType int32

const (
	RT000LFR7_Metric_METRIC_TYPE_UNSPECIFIED RT000LFR7_Metric_ValueType = 0
	RT000LFR7_Metric_NUMBER                  RT000LFR7_Metric_ValueType = 1
	RT000LFR7_Metric_PERCENTAGE              RT000LFR7_Metric_ValueType = 2
	RT000LFR7_Metric_CURRENCY                RT000LFR7_Metric_ValueType = 3
)

// Enum value maps for RT000LFR7_Metric_ValueType.
var (
	RT000LFR7_Metric_ValueType_name = map[int32]string{
		0: "METRIC_TYPE_UNSPECIFIED",
		1: "NUMBER",
		2: "PERCENTAGE",
		3: "CURRENCY",
	}
	RT000LFR7_Metric_ValueType_value = map[string]int32{
		"METRIC_TYPE_UNSPECIFIED": 0,
		"NUMBER":                  1,
		"PERCENTAGE":              2,
		"CURRENCY":                3,
	}
)

func (x RT000LFR7_Metric_ValueType) Enum() *RT000LFR7_Metric_ValueType {
	p := new(RT000LFR7_Metric_ValueType)
	*p = x
	return p
}

func (x RT000LFR7_Metric_ValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RT000LFR7_Metric_ValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_standards_open_v1_RT000LFR7_proto_enumTypes[1].Descriptor()
}

func (RT000LFR7_Metric_ValueType) Type() protoreflect.EnumType {
	return &file_standards_open_v1_RT000LFR7_proto_enumTypes[1]
}

func (x RT000LFR7_Metric_ValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RT000LFR7_Metric_ValueType.Descriptor instead.
func (RT000LFR7_Metric_ValueType) EnumDescriptor() ([]byte, []int) {
	return file_standards_open_v1_RT000LFR7_proto_rawDescGZIP(), []int{0, 0, 1}
}

// Options for how to evaluate the metric
type RT000LFR7_Metric_EvaluationType int32

const (
	RT000LFR7_Metric_EVALUATION_TYPE_UNSPECIFIED RT000LFR7_Metric_EvaluationType = 0
	// A higher result is more favorable
	RT000LFR7_Metric_MAXIMISE RT000LFR7_Metric_EvaluationType = 1
	// A lower result is more favorable
	RT000LFR7_Metric_MINIMISE RT000LFR7_Metric_EvaluationType = 2
)

// Enum value maps for RT000LFR7_Metric_EvaluationType.
var (
	RT000LFR7_Metric_EvaluationType_name = map[int32]string{
		0: "EVALUATION_TYPE_UNSPECIFIED",
		1: "MAXIMISE",
		2: "MINIMISE",
	}
	RT000LFR7_Metric_EvaluationType_value = map[string]int32{
		"EVALUATION_TYPE_UNSPECIFIED": 0,
		"MAXIMISE":                    1,
		"MINIMISE":                    2,
	}
)

func (x RT000LFR7_Metric_EvaluationType) Enum() *RT000LFR7_Metric_EvaluationType {
	p := new(RT000LFR7_Metric_EvaluationType)
	*p = x
	return p
}

func (x RT000LFR7_Metric_EvaluationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RT000LFR7_Metric_EvaluationType) Descriptor() protoreflect.EnumDescriptor {
	return file_standards_open_v1_RT000LFR7_proto_enumTypes[2].Descriptor()
}

func (RT000LFR7_Metric_EvaluationType) Type() protoreflect.EnumType {
	return &file_standards_open_v1_RT000LFR7_proto_enumTypes[2]
}

func (x RT000LFR7_Metric_EvaluationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RT000LFR7_Metric_EvaluationType.Descriptor instead.
func (RT000LFR7_Metric_EvaluationType) EnumDescriptor() ([]byte, []int) {
	return file_standards_open_v1_RT000LFR7_proto_rawDescGZIP(), []int{0, 0, 2}
}

// UCITS Fund Accounting KPI and MI Data Exchange Template
type RT000LFR7 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// KPIs & other key quantitative metrics
	Metrics       []*RT000LFR7_Metric `protobuf:"bytes,20,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RT000LFR7) Reset() {
	*x = RT000LFR7{}
	mi := &file_standards_open_v1_RT000LFR7_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RT000LFR7) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RT000LFR7) ProtoMessage() {}

func (x *RT000LFR7) ProtoReflect() protoreflect.Message {
	mi := &file_standards_open_v1_RT000LFR7_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RT000LFR7.ProtoReflect.Descriptor instead.
func (*RT000LFR7) Descriptor() ([]byte, []int) {
	return file_standards_open_v1_RT000LFR7_proto_rawDescGZIP(), []int{0}
}

func (x *RT000LFR7) GetMetrics() []*RT000LFR7_Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Definition of a metric
type RT000LFR7_Metric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The date the metric was produced
	ProductionDate *date.Date `protobuf:"bytes,1,opt,name=production_date,json=productionDate,proto3" json:"production_date,omitempty"`
	// The start date of the reporting period of the metric (inclusive)
	// For example, if the metric measures data for the month of December 2022, 2022-12-01
	ReportingPeriodStart *date.Date `protobuf:"bytes,2,opt,name=reporting_period_start,json=reportingPeriodStart,proto3" json:"reporting_period_start,omitempty"`
	// The end date of the reporting period of the metric (inclusive)
	// For example, if the metric measures data for the month of December 2022, 2022-12-01
	ReportingPeriodEnd *date.Date `protobuf:"bytes,3,opt,name=reporting_period_end,json=reportingPeriodEnd,proto3" json:"reporting_period_end,omitempty"`
	// The relevant identifier of the umbrella
	UmbrellaFundIdentifier string `protobuf:"bytes,4,opt,name=umbrella_fund_identifier,json=umbrellaFundIdentifier,proto3" json:"umbrella_fund_identifier,omitempty"`
	// The name of the umbrella
	// Should conform to: https://openfunds.org/OFST005010 (Umbrella)
	// See: https://openfunds.org/knowledge/whitepapers/fundnames/ for more information
	UmbrellaFund string `protobuf:"bytes,5,opt,name=umbrella_fund,json=umbrellaFund,proto3" json:"umbrella_fund,omitempty"`
	// The relevant identifier of the fund
	FundIdentifier string `protobuf:"bytes,6,opt,name=fund_identifier,json=fundIdentifier,proto3" json:"fund_identifier,omitempty"`
	// The name of the fund (typically the sub-fund fund or standalone fund) that holds the security
	// Should conform to: https://openfunds.org/OFST010110 (Legal Fund Name Only)
	// Refers to the Sub-Fund in the case of an umbrella structure
	// or Fund in the case of a standalone structure
	// See: https://openfunds.org/knowledge/whitepapers/fundnames/ for more information
	Fund string `protobuf:"bytes,7,opt,name=fund,proto3" json:"fund,omitempty"`
	// The identifier of what the metric measures
	MetricId RT000LFR7_Metric_MetricID `protobuf:"varint,8,opt,name=metric_id,json=metricId,proto3,enum=standards.open.v1.RT000LFR7_Metric_MetricID" json:"metric_id,omitempty"`
	// Enumeration for how to interpret the metric value
	ValueType RT000LFR7_Metric_ValueType `protobuf:"varint,9,opt,name=value_type,json=valueType,proto3,enum=standards.open.v1.RT000LFR7_Metric_ValueType" json:"value_type,omitempty"`
	// If the metric type is "CURRENCY" then a 3-letter currency code defined in ISO 4217 must be provided.
	// The country code is required to comply with the 3-letter ISO 3166-1 alpha-3 standard.
	// The ISO 3166-1 alpha-3 is a set of 3-letter country codes to represent countries and dependent areas.
	// Make sure the provided country code is in uppercase.
	// Example: 'USA' for the United States, 'GBR' for Great Britain, 'DEU' for Germany, etc.
	CurrencyCode string `protobuf:"bytes,10,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	// The value of the metric
	Metric float64 `protobuf:"fixed64,11,opt,name=metric,proto3" json:"metric,omitempty"`
	// How to evaluate the metric (i.e. is a higher or lower value more favorable)
	EvaluationType RT000LFR7_Metric_EvaluationType `protobuf:"varint,12,opt,name=evaluation_type,json=evaluationType,proto3,enum=standards.open.v1.RT000LFR7_Metric_EvaluationType" json:"evaluation_type,omitempty"`
	// The "RED/AMBER/GREEN" designation if applicable
	Rag RedAmberGreen `protobuf:"varint,13,opt,name=rag,proto3,enum=standards.open.v1.RedAmberGreen" json:"rag,omitempty"`
	// The amber cutoff (i.e. the value above which the metric is no longer classified as "RED") if applicable
	AmberCutoff float64 `protobuf:"fixed64,14,opt,name=amber_cutoff,json=amberCutoff,proto3" json:"amber_cutoff,omitempty"`
	// The green cutoff (i.e. the value above which the metric is no longer classified as "AMBER")  if applicable
	GreenCutoff float64 `protobuf:"fixed64,15,opt,name=green_cutoff,json=greenCutoff,proto3" json:"green_cutoff,omitempty"`
	// Optional. The name of the provider
	Provider string `protobuf:"bytes,20,opt,name=provider,proto3" json:"provider,omitempty"`
	// Optional. The metric ID used by the provider
	ProviderMetricId string `protobuf:"bytes,21,opt,name=provider_metric_id,json=providerMetricId,proto3" json:"provider_metric_id,omitempty"`
	// Optional. The KPI name used by the provider
	ProviderMetricName string `protobuf:"bytes,22,opt,name=provider_metric_name,json=providerMetricName,proto3" json:"provider_metric_name,omitempty"`
	// Optional. General comments related to the metric
	GeneralCommentary string `protobuf:"bytes,81,opt,name=general_commentary,json=generalCommentary,proto3" json:"general_commentary,omitempty"`
	// Optional. Comments on the root cause of any issue
	RootCauseCommentary string `protobuf:"bytes,82,opt,name=root_cause_commentary,json=rootCauseCommentary,proto3" json:"root_cause_commentary,omitempty"`
	// Optional. Comments on the actions taken to remediate the root cause
	RemediationsCommentary string `protobuf:"bytes,83,opt,name=remediations_commentary,json=remediationsCommentary,proto3" json:"remediations_commentary,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RT000LFR7_Metric) Reset() {
	*x = RT000LFR7_Metric{}
	mi := &file_standards_open_v1_RT000LFR7_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RT000LFR7_Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RT000LFR7_Metric) ProtoMessage() {}

func (x *RT000LFR7_Metric) ProtoReflect() protoreflect.Message {
	mi := &file_standards_open_v1_RT000LFR7_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RT000LFR7_Metric.ProtoReflect.Descriptor instead.
func (*RT000LFR7_Metric) Descriptor() ([]byte, []int) {
	return file_standards_open_v1_RT000LFR7_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RT000LFR7_Metric) GetProductionDate() *date.Date {
	if x != nil {
		return x.ProductionDate
	}
	return nil
}

func (x *RT000LFR7_Metric) GetReportingPeriodStart() *date.Date {
	if x != nil {
		return x.ReportingPeriodStart
	}
	return nil
}

func (x *RT000LFR7_Metric) GetReportingPeriodEnd() *date.Date {
	if x != nil {
		return x.ReportingPeriodEnd
	}
	return nil
}

func (x *RT000LFR7_Metric) GetUmbrellaFundIdentifier() string {
	if x != nil {
		return x.UmbrellaFundIdentifier
	}
	return ""
}

func (x *RT000LFR7_Metric) GetUmbrellaFund() string {
	if x != nil {
		return x.UmbrellaFund
	}
	return ""
}

func (x *RT000LFR7_Metric) GetFundIdentifier() string {
	if x != nil {
		return x.FundIdentifier
	}
	return ""
}

func (x *RT000LFR7_Metric) GetFund() string {
	if x != nil {
		return x.Fund
	}
	return ""
}

func (x *RT000LFR7_Metric) GetMetricId() RT000LFR7_Metric_MetricID {
	if x != nil {
		return x.MetricId
	}
	return RT000LFR7_Metric_METRIC_ID_UNSPECIFIED
}

func (x *RT000LFR7_Metric) GetValueType() RT000LFR7_Metric_ValueType {
	if x != nil {
		return x.ValueType
	}
	return RT000LFR7_Metric_METRIC_TYPE_UNSPECIFIED
}

func (x *RT000LFR7_Metric) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *RT000LFR7_Metric) GetMetric() float64 {
	if x != nil {
		return x.Metric
	}
	return 0
}

func (x *RT000LFR7_Metric) GetEvaluationType() RT000LFR7_Metric_EvaluationType {
	if x != nil {
		return x.EvaluationType
	}
	return RT000LFR7_Metric_EVALUATION_TYPE_UNSPECIFIED
}

func (x *RT000LFR7_Metric) GetRag() RedAmberGreen {
	if x != nil {
		return x.Rag
	}
	return RedAmberGreen_RAG_UNSPECIFIED
}

func (x *RT000LFR7_Metric) GetAmberCutoff() float64 {
	if x != nil {
		return x.AmberCutoff
	}
	return 0
}

func (x *RT000LFR7_Metric) GetGreenCutoff() float64 {
	if x != nil {
		return x.GreenCutoff
	}
	return 0
}

func (x *RT000LFR7_Metric) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *RT000LFR7_Metric) GetProviderMetricId() string {
	if x != nil {
		return x.ProviderMetricId
	}
	return ""
}

func (x *RT000LFR7_Metric) GetProviderMetricName() string {
	if x != nil {
		return x.ProviderMetricName
	}
	return ""
}

func (x *RT000LFR7_Metric) GetGeneralCommentary() string {
	if x != nil {
		return x.GeneralCommentary
	}
	return ""
}

func (x *RT000LFR7_Metric) GetRootCauseCommentary() string {
	if x != nil {
		return x.RootCauseCommentary
	}
	return ""
}

func (x *RT000LFR7_Metric) GetRemediationsCommentary() string {
	if x != nil {
		return x.RemediationsCommentary
	}
	return ""
}

var File_standards_open_v1_RT000LFR7_proto protoreflect.FileDescriptor

const file_standards_open_v1_RT000LFR7_proto_rawDesc = "" +
	"\n" +
	"!standards/open/v1/RT000LFR7.proto\x12\x11standards.open.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x19google/api/resource.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x17google/type/month.proto\x1a\x16google/type/date.proto\x1a\x1bstandards/open/v1/rag.proto\"\x97\x17\n" +
	"\tRT000LFR7\x12=\n" +
	"\ametrics\x18\x14 \x03(\v2#.standards.open.v1.RT000LFR7.MetricR\ametrics\x1a\xca\x16\n" +
	"\x06Metric\x12:\n" +
	"\x0fproduction_date\x18\x01 \x01(\v2\x11.google.type.DateR\x0eproductionDate\x12G\n" +
	"\x16reporting_period_start\x18\x02 \x01(\v2\x11.google.type.DateR\x14reportingPeriodStart\x12C\n" +
	"\x14reporting_period_end\x18\x03 \x01(\v2\x11.google.type.DateR\x12reportingPeriodEnd\x128\n" +
	"\x18umbrella_fund_identifier\x18\x04 \x01(\tR\x16umbrellaFundIdentifier\x12#\n" +
	"\rumbrella_fund\x18\x05 \x01(\tR\fumbrellaFund\x12'\n" +
	"\x0ffund_identifier\x18\x06 \x01(\tR\x0efundIdentifier\x12\x12\n" +
	"\x04fund\x18\a \x01(\tR\x04fund\x12I\n" +
	"\tmetric_id\x18\b \x01(\x0e2,.standards.open.v1.RT000LFR7.Metric.MetricIDR\bmetricId\x12L\n" +
	"\n" +
	"value_type\x18\t \x01(\x0e2-.standards.open.v1.RT000LFR7.Metric.ValueTypeR\tvalueType\x12#\n" +
	"\rcurrency_code\x18\n" +
	" \x01(\tR\fcurrencyCode\x12\x16\n" +
	"\x06metric\x18\v \x01(\x01R\x06metric\x12[\n" +
	"\x0fevaluation_type\x18\f \x01(\x0e22.standards.open.v1.RT000LFR7.Metric.EvaluationTypeR\x0eevaluationType\x122\n" +
	"\x03rag\x18\r \x01(\x0e2 .standards.open.v1.RedAmberGreenR\x03rag\x12!\n" +
	"\famber_cutoff\x18\x0e \x01(\x01R\vamberCutoff\x12!\n" +
	"\fgreen_cutoff\x18\x0f \x01(\x01R\vgreenCutoff\x12\x1a\n" +
	"\bprovider\x18\x14 \x01(\tR\bprovider\x12,\n" +
	"\x12provider_metric_id\x18\x15 \x01(\tR\x10providerMetricId\x120\n" +
	"\x14provider_metric_name\x18\x16 \x01(\tR\x12providerMetricName\x12-\n" +
	"\x12general_commentary\x18Q \x01(\tR\x11generalCommentary\x122\n" +
	"\x15root_cause_commentary\x18R \x01(\tR\x13rootCauseCommentary\x127\n" +
	"\x17remediations_commentary\x18S \x01(\tR\x16remediationsCommentary\"\xf1\f\n" +
	"\bMetricID\x12\x19\n" +
	"\x15METRIC_ID_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fNAVS_CALCULATED\x10\x01\x12\x19\n" +
	"\x15NAVS_PROVIDER_DELAYED\x10\x02\x12\x1d\n" +
	"\x19NAVS_NON_PROVIDER_DELAYED\x10\x03\x12\x12\n" +
	"\x0eNAV_TIMELINESS\x10\x04\x12\x1b\n" +
	"\x17NAV_TIMELINESS_PROVIDER\x10\x05\x12\x10\n" +
	"\fNAV_ACCURACY\x10\x06\x12\x19\n" +
	"\x15NAV_ACCURACY_PROVIDER\x10\a\x12 \n" +
	"\x1cNAV_ERRORS_MATERIAL_PROVIDER\x10\b\x12$\n" +
	" NAV_ERRORS_MATERIAL_NON_PROVIDER\x10\t\x12$\n" +
	" NAV_ERRORS_NON_MATERIAL_PROVIDER\x10\n" +
	"\x12(\n" +
	"$NAV_ERRORS_NON_MATERIAL_NON_PROVIDER\x10\v\x12\x14\n" +
	"\x10STALE_SECURITIES\x10\f\x12&\n" +
	"\"CASH_RECONCILIATIONS_31_TO_60_DAYS\x10\r\x12-\n" +
	")CASH_RECONCILIATIONS_GREATER_THAN_60_DAYS\x10\x0e\x12'\n" +
	"#STOCK_RECONCILIATIONS_31_TO_60_DAYS\x10\x0f\x12.\n" +
	"*STOCK_RECONCILIATIONS_GREATER_THAN_60_DAYS\x10\x10\x12\x17\n" +
	"\x13COUNT_SYSTEM_ISSUES\x10\x11\x12!\n" +
	"\x1dNUMBER_LATE_FINANCIAL_REPORTS\x10\x12\x12&\n" +
	"\"NET_ASSET_VALUE_REPORTING_CURRENCY\x10\x13\x12$\n" +
	" NET_ASSET_VALUE_SUBJECT_CURRENCY\x10\x14\x12!\n" +
	"\x1dDIFFICULT_TO_PRICE_SECURITIES\x10\x15\x12$\n" +
	" SUSPENDED_OR_DELISTED_SECURITIES\x10\x16\x12&\n" +
	"\"DISTRESSED_FIXED_INCOME_SECURITIES\x10\x17\x12%\n" +
	"!DEFAULTED_FIXED_INCOME_SECURITIES\x10\x18\x12\x13\n" +
	"\x0fSECURITIES_HELD\x10\x19\x12\x12\n" +
	"\x0eANNUALIZED_TER\x10\x1a\x12\x16\n" +
	"\x12ANNUALIZED_YTD_TER\x10\x1b\x12\x1c\n" +
	"\x18PROVIDER_SELF_ASSESSMENT\x10\x1c\x12\x1f\n" +
	"\x1bCUSTOMER_SERVICE_ASSESSMENT\x10\x1d\x12\x16\n" +
	"\x12NAV_DELAYS_PRICING\x10\x1e\x12\x14\n" +
	"\x10NAV_DELAYS_TOTAL\x10\x1f\x12\x1a\n" +
	"\x16NAV_DELAYS_TRADE_INPUT\x10 \x12\x11\n" +
	"\rNAV_DELAYS_FX\x10!\x12\x1a\n" +
	"\x16NAV_DELAYS_CASH_INCOME\x10\"\x12 \n" +
	"\x1cNAV_DELAYS_CORPORATE_ACTIONS\x10#\x12#\n" +
	"\x1fNAV_DELAYS_VALUATION_VALIDATION\x10$\x12\x1e\n" +
	"\x1aNAV_DELAYS_QUALITY_CONTROL\x10%\x12\x15\n" +
	"\x11NAV_DELAYS_SYSTEM\x10&\x12$\n" +
	" NAV_DELAYS_CLIENT_OR_THIRD_PARTY\x10'\x12\x14\n" +
	"\x10NAV_DELAYS_OTHER\x10(\x12%\n" +
	"!FUNDS_IMPACTED_BY_PROVIDER_ERRORS\x10)\x122\n" +
	".FUNDS_IMPACTED_BY_PROVIDER_NON_PROVIDER_ERRORS\x10*\x12'\n" +
	"#VALUATIONS_IMPACTED_PROVIDER_ERRORS\x10+\x12+\n" +
	"'VALUATIONS_IMPACTED_NON_PROVIDER_ERRORS\x10,\x12@\n" +
	"<VALUATIONS_IMPACTED_CURRENT_REPORTING_PERIOD_PROVIDER_ERRORS\x10-\x12D\n" +
	"@VALUATIONS_IMPACTED_CURRENT_REPORTING_PERIOD_NON_PROVIDER_ERRORS\x10.\x121\n" +
	"-MATERIALLY_IMPACTED_VALUATIONS_PROVIDER_ERROR\x10/\"R\n" +
	"\tValueType\x12\x1b\n" +
	"\x17METRIC_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06NUMBER\x10\x01\x12\x0e\n" +
	"\n" +
	"PERCENTAGE\x10\x02\x12\f\n" +
	"\bCURRENCY\x10\x03\"M\n" +
	"\x0eEvaluationType\x12\x1f\n" +
	"\x1bEVALUATION_TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bMAXIMISE\x10\x01\x12\f\n" +
	"\bMINIMISE\x10\x02B(Z&go.alis.build/common/standards/open/v1b\x06proto3"

var (
	file_standards_open_v1_RT000LFR7_proto_rawDescOnce sync.Once
	file_standards_open_v1_RT000LFR7_proto_rawDescData []byte
)

func file_standards_open_v1_RT000LFR7_proto_rawDescGZIP() []byte {
	file_standards_open_v1_RT000LFR7_proto_rawDescOnce.Do(func() {
		file_standards_open_v1_RT000LFR7_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_standards_open_v1_RT000LFR7_proto_rawDesc), len(file_standards_open_v1_RT000LFR7_proto_rawDesc)))
	})
	return file_standards_open_v1_RT000LFR7_proto_rawDescData
}

var file_standards_open_v1_RT000LFR7_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_standards_open_v1_RT000LFR7_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_standards_open_v1_RT000LFR7_proto_goTypes = []any{
	(RT000LFR7_Metric_MetricID)(0),       // 0: standards.open.v1.RT000LFR7.Metric.MetricID
	(RT000LFR7_Metric_ValueType)(0),      // 1: standards.open.v1.RT000LFR7.Metric.ValueType
	(RT000LFR7_Metric_EvaluationType)(0), // 2: standards.open.v1.RT000LFR7.Metric.EvaluationType
	(*RT000LFR7)(nil),                    // 3: standards.open.v1.RT000LFR7
	(*RT000LFR7_Metric)(nil),             // 4: standards.open.v1.RT000LFR7.Metric
	(*date.Date)(nil),                    // 5: google.type.Date
	(RedAmberGreen)(0),                   // 6: standards.open.v1.RedAmberGreen
}
var file_standards_open_v1_RT000LFR7_proto_depIdxs = []int32{
	4, // 0: standards.open.v1.RT000LFR7.metrics:type_name -> standards.open.v1.RT000LFR7.Metric
	5, // 1: standards.open.v1.RT000LFR7.Metric.production_date:type_name -> google.type.Date
	5, // 2: standards.open.v1.RT000LFR7.Metric.reporting_period_start:type_name -> google.type.Date
	5, // 3: standards.open.v1.RT000LFR7.Metric.reporting_period_end:type_name -> google.type.Date
	0, // 4: standards.open.v1.RT000LFR7.Metric.metric_id:type_name -> standards.open.v1.RT000LFR7.Metric.MetricID
	1, // 5: standards.open.v1.RT000LFR7.Metric.value_type:type_name -> standards.open.v1.RT000LFR7.Metric.ValueType
	2, // 6: standards.open.v1.RT000LFR7.Metric.evaluation_type:type_name -> standards.open.v1.RT000LFR7.Metric.EvaluationType
	6, // 7: standards.open.v1.RT000LFR7.Metric.rag:type_name -> standards.open.v1.RedAmberGreen
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_standards_open_v1_RT000LFR7_proto_init() }
func file_standards_open_v1_RT000LFR7_proto_init() {
	if File_standards_open_v1_RT000LFR7_proto != nil {
		return
	}
	file_standards_open_v1_rag_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_standards_open_v1_RT000LFR7_proto_rawDesc), len(file_standards_open_v1_RT000LFR7_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_standards_open_v1_RT000LFR7_proto_goTypes,
		DependencyIndexes: file_standards_open_v1_RT000LFR7_proto_depIdxs,
		EnumInfos:         file_standards_open_v1_RT000LFR7_proto_enumTypes,
		MessageInfos:      file_standards_open_v1_RT000LFR7_proto_msgTypes,
	}.Build()
	File_standards_open_v1_RT000LFR7_proto = out.File
	file_standards_open_v1_RT000LFR7_proto_goTypes = nil
	file_standards_open_v1_RT000LFR7_proto_depIdxs = nil
}
