// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: standards/open/v1/RT0003G88.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This report provides asset allocation data to the Allan Gray Retail Platform for certain  Rezco funds
type RT0003G88 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RT0003G88) Reset() {
	*x = RT0003G88{}
	mi := &file_standards_open_v1_RT0003G88_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RT0003G88) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RT0003G88) ProtoMessage() {}

func (x *RT0003G88) ProtoReflect() protoreflect.Message {
	mi := &file_standards_open_v1_RT0003G88_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RT0003G88.ProtoReflect.Descriptor instead.
func (*RT0003G88) Descriptor() ([]byte, []int) {
	return file_standards_open_v1_RT0003G88_proto_rawDescGZIP(), []int{0}
}

var File_standards_open_v1_RT0003G88_proto protoreflect.FileDescriptor

const file_standards_open_v1_RT0003G88_proto_rawDesc = "" +
	"\n" +
	"!standards/open/v1/RT0003G88.proto\x12\x11standards.open.v1\"\v\n" +
	"\tRT0003G88B(Z&go.alis.build/common/standards/open/v1b\x06proto3"

var (
	file_standards_open_v1_RT0003G88_proto_rawDescOnce sync.Once
	file_standards_open_v1_RT0003G88_proto_rawDescData []byte
)

func file_standards_open_v1_RT0003G88_proto_rawDescGZIP() []byte {
	file_standards_open_v1_RT0003G88_proto_rawDescOnce.Do(func() {
		file_standards_open_v1_RT0003G88_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_standards_open_v1_RT0003G88_proto_rawDesc), len(file_standards_open_v1_RT0003G88_proto_rawDesc)))
	})
	return file_standards_open_v1_RT0003G88_proto_rawDescData
}

var file_standards_open_v1_RT0003G88_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_standards_open_v1_RT0003G88_proto_goTypes = []any{
	(*RT0003G88)(nil), // 0: standards.open.v1.RT0003G88
}
var file_standards_open_v1_RT0003G88_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_standards_open_v1_RT0003G88_proto_init() }
func file_standards_open_v1_RT0003G88_proto_init() {
	if File_standards_open_v1_RT0003G88_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_standards_open_v1_RT0003G88_proto_rawDesc), len(file_standards_open_v1_RT0003G88_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_standards_open_v1_RT0003G88_proto_goTypes,
		DependencyIndexes: file_standards_open_v1_RT0003G88_proto_depIdxs,
		MessageInfos:      file_standards_open_v1_RT0003G88_proto_msgTypes,
	}.Build()
	File_standards_open_v1_RT0003G88_proto = out.File
	file_standards_open_v1_RT0003G88_proto_goTypes = nil
	file_standards_open_v1_RT0003G88_proto_depIdxs = nil
}
