// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.4
// source: alis/open/config/v1/config.proto

package v1

import (
	v1 "go.alis.build/common/alis/open/iam/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The definition of a product config which is passed in as an environment variable
type ProductConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the product
	// Format: organisations/([a-z][a-z0-9]{2,9})/products/([a-z]{2})
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The id of the product
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// The google project id of the product
	ProjectId string `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// The google project number of the product
	ProjectNumber string `protobuf:"bytes,4,opt,name=project_number,json=projectNumber,proto3" json:"project_number,omitempty"`
	// The iam roles defined for the product
	Roles         []*v1.Role `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductConfig) Reset() {
	*x = ProductConfig{}
	mi := &file_alis_open_config_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductConfig) ProtoMessage() {}

func (x *ProductConfig) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_config_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductConfig.ProtoReflect.Descriptor instead.
func (*ProductConfig) Descriptor() ([]byte, []int) {
	return file_alis_open_config_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *ProductConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductConfig) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ProductConfig) GetProjectNumber() string {
	if x != nil {
		return x.ProjectNumber
	}
	return ""
}

func (x *ProductConfig) GetRoles() []*v1.Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

var File_alis_open_config_v1_config_proto protoreflect.FileDescriptor

const file_alis_open_config_v1_config_proto_rawDesc = "" +
	"\n" +
	" alis/open/config/v1/config.proto\x12\x13alis.open.config.v1\x1a\x1balis/open/iam/v1/role.proto\"\xa7\x01\n" +
	"\rProductConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12%\n" +
	"\x0eproject_number\x18\x04 \x01(\tR\rprojectNumber\x12,\n" +
	"\x05roles\x18\x05 \x03(\v2\x16.alis.open.iam.v1.RoleR\x05rolesB*Z(go.alis.build/common/alis/open/config/v1b\x06proto3"

var (
	file_alis_open_config_v1_config_proto_rawDescOnce sync.Once
	file_alis_open_config_v1_config_proto_rawDescData []byte
)

func file_alis_open_config_v1_config_proto_rawDescGZIP() []byte {
	file_alis_open_config_v1_config_proto_rawDescOnce.Do(func() {
		file_alis_open_config_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alis_open_config_v1_config_proto_rawDesc), len(file_alis_open_config_v1_config_proto_rawDesc)))
	})
	return file_alis_open_config_v1_config_proto_rawDescData
}

var file_alis_open_config_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_alis_open_config_v1_config_proto_goTypes = []any{
	(*ProductConfig)(nil), // 0: alis.open.config.v1.ProductConfig
	(*v1.Role)(nil),       // 1: alis.open.iam.v1.Role
}
var file_alis_open_config_v1_config_proto_depIdxs = []int32{
	1, // 0: alis.open.config.v1.ProductConfig.roles:type_name -> alis.open.iam.v1.Role
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_alis_open_config_v1_config_proto_init() }
func file_alis_open_config_v1_config_proto_init() {
	if File_alis_open_config_v1_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alis_open_config_v1_config_proto_rawDesc), len(file_alis_open_config_v1_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alis_open_config_v1_config_proto_goTypes,
		DependencyIndexes: file_alis_open_config_v1_config_proto_depIdxs,
		MessageInfos:      file_alis_open_config_v1_config_proto_msgTypes,
	}.Build()
	File_alis_open_config_v1_config_proto = out.File
	file_alis_open_config_v1_config_proto_goTypes = nil
	file_alis_open_config_v1_config_proto_depIdxs = nil
}
