// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/open/iam/v1/oauth.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-03-26 07:17:43 UTC

package v1

const ()
