// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.24.4
// source: alis/open/iam/v1/user.proto

package v1

import (
	context "context"
	v1 "go.alis.build/common/alis/open/validation/v1"
	v11 "go.alis.build/common/google/iam/v1"
	protobuf "go.alis.build/common/google/protobuf"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UsersService_ValidateMessage_FullMethodName          = "/alis.open.iam.v1.UsersService/ValidateMessage"
	UsersService_RetrieveRules_FullMethodName            = "/alis.open.iam.v1.UsersService/RetrieveRules"
	UsersService_GetIamPolicy_FullMethodName             = "/alis.open.iam.v1.UsersService/GetIamPolicy"
	UsersService_SetIamPolicy_FullMethodName             = "/alis.open.iam.v1.UsersService/SetIamPolicy"
	UsersService_TestIamPermissions_FullMethodName       = "/alis.open.iam.v1.UsersService/TestIamPermissions"
	UsersService_AddIamBindings_FullMethodName           = "/alis.open.iam.v1.UsersService/AddIamBindings"
	UsersService_RemoveIamBindings_FullMethodName        = "/alis.open.iam.v1.UsersService/RemoveIamBindings"
	UsersService_GetUser_FullMethodName                  = "/alis.open.iam.v1.UsersService/GetUser"
	UsersService_CreateUser_FullMethodName               = "/alis.open.iam.v1.UsersService/CreateUser"
	UsersService_UpdateUser_FullMethodName               = "/alis.open.iam.v1.UsersService/UpdateUser"
	UsersService_DeleteUser_FullMethodName               = "/alis.open.iam.v1.UsersService/DeleteUser"
	UsersService_ListUsers_FullMethodName                = "/alis.open.iam.v1.UsersService/ListUsers"
	UsersService_RetrieveUserByEmail_FullMethodName      = "/alis.open.iam.v1.UsersService/RetrieveUserByEmail"
	UsersService_LookupUser_FullMethodName               = "/alis.open.iam.v1.UsersService/LookupUser"
	UsersService_BatchRetrieveMaskedUsers_FullMethodName = "/alis.open.iam.v1.UsersService/BatchRetrieveMaskedUsers"
	UsersService_RetrieveMaskedUsers_FullMethodName      = "/alis.open.iam.v1.UsersService/RetrieveMaskedUsers"
	UsersService_RetrieveMaskedUser_FullMethodName       = "/alis.open.iam.v1.UsersService/RetrieveMaskedUser"
	UsersService_EditUserInfo_FullMethodName             = "/alis.open.iam.v1.UsersService/EditUserInfo"
	UsersService_EditUserMetadata_FullMethodName         = "/alis.open.iam.v1.UsersService/EditUserMetadata"
	UsersService_RetrieveMyUser_FullMethodName           = "/alis.open.iam.v1.UsersService/RetrieveMyUser"
	UsersService_EditMyInfo_FullMethodName               = "/alis.open.iam.v1.UsersService/EditMyInfo"
	UsersService_EditMyMetadata_FullMethodName           = "/alis.open.iam.v1.UsersService/EditMyMetadata"
	UsersService_RemoveMyUser_FullMethodName             = "/alis.open.iam.v1.UsersService/RemoveMyUser"
	UsersService_SyncToGoogleGroup_FullMethodName        = "/alis.open.iam.v1.UsersService/SyncToGoogleGroup"
	UsersService_SetUserPicture_FullMethodName           = "/alis.open.iam.v1.UsersService/SetUserPicture"
)

// UsersServiceClient is the client API for UsersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UsersService provides RPCs for managing User resources.
type UsersServiceClient interface {
	// Validates any proto message that is used directly or indirectly by this service.
	// Most common use case is to validate request messages from a client-side application.
	ValidateMessage(ctx context.Context, in *v1.ValidateMessageRequest, opts ...grpc.CallOption) (*v1.ValidateMessageResponse, error)
	// Retrieves the validation rules for any proto message that is used directly or indirectly by this service.
	// Serves as live auto-documentation of the validation rules in this service.
	RetrieveRules(ctx context.Context, in *v1.RetrieveRulesRequest, opts ...grpc.CallOption) (*v1.RetrieveRulesResponse, error)
	// Gets the IAM policy for a resource implemented in this service.
	GetIamPolicy(ctx context.Context, in *v11.GetIamPolicyRequest, opts ...grpc.CallOption) (*v11.Policy, error)
	// Sets the IAM policy for a resource implemented in this service.
	SetIamPolicy(ctx context.Context, in *v11.SetIamPolicyRequest, opts ...grpc.CallOption) (*v11.Policy, error)
	// Returns permissions that a caller has on the specified resource.
	TestIamPermissions(ctx context.Context, in *v11.TestIamPermissionsRequest, opts ...grpc.CallOption) (*v11.TestIamPermissionsResponse, error)
	// Adds principals or updates the roles existing principals have on an IAM Policy protected resource.
	AddIamBindings(ctx context.Context, in *AddIamBindingsRequest, opts ...grpc.CallOption) (*v11.Policy, error)
	// Removes principals or some of the roles they have on an IAM Policy protected resource.
	RemoveIamBindings(ctx context.Context, in *RemoveIamBindingsRequest, opts ...grpc.CallOption) (*v11.Policy, error)
	// Gets information about a User.
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	// Creates a new User.
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error)
	// Updates a User.
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*User, error)
	// Deletes a User.
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*protobuf.Empty, error)
	// Lists Users. Results are sorted by name, ascending.
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	// Retrieve a User by their email.
	RetrieveUserByEmail(ctx context.Context, in *RetrieveUserByEmailRequest, opts ...grpc.CallOption) (*User, error)
	// Look up a User based on a search text.
	//
	// This method retrieves a set of results, which are Users, based on the request.
	// The lookup for these Users are done across the given_name, family_name, email and contact number.
	LookupUser(ctx context.Context, in *LookupUserRequest, opts ...grpc.CallOption) (*LookupUserResponse, error)
	// Retrieves the set of Users requested, with only a
	// subset of the User information returned.
	//
	// This is equivalent to a BatchGet method, but only a subset of the User information,
	// which does not contain any sensitive information such as email or group configurations.
	//
	// Differs from the RetrieveMaskedUsers method in that it returns only
	// the Users that were specified in the request.
	BatchRetrieveMaskedUsers(ctx context.Context, in *BatchRetrieveMaskedUsersRequest, opts ...grpc.CallOption) (*BatchRetrieveMaskedUsersResponse, error)
	// Retrieves all Users that match the filter criteria, if specified,
	// with only a subset of the User information.
	//
	// This is equivalent to a List method, but only a subset of the User information,
	// which does not contain any sensitive information such as email or group configurations.
	//
	// Differs from the BatchRetrieveMaskedUsers method in that it returns all
	// the Users that match the filter, if the filter is specified.
	//
	// This is useful for displaying a list of Users without revealing sensitive information like email.
	RetrieveMaskedUsers(ctx context.Context, in *RetrieveMaskedUsersRequest, opts ...grpc.CallOption) (*RetrieveMaskedUsersResponse, error)
	// Retrieves a User with some of their details hidden.
	// This is useful for displaying a User without revealing sensitive information like email.
	// Both name and email can be used to retrieve the User.
	RetrieveMaskedUser(ctx context.Context, in *RetrieveMaskedUserRequest, opts ...grpc.CallOption) (*MaskedUser, error)
	// Edits a User's non-auth related information like family name and picture.
	EditUserInfo(ctx context.Context, in *EditUserInfoRequest, opts ...grpc.CallOption) (*User, error)
	// Edits a User's metadata
	EditUserMetadata(ctx context.Context, in *EditUserMetadataRequest, opts ...grpc.CallOption) (*User, error)
	// Retrieves the currently signed in user.
	// This is useful for client-side applications to get the signed in user's information.
	RetrieveMyUser(ctx context.Context, in *RetrieveMyUserRequest, opts ...grpc.CallOption) (*User, error)
	// Edits the info of the currently signed in user.
	// This is useful for client-side applications to edit the signed in user's information.
	// Allows the user to edit their given_name, family_name, picture, contact_number, position, education, linkedin_uri and metadata.
	EditMyInfo(ctx context.Context, in *EditMyInfoRequest, opts ...grpc.CallOption) (*User, error)
	// Edits the metadata of the currently signed in user.
	// This is useful for client-side applications to edit the signed in user's metadata.
	EditMyMetadata(ctx context.Context, in *EditMyMetadataRequest, opts ...grpc.CallOption) (*User, error)
	// Removes the currently signed in user.
	// This is useful if a user wants to delete their account.
	RemoveMyUser(ctx context.Context, in *RemoveMyUserRequest, opts ...grpc.CallOption) (*protobuf.Empty, error)
	// Syncs all google User's to the google group configured in the IamConfig.
	// Will not delete service accounts.
	SyncToGoogleGroup(ctx context.Context, in *SyncToGoogleGroupRequest, opts ...grpc.CallOption) (*SyncToGoogleGroupResponse, error)
	// Sets the user's profile picture
	SetUserPicture(ctx context.Context, in *SetUserPictureRequest, opts ...grpc.CallOption) (*SetUserPictureResponse, error)
}

type usersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUsersServiceClient(cc grpc.ClientConnInterface) UsersServiceClient {
	return &usersServiceClient{cc}
}

func (c *usersServiceClient) ValidateMessage(ctx context.Context, in *v1.ValidateMessageRequest, opts ...grpc.CallOption) (*v1.ValidateMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ValidateMessageResponse)
	err := c.cc.Invoke(ctx, UsersService_ValidateMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) RetrieveRules(ctx context.Context, in *v1.RetrieveRulesRequest, opts ...grpc.CallOption) (*v1.RetrieveRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.RetrieveRulesResponse)
	err := c.cc.Invoke(ctx, UsersService_RetrieveRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) GetIamPolicy(ctx context.Context, in *v11.GetIamPolicyRequest, opts ...grpc.CallOption) (*v11.Policy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v11.Policy)
	err := c.cc.Invoke(ctx, UsersService_GetIamPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) SetIamPolicy(ctx context.Context, in *v11.SetIamPolicyRequest, opts ...grpc.CallOption) (*v11.Policy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v11.Policy)
	err := c.cc.Invoke(ctx, UsersService_SetIamPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) TestIamPermissions(ctx context.Context, in *v11.TestIamPermissionsRequest, opts ...grpc.CallOption) (*v11.TestIamPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v11.TestIamPermissionsResponse)
	err := c.cc.Invoke(ctx, UsersService_TestIamPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) AddIamBindings(ctx context.Context, in *AddIamBindingsRequest, opts ...grpc.CallOption) (*v11.Policy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v11.Policy)
	err := c.cc.Invoke(ctx, UsersService_AddIamBindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) RemoveIamBindings(ctx context.Context, in *RemoveIamBindingsRequest, opts ...grpc.CallOption) (*v11.Policy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v11.Policy)
	err := c.cc.Invoke(ctx, UsersService_RemoveIamBindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UsersService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UsersService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UsersService_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*protobuf.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(protobuf.Empty)
	err := c.cc.Invoke(ctx, UsersService_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, UsersService_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) RetrieveUserByEmail(ctx context.Context, in *RetrieveUserByEmailRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UsersService_RetrieveUserByEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) LookupUser(ctx context.Context, in *LookupUserRequest, opts ...grpc.CallOption) (*LookupUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupUserResponse)
	err := c.cc.Invoke(ctx, UsersService_LookupUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) BatchRetrieveMaskedUsers(ctx context.Context, in *BatchRetrieveMaskedUsersRequest, opts ...grpc.CallOption) (*BatchRetrieveMaskedUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchRetrieveMaskedUsersResponse)
	err := c.cc.Invoke(ctx, UsersService_BatchRetrieveMaskedUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) RetrieveMaskedUsers(ctx context.Context, in *RetrieveMaskedUsersRequest, opts ...grpc.CallOption) (*RetrieveMaskedUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveMaskedUsersResponse)
	err := c.cc.Invoke(ctx, UsersService_RetrieveMaskedUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) RetrieveMaskedUser(ctx context.Context, in *RetrieveMaskedUserRequest, opts ...grpc.CallOption) (*MaskedUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaskedUser)
	err := c.cc.Invoke(ctx, UsersService_RetrieveMaskedUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) EditUserInfo(ctx context.Context, in *EditUserInfoRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UsersService_EditUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) EditUserMetadata(ctx context.Context, in *EditUserMetadataRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UsersService_EditUserMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) RetrieveMyUser(ctx context.Context, in *RetrieveMyUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UsersService_RetrieveMyUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) EditMyInfo(ctx context.Context, in *EditMyInfoRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UsersService_EditMyInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) EditMyMetadata(ctx context.Context, in *EditMyMetadataRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UsersService_EditMyMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) RemoveMyUser(ctx context.Context, in *RemoveMyUserRequest, opts ...grpc.CallOption) (*protobuf.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(protobuf.Empty)
	err := c.cc.Invoke(ctx, UsersService_RemoveMyUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) SyncToGoogleGroup(ctx context.Context, in *SyncToGoogleGroupRequest, opts ...grpc.CallOption) (*SyncToGoogleGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncToGoogleGroupResponse)
	err := c.cc.Invoke(ctx, UsersService_SyncToGoogleGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) SetUserPicture(ctx context.Context, in *SetUserPictureRequest, opts ...grpc.CallOption) (*SetUserPictureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetUserPictureResponse)
	err := c.cc.Invoke(ctx, UsersService_SetUserPicture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServiceServer is the server API for UsersService service.
// All implementations must embed UnimplementedUsersServiceServer
// for forward compatibility.
//
// UsersService provides RPCs for managing User resources.
type UsersServiceServer interface {
	// Validates any proto message that is used directly or indirectly by this service.
	// Most common use case is to validate request messages from a client-side application.
	ValidateMessage(context.Context, *v1.ValidateMessageRequest) (*v1.ValidateMessageResponse, error)
	// Retrieves the validation rules for any proto message that is used directly or indirectly by this service.
	// Serves as live auto-documentation of the validation rules in this service.
	RetrieveRules(context.Context, *v1.RetrieveRulesRequest) (*v1.RetrieveRulesResponse, error)
	// Gets the IAM policy for a resource implemented in this service.
	GetIamPolicy(context.Context, *v11.GetIamPolicyRequest) (*v11.Policy, error)
	// Sets the IAM policy for a resource implemented in this service.
	SetIamPolicy(context.Context, *v11.SetIamPolicyRequest) (*v11.Policy, error)
	// Returns permissions that a caller has on the specified resource.
	TestIamPermissions(context.Context, *v11.TestIamPermissionsRequest) (*v11.TestIamPermissionsResponse, error)
	// Adds principals or updates the roles existing principals have on an IAM Policy protected resource.
	AddIamBindings(context.Context, *AddIamBindingsRequest) (*v11.Policy, error)
	// Removes principals or some of the roles they have on an IAM Policy protected resource.
	RemoveIamBindings(context.Context, *RemoveIamBindingsRequest) (*v11.Policy, error)
	// Gets information about a User.
	GetUser(context.Context, *GetUserRequest) (*User, error)
	// Creates a new User.
	CreateUser(context.Context, *CreateUserRequest) (*User, error)
	// Updates a User.
	UpdateUser(context.Context, *UpdateUserRequest) (*User, error)
	// Deletes a User.
	DeleteUser(context.Context, *DeleteUserRequest) (*protobuf.Empty, error)
	// Lists Users. Results are sorted by name, ascending.
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	// Retrieve a User by their email.
	RetrieveUserByEmail(context.Context, *RetrieveUserByEmailRequest) (*User, error)
	// Look up a User based on a search text.
	//
	// This method retrieves a set of results, which are Users, based on the request.
	// The lookup for these Users are done across the given_name, family_name, email and contact number.
	LookupUser(context.Context, *LookupUserRequest) (*LookupUserResponse, error)
	// Retrieves the set of Users requested, with only a
	// subset of the User information returned.
	//
	// This is equivalent to a BatchGet method, but only a subset of the User information,
	// which does not contain any sensitive information such as email or group configurations.
	//
	// Differs from the RetrieveMaskedUsers method in that it returns only
	// the Users that were specified in the request.
	BatchRetrieveMaskedUsers(context.Context, *BatchRetrieveMaskedUsersRequest) (*BatchRetrieveMaskedUsersResponse, error)
	// Retrieves all Users that match the filter criteria, if specified,
	// with only a subset of the User information.
	//
	// This is equivalent to a List method, but only a subset of the User information,
	// which does not contain any sensitive information such as email or group configurations.
	//
	// Differs from the BatchRetrieveMaskedUsers method in that it returns all
	// the Users that match the filter, if the filter is specified.
	//
	// This is useful for displaying a list of Users without revealing sensitive information like email.
	RetrieveMaskedUsers(context.Context, *RetrieveMaskedUsersRequest) (*RetrieveMaskedUsersResponse, error)
	// Retrieves a User with some of their details hidden.
	// This is useful for displaying a User without revealing sensitive information like email.
	// Both name and email can be used to retrieve the User.
	RetrieveMaskedUser(context.Context, *RetrieveMaskedUserRequest) (*MaskedUser, error)
	// Edits a User's non-auth related information like family name and picture.
	EditUserInfo(context.Context, *EditUserInfoRequest) (*User, error)
	// Edits a User's metadata
	EditUserMetadata(context.Context, *EditUserMetadataRequest) (*User, error)
	// Retrieves the currently signed in user.
	// This is useful for client-side applications to get the signed in user's information.
	RetrieveMyUser(context.Context, *RetrieveMyUserRequest) (*User, error)
	// Edits the info of the currently signed in user.
	// This is useful for client-side applications to edit the signed in user's information.
	// Allows the user to edit their given_name, family_name, picture, contact_number, position, education, linkedin_uri and metadata.
	EditMyInfo(context.Context, *EditMyInfoRequest) (*User, error)
	// Edits the metadata of the currently signed in user.
	// This is useful for client-side applications to edit the signed in user's metadata.
	EditMyMetadata(context.Context, *EditMyMetadataRequest) (*User, error)
	// Removes the currently signed in user.
	// This is useful if a user wants to delete their account.
	RemoveMyUser(context.Context, *RemoveMyUserRequest) (*protobuf.Empty, error)
	// Syncs all google User's to the google group configured in the IamConfig.
	// Will not delete service accounts.
	SyncToGoogleGroup(context.Context, *SyncToGoogleGroupRequest) (*SyncToGoogleGroupResponse, error)
	// Sets the user's profile picture
	SetUserPicture(context.Context, *SetUserPictureRequest) (*SetUserPictureResponse, error)
	mustEmbedUnimplementedUsersServiceServer()
}

// UnimplementedUsersServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUsersServiceServer struct{}

func (UnimplementedUsersServiceServer) ValidateMessage(context.Context, *v1.ValidateMessageRequest) (*v1.ValidateMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateMessage not implemented")
}
func (UnimplementedUsersServiceServer) RetrieveRules(context.Context, *v1.RetrieveRulesRequest) (*v1.RetrieveRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrieveRules not implemented")
}
func (UnimplementedUsersServiceServer) GetIamPolicy(context.Context, *v11.GetIamPolicyRequest) (*v11.Policy, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIamPolicy not implemented")
}
func (UnimplementedUsersServiceServer) SetIamPolicy(context.Context, *v11.SetIamPolicyRequest) (*v11.Policy, error) {
	return nil, status.Error(codes.Unimplemented, "method SetIamPolicy not implemented")
}
func (UnimplementedUsersServiceServer) TestIamPermissions(context.Context, *v11.TestIamPermissionsRequest) (*v11.TestIamPermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestIamPermissions not implemented")
}
func (UnimplementedUsersServiceServer) AddIamBindings(context.Context, *AddIamBindingsRequest) (*v11.Policy, error) {
	return nil, status.Error(codes.Unimplemented, "method AddIamBindings not implemented")
}
func (UnimplementedUsersServiceServer) RemoveIamBindings(context.Context, *RemoveIamBindingsRequest) (*v11.Policy, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveIamBindings not implemented")
}
func (UnimplementedUsersServiceServer) GetUser(context.Context, *GetUserRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUsersServiceServer) CreateUser(context.Context, *CreateUserRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedUsersServiceServer) UpdateUser(context.Context, *UpdateUserRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedUsersServiceServer) DeleteUser(context.Context, *DeleteUserRequest) (*protobuf.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedUsersServiceServer) ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedUsersServiceServer) RetrieveUserByEmail(context.Context, *RetrieveUserByEmailRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrieveUserByEmail not implemented")
}
func (UnimplementedUsersServiceServer) LookupUser(context.Context, *LookupUserRequest) (*LookupUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupUser not implemented")
}
func (UnimplementedUsersServiceServer) BatchRetrieveMaskedUsers(context.Context, *BatchRetrieveMaskedUsersRequest) (*BatchRetrieveMaskedUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchRetrieveMaskedUsers not implemented")
}
func (UnimplementedUsersServiceServer) RetrieveMaskedUsers(context.Context, *RetrieveMaskedUsersRequest) (*RetrieveMaskedUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrieveMaskedUsers not implemented")
}
func (UnimplementedUsersServiceServer) RetrieveMaskedUser(context.Context, *RetrieveMaskedUserRequest) (*MaskedUser, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrieveMaskedUser not implemented")
}
func (UnimplementedUsersServiceServer) EditUserInfo(context.Context, *EditUserInfoRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method EditUserInfo not implemented")
}
func (UnimplementedUsersServiceServer) EditUserMetadata(context.Context, *EditUserMetadataRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method EditUserMetadata not implemented")
}
func (UnimplementedUsersServiceServer) RetrieveMyUser(context.Context, *RetrieveMyUserRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrieveMyUser not implemented")
}
func (UnimplementedUsersServiceServer) EditMyInfo(context.Context, *EditMyInfoRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method EditMyInfo not implemented")
}
func (UnimplementedUsersServiceServer) EditMyMetadata(context.Context, *EditMyMetadataRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method EditMyMetadata not implemented")
}
func (UnimplementedUsersServiceServer) RemoveMyUser(context.Context, *RemoveMyUserRequest) (*protobuf.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMyUser not implemented")
}
func (UnimplementedUsersServiceServer) SyncToGoogleGroup(context.Context, *SyncToGoogleGroupRequest) (*SyncToGoogleGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncToGoogleGroup not implemented")
}
func (UnimplementedUsersServiceServer) SetUserPicture(context.Context, *SetUserPictureRequest) (*SetUserPictureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetUserPicture not implemented")
}
func (UnimplementedUsersServiceServer) mustEmbedUnimplementedUsersServiceServer() {}
func (UnimplementedUsersServiceServer) testEmbeddedByValue()                      {}

// UnsafeUsersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsersServiceServer will
// result in compilation errors.
type UnsafeUsersServiceServer interface {
	mustEmbedUnimplementedUsersServiceServer()
}

func RegisterUsersServiceServer(s grpc.ServiceRegistrar, srv UsersServiceServer) {
	// If the following call panics, it indicates UnimplementedUsersServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UsersService_ServiceDesc, srv)
}

func _UsersService_ValidateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ValidateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).ValidateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_ValidateMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).ValidateMessage(ctx, req.(*v1.ValidateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_RetrieveRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.RetrieveRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).RetrieveRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_RetrieveRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).RetrieveRules(ctx, req.(*v1.RetrieveRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_GetIamPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v11.GetIamPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetIamPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_GetIamPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetIamPolicy(ctx, req.(*v11.GetIamPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_SetIamPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v11.SetIamPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).SetIamPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_SetIamPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).SetIamPolicy(ctx, req.(*v11.SetIamPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_TestIamPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v11.TestIamPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).TestIamPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_TestIamPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).TestIamPermissions(ctx, req.(*v11.TestIamPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_AddIamBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddIamBindingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).AddIamBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_AddIamBindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).AddIamBindings(ctx, req.(*AddIamBindingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_RemoveIamBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveIamBindingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).RemoveIamBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_RemoveIamBindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).RemoveIamBindings(ctx, req.(*RemoveIamBindingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_RetrieveUserByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveUserByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).RetrieveUserByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_RetrieveUserByEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).RetrieveUserByEmail(ctx, req.(*RetrieveUserByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_LookupUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).LookupUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_LookupUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).LookupUser(ctx, req.(*LookupUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_BatchRetrieveMaskedUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchRetrieveMaskedUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).BatchRetrieveMaskedUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_BatchRetrieveMaskedUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).BatchRetrieveMaskedUsers(ctx, req.(*BatchRetrieveMaskedUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_RetrieveMaskedUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveMaskedUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).RetrieveMaskedUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_RetrieveMaskedUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).RetrieveMaskedUsers(ctx, req.(*RetrieveMaskedUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_RetrieveMaskedUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveMaskedUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).RetrieveMaskedUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_RetrieveMaskedUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).RetrieveMaskedUser(ctx, req.(*RetrieveMaskedUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_EditUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).EditUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_EditUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).EditUserInfo(ctx, req.(*EditUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_EditUserMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditUserMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).EditUserMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_EditUserMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).EditUserMetadata(ctx, req.(*EditUserMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_RetrieveMyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveMyUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).RetrieveMyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_RetrieveMyUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).RetrieveMyUser(ctx, req.(*RetrieveMyUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_EditMyInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditMyInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).EditMyInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_EditMyInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).EditMyInfo(ctx, req.(*EditMyInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_EditMyMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditMyMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).EditMyMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_EditMyMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).EditMyMetadata(ctx, req.(*EditMyMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_RemoveMyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMyUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).RemoveMyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_RemoveMyUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).RemoveMyUser(ctx, req.(*RemoveMyUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_SyncToGoogleGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncToGoogleGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).SyncToGoogleGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_SyncToGoogleGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).SyncToGoogleGroup(ctx, req.(*SyncToGoogleGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_SetUserPicture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserPictureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).SetUserPicture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_SetUserPicture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).SetUserPicture(ctx, req.(*SetUserPictureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UsersService_ServiceDesc is the grpc.ServiceDesc for UsersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UsersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alis.open.iam.v1.UsersService",
	HandlerType: (*UsersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateMessage",
			Handler:    _UsersService_ValidateMessage_Handler,
		},
		{
			MethodName: "RetrieveRules",
			Handler:    _UsersService_RetrieveRules_Handler,
		},
		{
			MethodName: "GetIamPolicy",
			Handler:    _UsersService_GetIamPolicy_Handler,
		},
		{
			MethodName: "SetIamPolicy",
			Handler:    _UsersService_SetIamPolicy_Handler,
		},
		{
			MethodName: "TestIamPermissions",
			Handler:    _UsersService_TestIamPermissions_Handler,
		},
		{
			MethodName: "AddIamBindings",
			Handler:    _UsersService_AddIamBindings_Handler,
		},
		{
			MethodName: "RemoveIamBindings",
			Handler:    _UsersService_RemoveIamBindings_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UsersService_GetUser_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _UsersService_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UsersService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UsersService_DeleteUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _UsersService_ListUsers_Handler,
		},
		{
			MethodName: "RetrieveUserByEmail",
			Handler:    _UsersService_RetrieveUserByEmail_Handler,
		},
		{
			MethodName: "LookupUser",
			Handler:    _UsersService_LookupUser_Handler,
		},
		{
			MethodName: "BatchRetrieveMaskedUsers",
			Handler:    _UsersService_BatchRetrieveMaskedUsers_Handler,
		},
		{
			MethodName: "RetrieveMaskedUsers",
			Handler:    _UsersService_RetrieveMaskedUsers_Handler,
		},
		{
			MethodName: "RetrieveMaskedUser",
			Handler:    _UsersService_RetrieveMaskedUser_Handler,
		},
		{
			MethodName: "EditUserInfo",
			Handler:    _UsersService_EditUserInfo_Handler,
		},
		{
			MethodName: "EditUserMetadata",
			Handler:    _UsersService_EditUserMetadata_Handler,
		},
		{
			MethodName: "RetrieveMyUser",
			Handler:    _UsersService_RetrieveMyUser_Handler,
		},
		{
			MethodName: "EditMyInfo",
			Handler:    _UsersService_EditMyInfo_Handler,
		},
		{
			MethodName: "EditMyMetadata",
			Handler:    _UsersService_EditMyMetadata_Handler,
		},
		{
			MethodName: "RemoveMyUser",
			Handler:    _UsersService_RemoveMyUser_Handler,
		},
		{
			MethodName: "SyncToGoogleGroup",
			Handler:    _UsersService_SyncToGoogleGroup_Handler,
		},
		{
			MethodName: "SetUserPicture",
			Handler:    _UsersService_SetUserPicture_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alis/open/iam/v1/user.proto",
}
