// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: google/iam/v1/iam_policy.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-03-25 13:57:21 UTC

package v1

const (
	// IAMPolicy_SetIamPolicy_FullMethodDescription returns the description of the google.iam.v1.IAMPolicy.SetIamPolicy method.
	IAMPolicy_SetIamPolicy_FullMethodDescription = "Sets the access control policy on the specified resource. Replaces any\n existing policy. Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED` errors."
	// IAMPolicy_GetIamPolicy_FullMethodDescription returns the description of the google.iam.v1.IAMPolicy.GetIamPolicy method.
	IAMPolicy_GetIamPolicy_FullMethodDescription = "Gets the access control policy for a resource.\n Returns an empty policy if the resource exists and does not have a policy\n set."
	// IAMPolicy_TestIamPermissions_FullMethodDescription returns the description of the google.iam.v1.IAMPolicy.TestIamPermissions method.
	IAMPolicy_TestIamPermissions_FullMethodDescription = "Returns permissions that a caller has on the specified resource.\n If the resource does not exist, this will return an empty set of\n permissions, not a `NOT_FOUND` error. Note: This operation is designed to be used for building permission-aware\n UIs and command-line tools, not for authorization checking. This operation\n may \"fail open\" without warning."
)
