// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.4
// source: alis/open/support/v1/attachments.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message for the `UploadImage` method.
type UploadImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The image data as bytes.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// The image mime type.
	//
	// The current types supported are:
	// - image/jpeg,
	// - image/jpg
	// - image/x-png,
	// - image/png,
	// - image/gif
	MimeType      string `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageRequest) Reset() {
	*x = UploadImageRequest{}
	mi := &file_alis_open_support_v1_attachments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageRequest) ProtoMessage() {}

func (x *UploadImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_support_v1_attachments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageRequest.ProtoReflect.Descriptor instead.
func (*UploadImageRequest) Descriptor() ([]byte, []int) {
	return file_alis_open_support_v1_attachments_proto_rawDescGZIP(), []int{0}
}

func (x *UploadImageRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadImageRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

// The response message for the `UploadImage` method.
type UploadImageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The uri link to the original image.
	PublicUri     string `protobuf:"bytes,1,opt,name=public_uri,json=publicUri,proto3" json:"public_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageResponse) Reset() {
	*x = UploadImageResponse{}
	mi := &file_alis_open_support_v1_attachments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageResponse) ProtoMessage() {}

func (x *UploadImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_support_v1_attachments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageResponse.ProtoReflect.Descriptor instead.
func (*UploadImageResponse) Descriptor() ([]byte, []int) {
	return file_alis_open_support_v1_attachments_proto_rawDescGZIP(), []int{1}
}

func (x *UploadImageResponse) GetPublicUri() string {
	if x != nil {
		return x.PublicUri
	}
	return ""
}

var File_alis_open_support_v1_attachments_proto protoreflect.FileDescriptor

const file_alis_open_support_v1_attachments_proto_rawDesc = "" +
	"\n" +
	"&alis/open/support/v1/attachments.proto\x12\x14alis.open.support.v1\"E\n" +
	"\x12UploadImageRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\"4\n" +
	"\x13UploadImageResponse\x12\x1d\n" +
	"\n" +
	"public_uri\x18\x01 \x01(\tR\tpublicUri2\x80\x01\n" +
	"\x18PublicAttachmentsService\x12d\n" +
	"\vUploadImage\x12(.alis.open.support.v1.UploadImageRequest\x1a).alis.open.support.v1.UploadImageResponse\"\x00B+Z)go.alis.build/common/alis/open/support/v1b\x06proto3"

var (
	file_alis_open_support_v1_attachments_proto_rawDescOnce sync.Once
	file_alis_open_support_v1_attachments_proto_rawDescData []byte
)

func file_alis_open_support_v1_attachments_proto_rawDescGZIP() []byte {
	file_alis_open_support_v1_attachments_proto_rawDescOnce.Do(func() {
		file_alis_open_support_v1_attachments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alis_open_support_v1_attachments_proto_rawDesc), len(file_alis_open_support_v1_attachments_proto_rawDesc)))
	})
	return file_alis_open_support_v1_attachments_proto_rawDescData
}

var file_alis_open_support_v1_attachments_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_alis_open_support_v1_attachments_proto_goTypes = []any{
	(*UploadImageRequest)(nil),  // 0: alis.open.support.v1.UploadImageRequest
	(*UploadImageResponse)(nil), // 1: alis.open.support.v1.UploadImageResponse
}
var file_alis_open_support_v1_attachments_proto_depIdxs = []int32{
	0, // 0: alis.open.support.v1.PublicAttachmentsService.UploadImage:input_type -> alis.open.support.v1.UploadImageRequest
	1, // 1: alis.open.support.v1.PublicAttachmentsService.UploadImage:output_type -> alis.open.support.v1.UploadImageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_alis_open_support_v1_attachments_proto_init() }
func file_alis_open_support_v1_attachments_proto_init() {
	if File_alis_open_support_v1_attachments_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alis_open_support_v1_attachments_proto_rawDesc), len(file_alis_open_support_v1_attachments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alis_open_support_v1_attachments_proto_goTypes,
		DependencyIndexes: file_alis_open_support_v1_attachments_proto_depIdxs,
		MessageInfos:      file_alis_open_support_v1_attachments_proto_msgTypes,
	}.Build()
	File_alis_open_support_v1_attachments_proto = out.File
	file_alis_open_support_v1_attachments_proto_goTypes = nil
	file_alis_open_support_v1_attachments_proto_depIdxs = nil
}
