// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.4
// source: alis/open/support/v1/guide.proto

package v1

import (
	v1 "go.alis.build/common/alis/open/validation/v1"
	protobuf "go.alis.build/common/google/protobuf"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The potential types of content blocks
type Guide_ContentBlock_Type int32

const (
	// TYPE_UNSPECIFIED
	Guide_ContentBlock_TYPE_UNSPECIFIED Guide_ContentBlock_Type = 0
	// A title
	Guide_ContentBlock_TITLE Guide_ContentBlock_Type = 1
	// A subtitle
	Guide_ContentBlock_SUBTITLE Guide_ContentBlock_Type = 2
	// A heading
	Guide_ContentBlock_HEADING Guide_ContentBlock_Type = 3
	// Body text
	Guide_ContentBlock_TEXT_BODY Guide_ContentBlock_Type = 4
	// A standalone image
	Guide_ContentBlock_IMAGE Guide_ContentBlock_Type = 5
	// A standalone video
	Guide_ContentBlock_VIDEO Guide_ContentBlock_Type = 6
	// A divider which can be used to seperate elements of the page.
	Guide_ContentBlock_DIVIDER Guide_ContentBlock_Type = 7
	// Provides a user-specified preview of a URL
	Guide_ContentBlock_LINK_PREVIEW Guide_ContentBlock_Type = 8
	// Footnote that can be placed at the end of a section
	Guide_ContentBlock_FOOTNOTE Guide_ContentBlock_Type = 9
	// A diagram, specified using valid syntax
	Guide_ContentBlock_DIAGRAM Guide_ContentBlock_Type = 10
	// A syntax-highlighted code block for the set of supported languages
	Guide_ContentBlock_CODE_BLOCK Guide_ContentBlock_Type = 11
)

// Enum value maps for Guide_ContentBlock_Type.
var (
	Guide_ContentBlock_Type_name = map[int32]string{
		0:  "TYPE_UNSPECIFIED",
		1:  "TITLE",
		2:  "SUBTITLE",
		3:  "HEADING",
		4:  "TEXT_BODY",
		5:  "IMAGE",
		6:  "VIDEO",
		7:  "DIVIDER",
		8:  "LINK_PREVIEW",
		9:  "FOOTNOTE",
		10: "DIAGRAM",
		11: "CODE_BLOCK",
	}
	Guide_ContentBlock_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TITLE":            1,
		"SUBTITLE":         2,
		"HEADING":          3,
		"TEXT_BODY":        4,
		"IMAGE":            5,
		"VIDEO":            6,
		"DIVIDER":          7,
		"LINK_PREVIEW":     8,
		"FOOTNOTE":         9,
		"DIAGRAM":          10,
		"CODE_BLOCK":       11,
	}
)

func (x Guide_ContentBlock_Type) Enum() *Guide_ContentBlock_Type {
	p := new(Guide_ContentBlock_Type)
	*p = x
	return p
}

func (x Guide_ContentBlock_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Guide_ContentBlock_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_alis_open_support_v1_guide_proto_enumTypes[0].Descriptor()
}

func (Guide_ContentBlock_Type) Type() protoreflect.EnumType {
	return &file_alis_open_support_v1_guide_proto_enumTypes[0]
}

func (x Guide_ContentBlock_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Guide_ContentBlock_Type.Descriptor instead.
func (Guide_ContentBlock_Type) EnumDescriptor() ([]byte, []int) {
	return file_alis_open_support_v1_guide_proto_rawDescGZIP(), []int{0, 0, 0}
}

// The set of available languages
type Guide_ContentBlock_CodeBlock_Language int32

const (
	// Unspecified
	Guide_ContentBlock_CodeBlock_LANGUAGE_UNSPECIFIED Guide_ContentBlock_CodeBlock_Language = 0
	// Go
	Guide_ContentBlock_CodeBlock_GO Guide_ContentBlock_CodeBlock_Language = 1
	// Protocol buffer 3
	Guide_ContentBlock_CodeBlock_PROTO Guide_ContentBlock_CodeBlock_Language = 2
	// Python
	Guide_ContentBlock_CodeBlock_PYTHON Guide_ContentBlock_CodeBlock_Language = 3
	// Vue
	Guide_ContentBlock_CodeBlock_VUE Guide_ContentBlock_CodeBlock_Language = 4
	// Typescript
	Guide_ContentBlock_CodeBlock_TYPESCRIPT Guide_ContentBlock_CodeBlock_Language = 5
	// LATEX
	Guide_ContentBlock_CodeBlock_LATEX Guide_ContentBlock_CodeBlock_Language = 6
	// Hashicorp HCL
	Guide_ContentBlock_CodeBlock_HCL Guide_ContentBlock_CodeBlock_Language = 7
	// JSON
	Guide_ContentBlock_CodeBlock_JSON Guide_ContentBlock_CodeBlock_Language = 8
	// YAML
	Guide_ContentBlock_CodeBlock_YAML Guide_ContentBlock_CodeBlock_Language = 9
	// Plain text
	Guide_ContentBlock_CodeBlock_TEXT Guide_ContentBlock_CodeBlock_Language = 10
)

// Enum value maps for Guide_ContentBlock_CodeBlock_Language.
var (
	Guide_ContentBlock_CodeBlock_Language_name = map[int32]string{
		0:  "LANGUAGE_UNSPECIFIED",
		1:  "GO",
		2:  "PROTO",
		3:  "PYTHON",
		4:  "VUE",
		5:  "TYPESCRIPT",
		6:  "LATEX",
		7:  "HCL",
		8:  "JSON",
		9:  "YAML",
		10: "TEXT",
	}
	Guide_ContentBlock_CodeBlock_Language_value = map[string]int32{
		"LANGUAGE_UNSPECIFIED": 0,
		"GO":                   1,
		"PROTO":                2,
		"PYTHON":               3,
		"VUE":                  4,
		"TYPESCRIPT":           5,
		"LATEX":                6,
		"HCL":                  7,
		"JSON":                 8,
		"YAML":                 9,
		"TEXT":                 10,
	}
)

func (x Guide_ContentBlock_CodeBlock_Language) Enum() *Guide_ContentBlock_CodeBlock_Language {
	p := new(Guide_ContentBlock_CodeBlock_Language)
	*p = x
	return p
}

func (x Guide_ContentBlock_CodeBlock_Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Guide_ContentBlock_CodeBlock_Language) Descriptor() protoreflect.EnumDescriptor {
	return file_alis_open_support_v1_guide_proto_enumTypes[1].Descriptor()
}

func (Guide_ContentBlock_CodeBlock_Language) Type() protoreflect.EnumType {
	return &file_alis_open_support_v1_guide_proto_enumTypes[1]
}

func (x Guide_ContentBlock_CodeBlock_Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Guide_ContentBlock_CodeBlock_Language.Descriptor instead.
func (Guide_ContentBlock_CodeBlock_Language) EnumDescriptor() ([]byte, []int) {
	return file_alis_open_support_v1_guide_proto_rawDescGZIP(), []int{0, 0, 10, 0}
}

// A Guide represents preemptive support that is provided
// by the Product team to aid users in their usage of the Product.
type Guide struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the guide
	// Format: guides/*
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Title of the Guide
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// The subtitle of the Guide
	Subtitle string `protobuf:"bytes,3,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	// The Guide contents
	Contents []*Guide_ContentBlock `protobuf:"bytes,5,rep,name=contents,proto3" json:"contents,omitempty"`
	// Time the page was created
	CreateTime *protobuf.Timestamp `protobuf:"bytes,98,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Time the page was updated
	UpdateTime    *protobuf.Timestamp `protobuf:"bytes,99,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Guide) Reset() {
	*x = Guide{}
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guide) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guide) ProtoMessage() {}

func (x *Guide) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guide.ProtoReflect.Descriptor instead.
func (*Guide) Descriptor() ([]byte, []int) {
	return file_alis_open_support_v1_guide_proto_rawDescGZIP(), []int{0}
}

func (x *Guide) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Guide) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Guide) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *Guide) GetContents() []*Guide_ContentBlock {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *Guide) GetCreateTime() *protobuf.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Guide) GetUpdateTime() *protobuf.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// The request message for the GetGuide method.
type GetGuideRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique name of the Guide.
	// Format: guides/*
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The fields to return in snake_case.
	// All fields are returned if not set.
	ReadMask      *protobuf.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGuideRequest) Reset() {
	*x = GetGuideRequest{}
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGuideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuideRequest) ProtoMessage() {}

func (x *GetGuideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuideRequest.ProtoReflect.Descriptor instead.
func (*GetGuideRequest) Descriptor() ([]byte, []int) {
	return file_alis_open_support_v1_guide_proto_rawDescGZIP(), []int{1}
}

func (x *GetGuideRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetGuideRequest) GetReadMask() *protobuf.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

// The request message for the ListGuides method.
type ListGuidesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum number of Guides to return.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A page token, received from a previous ListGuides call.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// The fields to return in snake_case.
	// All fields are returned if not set.
	ReadMask *protobuf.FieldMask `protobuf:"bytes,4,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	// The filter to apply
	Filter string `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	// The order to sort the results by
	// Default is descending
	//
	// Format: "field_name {asc|desc}"
	//
	// Only update_time is supported at the moment.
	OrderBy       string `protobuf:"bytes,6,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGuidesRequest) Reset() {
	*x = ListGuidesRequest{}
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGuidesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGuidesRequest) ProtoMessage() {}

func (x *ListGuidesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGuidesRequest.ProtoReflect.Descriptor instead.
func (*ListGuidesRequest) Descriptor() ([]byte, []int) {
	return file_alis_open_support_v1_guide_proto_rawDescGZIP(), []int{2}
}

func (x *ListGuidesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListGuidesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListGuidesRequest) GetReadMask() *protobuf.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

func (x *ListGuidesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListGuidesRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

// The response message for the ListGuides method.
type ListGuidesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Guides.
	Guides []*Guide `protobuf:"bytes,1,rep,name=guides,proto3" json:"guides,omitempty"`
	// A token to retrieve the next page of results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGuidesResponse) Reset() {
	*x = ListGuidesResponse{}
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGuidesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGuidesResponse) ProtoMessage() {}

func (x *ListGuidesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGuidesResponse.ProtoReflect.Descriptor instead.
func (*ListGuidesResponse) Descriptor() ([]byte, []int) {
	return file_alis_open_support_v1_guide_proto_rawDescGZIP(), []int{3}
}

func (x *ListGuidesResponse) GetGuides() []*Guide {
	if x != nil {
		return x.Guides
	}
	return nil
}

func (x *ListGuidesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// The request message for the SyncGuide method.
type SyncGuideRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the guide to sync
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The new values of the guide.
	// If empty, the guide is removed.
	Guide         *Guide `protobuf:"bytes,2,opt,name=guide,proto3" json:"guide,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncGuideRequest) Reset() {
	*x = SyncGuideRequest{}
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncGuideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncGuideRequest) ProtoMessage() {}

func (x *SyncGuideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncGuideRequest.ProtoReflect.Descriptor instead.
func (*SyncGuideRequest) Descriptor() ([]byte, []int) {
	return file_alis_open_support_v1_guide_proto_rawDescGZIP(), []int{4}
}

func (x *SyncGuideRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SyncGuideRequest) GetGuide() *Guide {
	if x != nil {
		return x.Guide
	}
	return nil
}

// A ContentBlock defines various content types
// that may be used as part of the Guides.
type Guide_ContentBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of the content block
	Type Guide_ContentBlock_Type `protobuf:"varint,1,opt,name=type,proto3,enum=alis.open.support.v1.Guide_ContentBlock_Type" json:"type,omitempty"`
	// The block containing the content
	//
	// Types that are valid to be assigned to Block:
	//
	//	*Guide_ContentBlock_Title_
	//	*Guide_ContentBlock_Subtitle_
	//	*Guide_ContentBlock_Heading_
	//	*Guide_ContentBlock_TextBody_
	//	*Guide_ContentBlock_Image_
	//	*Guide_ContentBlock_Video_
	//	*Guide_ContentBlock_Divider_
	//	*Guide_ContentBlock_LinkPreview_
	//	*Guide_ContentBlock_Footnote_
	//	*Guide_ContentBlock_Diagram_
	//	*Guide_ContentBlock_CodeBlock_
	Block         isGuide_ContentBlock_Block `protobuf_oneof:"block"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Guide_ContentBlock) Reset() {
	*x = Guide_ContentBlock{}
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guide_ContentBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guide_ContentBlock) ProtoMessage() {}

func (x *Guide_ContentBlock) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guide_ContentBlock.ProtoReflect.Descriptor instead.
func (*Guide_ContentBlock) Descriptor() ([]byte, []int) {
	return file_alis_open_support_v1_guide_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Guide_ContentBlock) GetType() Guide_ContentBlock_Type {
	if x != nil {
		return x.Type
	}
	return Guide_ContentBlock_TYPE_UNSPECIFIED
}

func (x *Guide_ContentBlock) GetBlock() isGuide_ContentBlock_Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *Guide_ContentBlock) GetTitle() *Guide_ContentBlock_Title {
	if x != nil {
		if x, ok := x.Block.(*Guide_ContentBlock_Title_); ok {
			return x.Title
		}
	}
	return nil
}

func (x *Guide_ContentBlock) GetSubtitle() *Guide_ContentBlock_Subtitle {
	if x != nil {
		if x, ok := x.Block.(*Guide_ContentBlock_Subtitle_); ok {
			return x.Subtitle
		}
	}
	return nil
}

func (x *Guide_ContentBlock) GetHeading() *Guide_ContentBlock_Heading {
	if x != nil {
		if x, ok := x.Block.(*Guide_ContentBlock_Heading_); ok {
			return x.Heading
		}
	}
	return nil
}

func (x *Guide_ContentBlock) GetTextBody() *Guide_ContentBlock_TextBody {
	if x != nil {
		if x, ok := x.Block.(*Guide_ContentBlock_TextBody_); ok {
			return x.TextBody
		}
	}
	return nil
}

func (x *Guide_ContentBlock) GetImage() *Guide_ContentBlock_Image {
	if x != nil {
		if x, ok := x.Block.(*Guide_ContentBlock_Image_); ok {
			return x.Image
		}
	}
	return nil
}

func (x *Guide_ContentBlock) GetVideo() *Guide_ContentBlock_Video {
	if x != nil {
		if x, ok := x.Block.(*Guide_ContentBlock_Video_); ok {
			return x.Video
		}
	}
	return nil
}

func (x *Guide_ContentBlock) GetDivider() *Guide_ContentBlock_Divider {
	if x != nil {
		if x, ok := x.Block.(*Guide_ContentBlock_Divider_); ok {
			return x.Divider
		}
	}
	return nil
}

func (x *Guide_ContentBlock) GetLinkPreview() *Guide_ContentBlock_LinkPreview {
	if x != nil {
		if x, ok := x.Block.(*Guide_ContentBlock_LinkPreview_); ok {
			return x.LinkPreview
		}
	}
	return nil
}

func (x *Guide_ContentBlock) GetFootnote() *Guide_ContentBlock_Footnote {
	if x != nil {
		if x, ok := x.Block.(*Guide_ContentBlock_Footnote_); ok {
			return x.Footnote
		}
	}
	return nil
}

func (x *Guide_ContentBlock) GetDiagram() *Guide_ContentBlock_Diagram {
	if x != nil {
		if x, ok := x.Block.(*Guide_ContentBlock_Diagram_); ok {
			return x.Diagram
		}
	}
	return nil
}

func (x *Guide_ContentBlock) GetCodeBlock() *Guide_ContentBlock_CodeBlock {
	if x != nil {
		if x, ok := x.Block.(*Guide_ContentBlock_CodeBlock_); ok {
			return x.CodeBlock
		}
	}
	return nil
}

type isGuide_ContentBlock_Block interface {
	isGuide_ContentBlock_Block()
}

type Guide_ContentBlock_Title_ struct {
	// A title
	Title *Guide_ContentBlock_Title `protobuf:"bytes,2,opt,name=title,proto3,oneof"`
}

type Guide_ContentBlock_Subtitle_ struct {
	// A Subtitle
	Subtitle *Guide_ContentBlock_Subtitle `protobuf:"bytes,3,opt,name=subtitle,proto3,oneof"`
}

type Guide_ContentBlock_Heading_ struct {
	// A heading
	Heading *Guide_ContentBlock_Heading `protobuf:"bytes,4,opt,name=heading,proto3,oneof"`
}

type Guide_ContentBlock_TextBody_ struct {
	// Body text
	TextBody *Guide_ContentBlock_TextBody `protobuf:"bytes,5,opt,name=text_body,json=textBody,proto3,oneof"`
}

type Guide_ContentBlock_Image_ struct {
	// A standalone image
	Image *Guide_ContentBlock_Image `protobuf:"bytes,6,opt,name=image,proto3,oneof"`
}

type Guide_ContentBlock_Video_ struct {
	// A standalone video
	Video *Guide_ContentBlock_Video `protobuf:"bytes,7,opt,name=video,proto3,oneof"`
}

type Guide_ContentBlock_Divider_ struct {
	// A divider which can be used to seperate elements of the page.
	Divider *Guide_ContentBlock_Divider `protobuf:"bytes,8,opt,name=divider,proto3,oneof"`
}

type Guide_ContentBlock_LinkPreview_ struct {
	// Provides a user-specified preview of a URL
	LinkPreview *Guide_ContentBlock_LinkPreview `protobuf:"bytes,9,opt,name=link_preview,json=linkPreview,proto3,oneof"`
}

type Guide_ContentBlock_Footnote_ struct {
	// Footnote that can be placed at the end of a section
	Footnote *Guide_ContentBlock_Footnote `protobuf:"bytes,10,opt,name=footnote,proto3,oneof"`
}

type Guide_ContentBlock_Diagram_ struct {
	// A diagram, specified using valid syntax
	Diagram *Guide_ContentBlock_Diagram `protobuf:"bytes,11,opt,name=diagram,proto3,oneof"`
}

type Guide_ContentBlock_CodeBlock_ struct {
	// A syntax-highlighted code block for the set of supported languages
	CodeBlock *Guide_ContentBlock_CodeBlock `protobuf:"bytes,12,opt,name=code_block,json=codeBlock,proto3,oneof"`
}

func (*Guide_ContentBlock_Title_) isGuide_ContentBlock_Block() {}

func (*Guide_ContentBlock_Subtitle_) isGuide_ContentBlock_Block() {}

func (*Guide_ContentBlock_Heading_) isGuide_ContentBlock_Block() {}

func (*Guide_ContentBlock_TextBody_) isGuide_ContentBlock_Block() {}

func (*Guide_ContentBlock_Image_) isGuide_ContentBlock_Block() {}

func (*Guide_ContentBlock_Video_) isGuide_ContentBlock_Block() {}

func (*Guide_ContentBlock_Divider_) isGuide_ContentBlock_Block() {}

func (*Guide_ContentBlock_LinkPreview_) isGuide_ContentBlock_Block() {}

func (*Guide_ContentBlock_Footnote_) isGuide_ContentBlock_Block() {}

func (*Guide_ContentBlock_Diagram_) isGuide_ContentBlock_Block() {}

func (*Guide_ContentBlock_CodeBlock_) isGuide_ContentBlock_Block() {}

// A title
type Guide_ContentBlock_Title struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The title text content
	Text          string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Guide_ContentBlock_Title) Reset() {
	*x = Guide_ContentBlock_Title{}
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guide_ContentBlock_Title) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guide_ContentBlock_Title) ProtoMessage() {}

func (x *Guide_ContentBlock_Title) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guide_ContentBlock_Title.ProtoReflect.Descriptor instead.
func (*Guide_ContentBlock_Title) Descriptor() ([]byte, []int) {
	return file_alis_open_support_v1_guide_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Guide_ContentBlock_Title) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// A Subtitle
type Guide_ContentBlock_Subtitle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The subtitle text content
	Text          string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Guide_ContentBlock_Subtitle) Reset() {
	*x = Guide_ContentBlock_Subtitle{}
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guide_ContentBlock_Subtitle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guide_ContentBlock_Subtitle) ProtoMessage() {}

func (x *Guide_ContentBlock_Subtitle) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guide_ContentBlock_Subtitle.ProtoReflect.Descriptor instead.
func (*Guide_ContentBlock_Subtitle) Descriptor() ([]byte, []int) {
	return file_alis_open_support_v1_guide_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *Guide_ContentBlock_Subtitle) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// A Heading
type Guide_ContentBlock_Heading struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The heading text content
	Text          string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Guide_ContentBlock_Heading) Reset() {
	*x = Guide_ContentBlock_Heading{}
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guide_ContentBlock_Heading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guide_ContentBlock_Heading) ProtoMessage() {}

func (x *Guide_ContentBlock_Heading) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guide_ContentBlock_Heading.ProtoReflect.Descriptor instead.
func (*Guide_ContentBlock_Heading) Descriptor() ([]byte, []int) {
	return file_alis_open_support_v1_guide_proto_rawDescGZIP(), []int{0, 0, 2}
}

func (x *Guide_ContentBlock_Heading) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Body text
type Guide_ContentBlock_TextBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The text body content
	// Supports standard markdown format.
	Text          string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Guide_ContentBlock_TextBody) Reset() {
	*x = Guide_ContentBlock_TextBody{}
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guide_ContentBlock_TextBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guide_ContentBlock_TextBody) ProtoMessage() {}

func (x *Guide_ContentBlock_TextBody) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guide_ContentBlock_TextBody.ProtoReflect.Descriptor instead.
func (*Guide_ContentBlock_TextBody) Descriptor() ([]byte, []int) {
	return file_alis_open_support_v1_guide_proto_rawDescGZIP(), []int{0, 0, 3}
}

func (x *Guide_ContentBlock_TextBody) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// A standalone image
type Guide_ContentBlock_Image struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The image source url
	SourceUri string `protobuf:"bytes,1,opt,name=source_uri,json=sourceUri,proto3" json:"source_uri,omitempty"`
	// An optional caption to the image
	Caption       string `protobuf:"bytes,2,opt,name=caption,proto3" json:"caption,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Guide_ContentBlock_Image) Reset() {
	*x = Guide_ContentBlock_Image{}
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guide_ContentBlock_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guide_ContentBlock_Image) ProtoMessage() {}

func (x *Guide_ContentBlock_Image) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guide_ContentBlock_Image.ProtoReflect.Descriptor instead.
func (*Guide_ContentBlock_Image) Descriptor() ([]byte, []int) {
	return file_alis_open_support_v1_guide_proto_rawDescGZIP(), []int{0, 0, 4}
}

func (x *Guide_ContentBlock_Image) GetSourceUri() string {
	if x != nil {
		return x.SourceUri
	}
	return ""
}

func (x *Guide_ContentBlock_Image) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

// A standalone video
type Guide_ContentBlock_Video struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The video source url.
	//
	// Currently only support Youtube links
	SourceUri string `protobuf:"bytes,1,opt,name=source_uri,json=sourceUri,proto3" json:"source_uri,omitempty"`
	// An optional caption to the video
	Caption       string `protobuf:"bytes,2,opt,name=caption,proto3" json:"caption,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Guide_ContentBlock_Video) Reset() {
	*x = Guide_ContentBlock_Video{}
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guide_ContentBlock_Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guide_ContentBlock_Video) ProtoMessage() {}

func (x *Guide_ContentBlock_Video) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guide_ContentBlock_Video.ProtoReflect.Descriptor instead.
func (*Guide_ContentBlock_Video) Descriptor() ([]byte, []int) {
	return file_alis_open_support_v1_guide_proto_rawDescGZIP(), []int{0, 0, 5}
}

func (x *Guide_ContentBlock_Video) GetSourceUri() string {
	if x != nil {
		return x.SourceUri
	}
	return ""
}

func (x *Guide_ContentBlock_Video) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

// A divider which can be used to seperate elements of the page.
type Guide_ContentBlock_Divider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Guide_ContentBlock_Divider) Reset() {
	*x = Guide_ContentBlock_Divider{}
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guide_ContentBlock_Divider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guide_ContentBlock_Divider) ProtoMessage() {}

func (x *Guide_ContentBlock_Divider) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guide_ContentBlock_Divider.ProtoReflect.Descriptor instead.
func (*Guide_ContentBlock_Divider) Descriptor() ([]byte, []int) {
	return file_alis_open_support_v1_guide_proto_rawDescGZIP(), []int{0, 0, 6}
}

// Provides a user-specified preview of a URL
type Guide_ContentBlock_LinkPreview struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The URI that will be directed to on open
	Uri string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	// An avatar to use, if not specified, will default to the Alis dots
	AvatarUri string `protobuf:"bytes,2,opt,name=avatar_uri,json=avatarUri,proto3" json:"avatar_uri,omitempty"`
	// A title to use
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// A blurb of body text that can be used to give a description to the link.
	Body          string `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Guide_ContentBlock_LinkPreview) Reset() {
	*x = Guide_ContentBlock_LinkPreview{}
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guide_ContentBlock_LinkPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guide_ContentBlock_LinkPreview) ProtoMessage() {}

func (x *Guide_ContentBlock_LinkPreview) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guide_ContentBlock_LinkPreview.ProtoReflect.Descriptor instead.
func (*Guide_ContentBlock_LinkPreview) Descriptor() ([]byte, []int) {
	return file_alis_open_support_v1_guide_proto_rawDescGZIP(), []int{0, 0, 7}
}

func (x *Guide_ContentBlock_LinkPreview) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Guide_ContentBlock_LinkPreview) GetAvatarUri() string {
	if x != nil {
		return x.AvatarUri
	}
	return ""
}

func (x *Guide_ContentBlock_LinkPreview) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Guide_ContentBlock_LinkPreview) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// Footnote that can be placed at the end of a section
type Guide_ContentBlock_Footnote struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The footnote content
	// Supports standard markdown format.
	Text          string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Guide_ContentBlock_Footnote) Reset() {
	*x = Guide_ContentBlock_Footnote{}
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guide_ContentBlock_Footnote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guide_ContentBlock_Footnote) ProtoMessage() {}

func (x *Guide_ContentBlock_Footnote) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guide_ContentBlock_Footnote.ProtoReflect.Descriptor instead.
func (*Guide_ContentBlock_Footnote) Descriptor() ([]byte, []int) {
	return file_alis_open_support_v1_guide_proto_rawDescGZIP(), []int{0, 0, 8}
}

func (x *Guide_ContentBlock_Footnote) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// A diagram, specified using valid syntax
type Guide_ContentBlock_Diagram struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Valid Mermaid Syntax (https://mermaid.js.org/intro/syntax-reference.html)
	// that will be used to render the diagram.
	MermaidDiagramCode string `protobuf:"bytes,1,opt,name=mermaid_diagram_code,json=mermaidDiagramCode,proto3" json:"mermaid_diagram_code,omitempty"`
	// A string version of the rendered diagram as valid html or SVG.
	//
	// This is stored such that client-side usage does not need to
	// install Mermaid and render the code themselves.
	MermaidRenderedDiagram string `protobuf:"bytes,2,opt,name=mermaid_rendered_diagram,json=mermaidRenderedDiagram,proto3" json:"mermaid_rendered_diagram,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Guide_ContentBlock_Diagram) Reset() {
	*x = Guide_ContentBlock_Diagram{}
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guide_ContentBlock_Diagram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guide_ContentBlock_Diagram) ProtoMessage() {}

func (x *Guide_ContentBlock_Diagram) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guide_ContentBlock_Diagram.ProtoReflect.Descriptor instead.
func (*Guide_ContentBlock_Diagram) Descriptor() ([]byte, []int) {
	return file_alis_open_support_v1_guide_proto_rawDescGZIP(), []int{0, 0, 9}
}

func (x *Guide_ContentBlock_Diagram) GetMermaidDiagramCode() string {
	if x != nil {
		return x.MermaidDiagramCode
	}
	return ""
}

func (x *Guide_ContentBlock_Diagram) GetMermaidRenderedDiagram() string {
	if x != nil {
		return x.MermaidRenderedDiagram
	}
	return ""
}

// A syntax-highlighted code block for the set of supported languages
type Guide_ContentBlock_CodeBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The language of the code
	Language Guide_ContentBlock_CodeBlock_Language `protobuf:"varint,1,opt,name=language,proto3,enum=alis.open.support.v1.Guide_ContentBlock_CodeBlock_Language" json:"language,omitempty"`
	// The code to that will be displayed in the code block.
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// A string version of the syntax-highlighted code rendered as valid html.
	//
	// This is stored such that client-side usage does not need to
	// install a syntax highlighter and render the html themselves.
	SyntaxHighlightedCode string `protobuf:"bytes,3,opt,name=syntax_highlighted_code,json=syntaxHighlightedCode,proto3" json:"syntax_highlighted_code,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Guide_ContentBlock_CodeBlock) Reset() {
	*x = Guide_ContentBlock_CodeBlock{}
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guide_ContentBlock_CodeBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guide_ContentBlock_CodeBlock) ProtoMessage() {}

func (x *Guide_ContentBlock_CodeBlock) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_support_v1_guide_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guide_ContentBlock_CodeBlock.ProtoReflect.Descriptor instead.
func (*Guide_ContentBlock_CodeBlock) Descriptor() ([]byte, []int) {
	return file_alis_open_support_v1_guide_proto_rawDescGZIP(), []int{0, 0, 10}
}

func (x *Guide_ContentBlock_CodeBlock) GetLanguage() Guide_ContentBlock_CodeBlock_Language {
	if x != nil {
		return x.Language
	}
	return Guide_ContentBlock_CodeBlock_LANGUAGE_UNSPECIFIED
}

func (x *Guide_ContentBlock_CodeBlock) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Guide_ContentBlock_CodeBlock) GetSyntaxHighlightedCode() string {
	if x != nil {
		return x.SyntaxHighlightedCode
	}
	return ""
}

var File_alis_open_support_v1_guide_proto protoreflect.FileDescriptor

const file_alis_open_support_v1_guide_proto_rawDesc = "" +
	"\n" +
	" alis/open/support/v1/guide.proto\x12\x14alis.open.support.v1\x1a(alis/open/validation/v1/validation.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x11\n" +
	"\x05Guide\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bsubtitle\x18\x03 \x01(\tR\bsubtitle\x12D\n" +
	"\bcontents\x18\x05 \x03(\v2(.alis.open.support.v1.Guide.ContentBlockR\bcontents\x12;\n" +
	"\vcreate_time\x18b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18c \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x1a\xc4\x0f\n" +
	"\fContentBlock\x12A\n" +
	"\x04type\x18\x01 \x01(\x0e2-.alis.open.support.v1.Guide.ContentBlock.TypeR\x04type\x12F\n" +
	"\x05title\x18\x02 \x01(\v2..alis.open.support.v1.Guide.ContentBlock.TitleH\x00R\x05title\x12O\n" +
	"\bsubtitle\x18\x03 \x01(\v21.alis.open.support.v1.Guide.ContentBlock.SubtitleH\x00R\bsubtitle\x12L\n" +
	"\aheading\x18\x04 \x01(\v20.alis.open.support.v1.Guide.ContentBlock.HeadingH\x00R\aheading\x12P\n" +
	"\ttext_body\x18\x05 \x01(\v21.alis.open.support.v1.Guide.ContentBlock.TextBodyH\x00R\btextBody\x12F\n" +
	"\x05image\x18\x06 \x01(\v2..alis.open.support.v1.Guide.ContentBlock.ImageH\x00R\x05image\x12F\n" +
	"\x05video\x18\a \x01(\v2..alis.open.support.v1.Guide.ContentBlock.VideoH\x00R\x05video\x12L\n" +
	"\adivider\x18\b \x01(\v20.alis.open.support.v1.Guide.ContentBlock.DividerH\x00R\adivider\x12Y\n" +
	"\flink_preview\x18\t \x01(\v24.alis.open.support.v1.Guide.ContentBlock.LinkPreviewH\x00R\vlinkPreview\x12O\n" +
	"\bfootnote\x18\n" +
	" \x01(\v21.alis.open.support.v1.Guide.ContentBlock.FootnoteH\x00R\bfootnote\x12L\n" +
	"\adiagram\x18\v \x01(\v20.alis.open.support.v1.Guide.ContentBlock.DiagramH\x00R\adiagram\x12S\n" +
	"\n" +
	"code_block\x18\f \x01(\v22.alis.open.support.v1.Guide.ContentBlock.CodeBlockH\x00R\tcodeBlock\x1a\x1b\n" +
	"\x05Title\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x1a\x1e\n" +
	"\bSubtitle\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x1a\x1d\n" +
	"\aHeading\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x1a\x1e\n" +
	"\bTextBody\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x1a@\n" +
	"\x05Image\x12\x1d\n" +
	"\n" +
	"source_uri\x18\x01 \x01(\tR\tsourceUri\x12\x18\n" +
	"\acaption\x18\x02 \x01(\tR\acaption\x1a@\n" +
	"\x05Video\x12\x1d\n" +
	"\n" +
	"source_uri\x18\x01 \x01(\tR\tsourceUri\x12\x18\n" +
	"\acaption\x18\x02 \x01(\tR\acaption\x1a\t\n" +
	"\aDivider\x1ah\n" +
	"\vLinkPreview\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x1d\n" +
	"\n" +
	"avatar_uri\x18\x02 \x01(\tR\tavatarUri\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x1a\x1e\n" +
	"\bFootnote\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x1au\n" +
	"\aDiagram\x120\n" +
	"\x14mermaid_diagram_code\x18\x01 \x01(\tR\x12mermaidDiagramCode\x128\n" +
	"\x18mermaid_rendered_diagram\x18\x02 \x01(\tR\x16mermaidRenderedDiagram\x1a\xc1\x02\n" +
	"\tCodeBlock\x12W\n" +
	"\blanguage\x18\x01 \x01(\x0e2;.alis.open.support.v1.Guide.ContentBlock.CodeBlock.LanguageR\blanguage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x126\n" +
	"\x17syntax_highlighted_code\x18\x03 \x01(\tR\x15syntaxHighlightedCode\"\x8e\x01\n" +
	"\bLanguage\x12\x18\n" +
	"\x14LANGUAGE_UNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02GO\x10\x01\x12\t\n" +
	"\x05PROTO\x10\x02\x12\n" +
	"\n" +
	"\x06PYTHON\x10\x03\x12\a\n" +
	"\x03VUE\x10\x04\x12\x0e\n" +
	"\n" +
	"TYPESCRIPT\x10\x05\x12\t\n" +
	"\x05LATEX\x10\x06\x12\a\n" +
	"\x03HCL\x10\a\x12\b\n" +
	"\x04JSON\x10\b\x12\b\n" +
	"\x04YAML\x10\t\x12\b\n" +
	"\x04TEXT\x10\n" +
	"\"\xb1\x01\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05TITLE\x10\x01\x12\f\n" +
	"\bSUBTITLE\x10\x02\x12\v\n" +
	"\aHEADING\x10\x03\x12\r\n" +
	"\tTEXT_BODY\x10\x04\x12\t\n" +
	"\x05IMAGE\x10\x05\x12\t\n" +
	"\x05VIDEO\x10\x06\x12\v\n" +
	"\aDIVIDER\x10\a\x12\x10\n" +
	"\fLINK_PREVIEW\x10\b\x12\f\n" +
	"\bFOOTNOTE\x10\t\x12\v\n" +
	"\aDIAGRAM\x10\n" +
	"\x12\x0e\n" +
	"\n" +
	"CODE_BLOCK\x10\vB\a\n" +
	"\x05block\"^\n" +
	"\x0fGetGuideRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\"\xbb\x01\n" +
	"\x11ListGuidesRequest\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x127\n" +
	"\tread_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\x12\x16\n" +
	"\x06filter\x18\x05 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x06 \x01(\tR\aorderBy\"q\n" +
	"\x12ListGuidesResponse\x123\n" +
	"\x06guides\x18\x01 \x03(\v2\x1b.alis.open.support.v1.GuideR\x06guides\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"Y\n" +
	"\x10SyncGuideRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x121\n" +
	"\x05guide\x18\x02 \x01(\v2\x1b.alis.open.support.v1.GuideR\x05guide2\x82\x04\n" +
	"\rGuidesService\x12v\n" +
	"\x0fValidateMessage\x12/.alis.open.validation.v1.ValidateMessageRequest\x1a0.alis.open.validation.v1.ValidateMessageResponse\"\x00\x12p\n" +
	"\rRetrieveRules\x12-.alis.open.validation.v1.RetrieveRulesRequest\x1a..alis.open.validation.v1.RetrieveRulesResponse\"\x00\x12P\n" +
	"\bGetGuide\x12%.alis.open.support.v1.GetGuideRequest\x1a\x1b.alis.open.support.v1.Guide\"\x00\x12a\n" +
	"\n" +
	"ListGuides\x12'.alis.open.support.v1.ListGuidesRequest\x1a(.alis.open.support.v1.ListGuidesResponse\"\x00\x12R\n" +
	"\tSyncGuide\x12&.alis.open.support.v1.SyncGuideRequest\x1a\x1b.alis.open.support.v1.Guide\"\x00B+Z)go.alis.build/common/alis/open/support/v1b\x06proto3"

var (
	file_alis_open_support_v1_guide_proto_rawDescOnce sync.Once
	file_alis_open_support_v1_guide_proto_rawDescData []byte
)

func file_alis_open_support_v1_guide_proto_rawDescGZIP() []byte {
	file_alis_open_support_v1_guide_proto_rawDescOnce.Do(func() {
		file_alis_open_support_v1_guide_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alis_open_support_v1_guide_proto_rawDesc), len(file_alis_open_support_v1_guide_proto_rawDesc)))
	})
	return file_alis_open_support_v1_guide_proto_rawDescData
}

var file_alis_open_support_v1_guide_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_alis_open_support_v1_guide_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_alis_open_support_v1_guide_proto_goTypes = []any{
	(Guide_ContentBlock_Type)(0),               // 0: alis.open.support.v1.Guide.ContentBlock.Type
	(Guide_ContentBlock_CodeBlock_Language)(0), // 1: alis.open.support.v1.Guide.ContentBlock.CodeBlock.Language
	(*Guide)(nil),                          // 2: alis.open.support.v1.Guide
	(*GetGuideRequest)(nil),                // 3: alis.open.support.v1.GetGuideRequest
	(*ListGuidesRequest)(nil),              // 4: alis.open.support.v1.ListGuidesRequest
	(*ListGuidesResponse)(nil),             // 5: alis.open.support.v1.ListGuidesResponse
	(*SyncGuideRequest)(nil),               // 6: alis.open.support.v1.SyncGuideRequest
	(*Guide_ContentBlock)(nil),             // 7: alis.open.support.v1.Guide.ContentBlock
	(*Guide_ContentBlock_Title)(nil),       // 8: alis.open.support.v1.Guide.ContentBlock.Title
	(*Guide_ContentBlock_Subtitle)(nil),    // 9: alis.open.support.v1.Guide.ContentBlock.Subtitle
	(*Guide_ContentBlock_Heading)(nil),     // 10: alis.open.support.v1.Guide.ContentBlock.Heading
	(*Guide_ContentBlock_TextBody)(nil),    // 11: alis.open.support.v1.Guide.ContentBlock.TextBody
	(*Guide_ContentBlock_Image)(nil),       // 12: alis.open.support.v1.Guide.ContentBlock.Image
	(*Guide_ContentBlock_Video)(nil),       // 13: alis.open.support.v1.Guide.ContentBlock.Video
	(*Guide_ContentBlock_Divider)(nil),     // 14: alis.open.support.v1.Guide.ContentBlock.Divider
	(*Guide_ContentBlock_LinkPreview)(nil), // 15: alis.open.support.v1.Guide.ContentBlock.LinkPreview
	(*Guide_ContentBlock_Footnote)(nil),    // 16: alis.open.support.v1.Guide.ContentBlock.Footnote
	(*Guide_ContentBlock_Diagram)(nil),     // 17: alis.open.support.v1.Guide.ContentBlock.Diagram
	(*Guide_ContentBlock_CodeBlock)(nil),   // 18: alis.open.support.v1.Guide.ContentBlock.CodeBlock
	(*protobuf.Timestamp)(nil),             // 19: google.protobuf.Timestamp
	(*protobuf.FieldMask)(nil),             // 20: google.protobuf.FieldMask
	(*v1.ValidateMessageRequest)(nil),      // 21: alis.open.validation.v1.ValidateMessageRequest
	(*v1.RetrieveRulesRequest)(nil),        // 22: alis.open.validation.v1.RetrieveRulesRequest
	(*v1.ValidateMessageResponse)(nil),     // 23: alis.open.validation.v1.ValidateMessageResponse
	(*v1.RetrieveRulesResponse)(nil),       // 24: alis.open.validation.v1.RetrieveRulesResponse
}
var file_alis_open_support_v1_guide_proto_depIdxs = []int32{
	7,  // 0: alis.open.support.v1.Guide.contents:type_name -> alis.open.support.v1.Guide.ContentBlock
	19, // 1: alis.open.support.v1.Guide.create_time:type_name -> google.protobuf.Timestamp
	19, // 2: alis.open.support.v1.Guide.update_time:type_name -> google.protobuf.Timestamp
	20, // 3: alis.open.support.v1.GetGuideRequest.read_mask:type_name -> google.protobuf.FieldMask
	20, // 4: alis.open.support.v1.ListGuidesRequest.read_mask:type_name -> google.protobuf.FieldMask
	2,  // 5: alis.open.support.v1.ListGuidesResponse.guides:type_name -> alis.open.support.v1.Guide
	2,  // 6: alis.open.support.v1.SyncGuideRequest.guide:type_name -> alis.open.support.v1.Guide
	0,  // 7: alis.open.support.v1.Guide.ContentBlock.type:type_name -> alis.open.support.v1.Guide.ContentBlock.Type
	8,  // 8: alis.open.support.v1.Guide.ContentBlock.title:type_name -> alis.open.support.v1.Guide.ContentBlock.Title
	9,  // 9: alis.open.support.v1.Guide.ContentBlock.subtitle:type_name -> alis.open.support.v1.Guide.ContentBlock.Subtitle
	10, // 10: alis.open.support.v1.Guide.ContentBlock.heading:type_name -> alis.open.support.v1.Guide.ContentBlock.Heading
	11, // 11: alis.open.support.v1.Guide.ContentBlock.text_body:type_name -> alis.open.support.v1.Guide.ContentBlock.TextBody
	12, // 12: alis.open.support.v1.Guide.ContentBlock.image:type_name -> alis.open.support.v1.Guide.ContentBlock.Image
	13, // 13: alis.open.support.v1.Guide.ContentBlock.video:type_name -> alis.open.support.v1.Guide.ContentBlock.Video
	14, // 14: alis.open.support.v1.Guide.ContentBlock.divider:type_name -> alis.open.support.v1.Guide.ContentBlock.Divider
	15, // 15: alis.open.support.v1.Guide.ContentBlock.link_preview:type_name -> alis.open.support.v1.Guide.ContentBlock.LinkPreview
	16, // 16: alis.open.support.v1.Guide.ContentBlock.footnote:type_name -> alis.open.support.v1.Guide.ContentBlock.Footnote
	17, // 17: alis.open.support.v1.Guide.ContentBlock.diagram:type_name -> alis.open.support.v1.Guide.ContentBlock.Diagram
	18, // 18: alis.open.support.v1.Guide.ContentBlock.code_block:type_name -> alis.open.support.v1.Guide.ContentBlock.CodeBlock
	1,  // 19: alis.open.support.v1.Guide.ContentBlock.CodeBlock.language:type_name -> alis.open.support.v1.Guide.ContentBlock.CodeBlock.Language
	21, // 20: alis.open.support.v1.GuidesService.ValidateMessage:input_type -> alis.open.validation.v1.ValidateMessageRequest
	22, // 21: alis.open.support.v1.GuidesService.RetrieveRules:input_type -> alis.open.validation.v1.RetrieveRulesRequest
	3,  // 22: alis.open.support.v1.GuidesService.GetGuide:input_type -> alis.open.support.v1.GetGuideRequest
	4,  // 23: alis.open.support.v1.GuidesService.ListGuides:input_type -> alis.open.support.v1.ListGuidesRequest
	6,  // 24: alis.open.support.v1.GuidesService.SyncGuide:input_type -> alis.open.support.v1.SyncGuideRequest
	23, // 25: alis.open.support.v1.GuidesService.ValidateMessage:output_type -> alis.open.validation.v1.ValidateMessageResponse
	24, // 26: alis.open.support.v1.GuidesService.RetrieveRules:output_type -> alis.open.validation.v1.RetrieveRulesResponse
	2,  // 27: alis.open.support.v1.GuidesService.GetGuide:output_type -> alis.open.support.v1.Guide
	5,  // 28: alis.open.support.v1.GuidesService.ListGuides:output_type -> alis.open.support.v1.ListGuidesResponse
	2,  // 29: alis.open.support.v1.GuidesService.SyncGuide:output_type -> alis.open.support.v1.Guide
	25, // [25:30] is the sub-list for method output_type
	20, // [20:25] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_alis_open_support_v1_guide_proto_init() }
func file_alis_open_support_v1_guide_proto_init() {
	if File_alis_open_support_v1_guide_proto != nil {
		return
	}
	file_alis_open_support_v1_guide_proto_msgTypes[5].OneofWrappers = []any{
		(*Guide_ContentBlock_Title_)(nil),
		(*Guide_ContentBlock_Subtitle_)(nil),
		(*Guide_ContentBlock_Heading_)(nil),
		(*Guide_ContentBlock_TextBody_)(nil),
		(*Guide_ContentBlock_Image_)(nil),
		(*Guide_ContentBlock_Video_)(nil),
		(*Guide_ContentBlock_Divider_)(nil),
		(*Guide_ContentBlock_LinkPreview_)(nil),
		(*Guide_ContentBlock_Footnote_)(nil),
		(*Guide_ContentBlock_Diagram_)(nil),
		(*Guide_ContentBlock_CodeBlock_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alis_open_support_v1_guide_proto_rawDesc), len(file_alis_open_support_v1_guide_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alis_open_support_v1_guide_proto_goTypes,
		DependencyIndexes: file_alis_open_support_v1_guide_proto_depIdxs,
		EnumInfos:         file_alis_open_support_v1_guide_proto_enumTypes,
		MessageInfos:      file_alis_open_support_v1_guide_proto_msgTypes,
	}.Build()
	File_alis_open_support_v1_guide_proto = out.File
	file_alis_open_support_v1_guide_proto_goTypes = nil
	file_alis_open_support_v1_guide_proto_depIdxs = nil
}
