// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.24.4
// source: alis/open/support/v1/issuesubscriber.proto

package v1

import (
	context "context"
	v12 "go.alis.build/common/alis/open/iam/v1"
	v1 "go.alis.build/common/alis/open/validation/v1"
	v11 "go.alis.build/common/google/iam/v1"
	protobuf "go.alis.build/common/google/protobuf"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IssueSubscribersService_ValidateMessage_FullMethodName       = "/alis.open.support.v1.IssueSubscribersService/ValidateMessage"
	IssueSubscribersService_RetrieveRules_FullMethodName         = "/alis.open.support.v1.IssueSubscribersService/RetrieveRules"
	IssueSubscribersService_GetIamPolicy_FullMethodName          = "/alis.open.support.v1.IssueSubscribersService/GetIamPolicy"
	IssueSubscribersService_SetIamPolicy_FullMethodName          = "/alis.open.support.v1.IssueSubscribersService/SetIamPolicy"
	IssueSubscribersService_TestIamPermissions_FullMethodName    = "/alis.open.support.v1.IssueSubscribersService/TestIamPermissions"
	IssueSubscribersService_AddIamBindings_FullMethodName        = "/alis.open.support.v1.IssueSubscribersService/AddIamBindings"
	IssueSubscribersService_RemoveIamBindings_FullMethodName     = "/alis.open.support.v1.IssueSubscribersService/RemoveIamBindings"
	IssueSubscribersService_CreateIssueSubscriber_FullMethodName = "/alis.open.support.v1.IssueSubscribersService/CreateIssueSubscriber"
	IssueSubscribersService_GetIssueSubscriber_FullMethodName    = "/alis.open.support.v1.IssueSubscribersService/GetIssueSubscriber"
	IssueSubscribersService_ListIssueSubscribers_FullMethodName  = "/alis.open.support.v1.IssueSubscribersService/ListIssueSubscribers"
	IssueSubscribersService_DeleteIssueSubscriber_FullMethodName = "/alis.open.support.v1.IssueSubscribersService/DeleteIssueSubscriber"
)

// IssueSubscribersServiceClient is the client API for IssueSubscribersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IssueSubscribersService provides RPCs for managing IssueSubscriber resources.
type IssueSubscribersServiceClient interface {
	// Validates any proto message that is used directly or indirectly by this service.
	// Most common use issue is to validate request messages from a client-side application.
	ValidateMessage(ctx context.Context, in *v1.ValidateMessageRequest, opts ...grpc.CallOption) (*v1.ValidateMessageResponse, error)
	// Retrieves the validation rules for any proto message that is used directly or indirectly by this service.
	// Serves as live auto-documentation of the validation rules in this service.
	RetrieveRules(ctx context.Context, in *v1.RetrieveRulesRequest, opts ...grpc.CallOption) (*v1.RetrieveRulesResponse, error)
	// Gets the IAM policy for a resource implemented in this service.
	GetIamPolicy(ctx context.Context, in *v11.GetIamPolicyRequest, opts ...grpc.CallOption) (*v11.Policy, error)
	// Sets the IAM policy for a resource implemented in this service.
	SetIamPolicy(ctx context.Context, in *v11.SetIamPolicyRequest, opts ...grpc.CallOption) (*v11.Policy, error)
	// Returns permissions that a caller has on the specified resource.
	TestIamPermissions(ctx context.Context, in *v11.TestIamPermissionsRequest, opts ...grpc.CallOption) (*v11.TestIamPermissionsResponse, error)
	// Adds principals or updates the roles existing principals have on an IAM Policy protected resource.
	AddIamBindings(ctx context.Context, in *v12.AddIamBindingsRequest, opts ...grpc.CallOption) (*v11.Policy, error)
	// Removes principals or some of the roles they have on an IAM Policy protected resource.
	RemoveIamBindings(ctx context.Context, in *v12.RemoveIamBindingsRequest, opts ...grpc.CallOption) (*v11.Policy, error)
	// Subscribes a user to an issue.
	CreateIssueSubscriber(ctx context.Context, in *CreateIssueSubscriberRequest, opts ...grpc.CallOption) (*IssueSubscriber, error)
	// Gets a user's subscription to an issue.
	GetIssueSubscriber(ctx context.Context, in *GetIssueSubscriberRequest, opts ...grpc.CallOption) (*IssueSubscriber, error)
	// Gets a list of subscribers for an issue.
	ListIssueSubscribers(ctx context.Context, in *ListIssueSubscribersRequest, opts ...grpc.CallOption) (*ListIssueSubscribersResponse, error)
	// Deletes an issue subscription.
	DeleteIssueSubscriber(ctx context.Context, in *DeleteIssueSubscriberRequest, opts ...grpc.CallOption) (*protobuf.Empty, error)
}

type issueSubscribersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIssueSubscribersServiceClient(cc grpc.ClientConnInterface) IssueSubscribersServiceClient {
	return &issueSubscribersServiceClient{cc}
}

func (c *issueSubscribersServiceClient) ValidateMessage(ctx context.Context, in *v1.ValidateMessageRequest, opts ...grpc.CallOption) (*v1.ValidateMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ValidateMessageResponse)
	err := c.cc.Invoke(ctx, IssueSubscribersService_ValidateMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueSubscribersServiceClient) RetrieveRules(ctx context.Context, in *v1.RetrieveRulesRequest, opts ...grpc.CallOption) (*v1.RetrieveRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.RetrieveRulesResponse)
	err := c.cc.Invoke(ctx, IssueSubscribersService_RetrieveRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueSubscribersServiceClient) GetIamPolicy(ctx context.Context, in *v11.GetIamPolicyRequest, opts ...grpc.CallOption) (*v11.Policy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v11.Policy)
	err := c.cc.Invoke(ctx, IssueSubscribersService_GetIamPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueSubscribersServiceClient) SetIamPolicy(ctx context.Context, in *v11.SetIamPolicyRequest, opts ...grpc.CallOption) (*v11.Policy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v11.Policy)
	err := c.cc.Invoke(ctx, IssueSubscribersService_SetIamPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueSubscribersServiceClient) TestIamPermissions(ctx context.Context, in *v11.TestIamPermissionsRequest, opts ...grpc.CallOption) (*v11.TestIamPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v11.TestIamPermissionsResponse)
	err := c.cc.Invoke(ctx, IssueSubscribersService_TestIamPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueSubscribersServiceClient) AddIamBindings(ctx context.Context, in *v12.AddIamBindingsRequest, opts ...grpc.CallOption) (*v11.Policy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v11.Policy)
	err := c.cc.Invoke(ctx, IssueSubscribersService_AddIamBindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueSubscribersServiceClient) RemoveIamBindings(ctx context.Context, in *v12.RemoveIamBindingsRequest, opts ...grpc.CallOption) (*v11.Policy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v11.Policy)
	err := c.cc.Invoke(ctx, IssueSubscribersService_RemoveIamBindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueSubscribersServiceClient) CreateIssueSubscriber(ctx context.Context, in *CreateIssueSubscriberRequest, opts ...grpc.CallOption) (*IssueSubscriber, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueSubscriber)
	err := c.cc.Invoke(ctx, IssueSubscribersService_CreateIssueSubscriber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueSubscribersServiceClient) GetIssueSubscriber(ctx context.Context, in *GetIssueSubscriberRequest, opts ...grpc.CallOption) (*IssueSubscriber, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueSubscriber)
	err := c.cc.Invoke(ctx, IssueSubscribersService_GetIssueSubscriber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueSubscribersServiceClient) ListIssueSubscribers(ctx context.Context, in *ListIssueSubscribersRequest, opts ...grpc.CallOption) (*ListIssueSubscribersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIssueSubscribersResponse)
	err := c.cc.Invoke(ctx, IssueSubscribersService_ListIssueSubscribers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueSubscribersServiceClient) DeleteIssueSubscriber(ctx context.Context, in *DeleteIssueSubscriberRequest, opts ...grpc.CallOption) (*protobuf.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(protobuf.Empty)
	err := c.cc.Invoke(ctx, IssueSubscribersService_DeleteIssueSubscriber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IssueSubscribersServiceServer is the server API for IssueSubscribersService service.
// All implementations must embed UnimplementedIssueSubscribersServiceServer
// for forward compatibility.
//
// IssueSubscribersService provides RPCs for managing IssueSubscriber resources.
type IssueSubscribersServiceServer interface {
	// Validates any proto message that is used directly or indirectly by this service.
	// Most common use issue is to validate request messages from a client-side application.
	ValidateMessage(context.Context, *v1.ValidateMessageRequest) (*v1.ValidateMessageResponse, error)
	// Retrieves the validation rules for any proto message that is used directly or indirectly by this service.
	// Serves as live auto-documentation of the validation rules in this service.
	RetrieveRules(context.Context, *v1.RetrieveRulesRequest) (*v1.RetrieveRulesResponse, error)
	// Gets the IAM policy for a resource implemented in this service.
	GetIamPolicy(context.Context, *v11.GetIamPolicyRequest) (*v11.Policy, error)
	// Sets the IAM policy for a resource implemented in this service.
	SetIamPolicy(context.Context, *v11.SetIamPolicyRequest) (*v11.Policy, error)
	// Returns permissions that a caller has on the specified resource.
	TestIamPermissions(context.Context, *v11.TestIamPermissionsRequest) (*v11.TestIamPermissionsResponse, error)
	// Adds principals or updates the roles existing principals have on an IAM Policy protected resource.
	AddIamBindings(context.Context, *v12.AddIamBindingsRequest) (*v11.Policy, error)
	// Removes principals or some of the roles they have on an IAM Policy protected resource.
	RemoveIamBindings(context.Context, *v12.RemoveIamBindingsRequest) (*v11.Policy, error)
	// Subscribes a user to an issue.
	CreateIssueSubscriber(context.Context, *CreateIssueSubscriberRequest) (*IssueSubscriber, error)
	// Gets a user's subscription to an issue.
	GetIssueSubscriber(context.Context, *GetIssueSubscriberRequest) (*IssueSubscriber, error)
	// Gets a list of subscribers for an issue.
	ListIssueSubscribers(context.Context, *ListIssueSubscribersRequest) (*ListIssueSubscribersResponse, error)
	// Deletes an issue subscription.
	DeleteIssueSubscriber(context.Context, *DeleteIssueSubscriberRequest) (*protobuf.Empty, error)
	mustEmbedUnimplementedIssueSubscribersServiceServer()
}

// UnimplementedIssueSubscribersServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIssueSubscribersServiceServer struct{}

func (UnimplementedIssueSubscribersServiceServer) ValidateMessage(context.Context, *v1.ValidateMessageRequest) (*v1.ValidateMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateMessage not implemented")
}
func (UnimplementedIssueSubscribersServiceServer) RetrieveRules(context.Context, *v1.RetrieveRulesRequest) (*v1.RetrieveRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrieveRules not implemented")
}
func (UnimplementedIssueSubscribersServiceServer) GetIamPolicy(context.Context, *v11.GetIamPolicyRequest) (*v11.Policy, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIamPolicy not implemented")
}
func (UnimplementedIssueSubscribersServiceServer) SetIamPolicy(context.Context, *v11.SetIamPolicyRequest) (*v11.Policy, error) {
	return nil, status.Error(codes.Unimplemented, "method SetIamPolicy not implemented")
}
func (UnimplementedIssueSubscribersServiceServer) TestIamPermissions(context.Context, *v11.TestIamPermissionsRequest) (*v11.TestIamPermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestIamPermissions not implemented")
}
func (UnimplementedIssueSubscribersServiceServer) AddIamBindings(context.Context, *v12.AddIamBindingsRequest) (*v11.Policy, error) {
	return nil, status.Error(codes.Unimplemented, "method AddIamBindings not implemented")
}
func (UnimplementedIssueSubscribersServiceServer) RemoveIamBindings(context.Context, *v12.RemoveIamBindingsRequest) (*v11.Policy, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveIamBindings not implemented")
}
func (UnimplementedIssueSubscribersServiceServer) CreateIssueSubscriber(context.Context, *CreateIssueSubscriberRequest) (*IssueSubscriber, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateIssueSubscriber not implemented")
}
func (UnimplementedIssueSubscribersServiceServer) GetIssueSubscriber(context.Context, *GetIssueSubscriberRequest) (*IssueSubscriber, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIssueSubscriber not implemented")
}
func (UnimplementedIssueSubscribersServiceServer) ListIssueSubscribers(context.Context, *ListIssueSubscribersRequest) (*ListIssueSubscribersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIssueSubscribers not implemented")
}
func (UnimplementedIssueSubscribersServiceServer) DeleteIssueSubscriber(context.Context, *DeleteIssueSubscriberRequest) (*protobuf.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteIssueSubscriber not implemented")
}
func (UnimplementedIssueSubscribersServiceServer) mustEmbedUnimplementedIssueSubscribersServiceServer() {
}
func (UnimplementedIssueSubscribersServiceServer) testEmbeddedByValue() {}

// UnsafeIssueSubscribersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IssueSubscribersServiceServer will
// result in compilation errors.
type UnsafeIssueSubscribersServiceServer interface {
	mustEmbedUnimplementedIssueSubscribersServiceServer()
}

func RegisterIssueSubscribersServiceServer(s grpc.ServiceRegistrar, srv IssueSubscribersServiceServer) {
	// If the following call panics, it indicates UnimplementedIssueSubscribersServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IssueSubscribersService_ServiceDesc, srv)
}

func _IssueSubscribersService_ValidateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ValidateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueSubscribersServiceServer).ValidateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueSubscribersService_ValidateMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueSubscribersServiceServer).ValidateMessage(ctx, req.(*v1.ValidateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueSubscribersService_RetrieveRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.RetrieveRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueSubscribersServiceServer).RetrieveRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueSubscribersService_RetrieveRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueSubscribersServiceServer).RetrieveRules(ctx, req.(*v1.RetrieveRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueSubscribersService_GetIamPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v11.GetIamPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueSubscribersServiceServer).GetIamPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueSubscribersService_GetIamPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueSubscribersServiceServer).GetIamPolicy(ctx, req.(*v11.GetIamPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueSubscribersService_SetIamPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v11.SetIamPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueSubscribersServiceServer).SetIamPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueSubscribersService_SetIamPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueSubscribersServiceServer).SetIamPolicy(ctx, req.(*v11.SetIamPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueSubscribersService_TestIamPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v11.TestIamPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueSubscribersServiceServer).TestIamPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueSubscribersService_TestIamPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueSubscribersServiceServer).TestIamPermissions(ctx, req.(*v11.TestIamPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueSubscribersService_AddIamBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v12.AddIamBindingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueSubscribersServiceServer).AddIamBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueSubscribersService_AddIamBindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueSubscribersServiceServer).AddIamBindings(ctx, req.(*v12.AddIamBindingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueSubscribersService_RemoveIamBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v12.RemoveIamBindingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueSubscribersServiceServer).RemoveIamBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueSubscribersService_RemoveIamBindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueSubscribersServiceServer).RemoveIamBindings(ctx, req.(*v12.RemoveIamBindingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueSubscribersService_CreateIssueSubscriber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIssueSubscriberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueSubscribersServiceServer).CreateIssueSubscriber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueSubscribersService_CreateIssueSubscriber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueSubscribersServiceServer).CreateIssueSubscriber(ctx, req.(*CreateIssueSubscriberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueSubscribersService_GetIssueSubscriber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIssueSubscriberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueSubscribersServiceServer).GetIssueSubscriber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueSubscribersService_GetIssueSubscriber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueSubscribersServiceServer).GetIssueSubscriber(ctx, req.(*GetIssueSubscriberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueSubscribersService_ListIssueSubscribers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIssueSubscribersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueSubscribersServiceServer).ListIssueSubscribers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueSubscribersService_ListIssueSubscribers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueSubscribersServiceServer).ListIssueSubscribers(ctx, req.(*ListIssueSubscribersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueSubscribersService_DeleteIssueSubscriber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIssueSubscriberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueSubscribersServiceServer).DeleteIssueSubscriber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueSubscribersService_DeleteIssueSubscriber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueSubscribersServiceServer).DeleteIssueSubscriber(ctx, req.(*DeleteIssueSubscriberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IssueSubscribersService_ServiceDesc is the grpc.ServiceDesc for IssueSubscribersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IssueSubscribersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alis.open.support.v1.IssueSubscribersService",
	HandlerType: (*IssueSubscribersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateMessage",
			Handler:    _IssueSubscribersService_ValidateMessage_Handler,
		},
		{
			MethodName: "RetrieveRules",
			Handler:    _IssueSubscribersService_RetrieveRules_Handler,
		},
		{
			MethodName: "GetIamPolicy",
			Handler:    _IssueSubscribersService_GetIamPolicy_Handler,
		},
		{
			MethodName: "SetIamPolicy",
			Handler:    _IssueSubscribersService_SetIamPolicy_Handler,
		},
		{
			MethodName: "TestIamPermissions",
			Handler:    _IssueSubscribersService_TestIamPermissions_Handler,
		},
		{
			MethodName: "AddIamBindings",
			Handler:    _IssueSubscribersService_AddIamBindings_Handler,
		},
		{
			MethodName: "RemoveIamBindings",
			Handler:    _IssueSubscribersService_RemoveIamBindings_Handler,
		},
		{
			MethodName: "CreateIssueSubscriber",
			Handler:    _IssueSubscribersService_CreateIssueSubscriber_Handler,
		},
		{
			MethodName: "GetIssueSubscriber",
			Handler:    _IssueSubscribersService_GetIssueSubscriber_Handler,
		},
		{
			MethodName: "ListIssueSubscribers",
			Handler:    _IssueSubscribersService_ListIssueSubscribers_Handler,
		},
		{
			MethodName: "DeleteIssueSubscriber",
			Handler:    _IssueSubscribersService_DeleteIssueSubscriber_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alis/open/support/v1/issuesubscriber.proto",
}
