// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: standards/open/fundholdings/v1/apex_ftrdist.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-07-13 07:29:12 UTC

package v1

const ()
