// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: standards/open/fundholdings/v1/apex_ftrdist.proto

package v1

import (
	date "google.golang.org/genproto/googleapis/type/date"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FTRDIST report format generated by JTC.
type APEX_FTRDIST struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The date that the file data pertains to
	// Note: This is deduced from the name of the file received by JTC during parsing
	EffectiveDate *date.Date `protobuf:"bytes,1,opt,name=effective_date,json=effectiveDate,proto3" json:"effective_date,omitempty"`
	// A list of FTRDIST records.
	// Each record refers to a row in the original CSV file from Jtc.
	Records       []*APEX_FTRDIST_Record `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APEX_FTRDIST) Reset() {
	*x = APEX_FTRDIST{}
	mi := &file_standards_open_fundholdings_v1_apex_ftrdist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APEX_FTRDIST) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APEX_FTRDIST) ProtoMessage() {}

func (x *APEX_FTRDIST) ProtoReflect() protoreflect.Message {
	mi := &file_standards_open_fundholdings_v1_apex_ftrdist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APEX_FTRDIST.ProtoReflect.Descriptor instead.
func (*APEX_FTRDIST) Descriptor() ([]byte, []int) {
	return file_standards_open_fundholdings_v1_apex_ftrdist_proto_rawDescGZIP(), []int{0}
}

func (x *APEX_FTRDIST) GetEffectiveDate() *date.Date {
	if x != nil {
		return x.EffectiveDate
	}
	return nil
}

func (x *APEX_FTRDIST) GetRecords() []*APEX_FTRDIST_Record {
	if x != nil {
		return x.Records
	}
	return nil
}

// A row in the FTRDIST file
type APEX_FTRDIST_Record struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Date of source file
	RequestDate *date.Date `protobuf:"bytes,1,opt,name=request_date,json=requestDate,proto3" json:"request_date,omitempty"`
	// Account number
	AccountNumber string `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	// Account name
	AccountName string `protobuf:"bytes,3,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	// Date of account verification
	AccountVerificationDate *date.Date `protobuf:"bytes,4,opt,name=account_verification_date,json=accountVerificationDate,proto3" json:"account_verification_date,omitempty"`
	// Account class (e.g. individual, joint, etc.)
	AccountClass string `protobuf:"bytes,5,opt,name=account_class,json=accountClass,proto3" json:"account_class,omitempty"`
	// Net assets of OEIC (Open-Ended Investment Company)
	OeicNetAssets *wrapperspb.DoubleValue `protobuf:"bytes,6,opt,name=oeic_net_assets,json=oeicNetAssets,proto3" json:"oeic_net_assets,omitempty"`
	// Shareholder equity
	ShareholderEquity *wrapperspb.DoubleValue `protobuf:"bytes,7,opt,name=shareholder_equity,json=shareholderEquity,proto3" json:"shareholder_equity,omitempty"`
	// Ownership percentage of class
	ClassOwnershipPercent *wrapperspb.DoubleValue `protobuf:"bytes,8,opt,name=class_ownership_percent,json=classOwnershipPercent,proto3" json:"class_ownership_percent,omitempty"`
	// Currency of class
	ClassCurr string `protobuf:"bytes,9,opt,name=class_curr,json=classCurr,proto3" json:"class_curr,omitempty"`
	// Net income of class in current currency
	ClassCurrNetIncome *wrapperspb.DoubleValue `protobuf:"bytes,10,opt,name=class_curr_net_income,json=classCurrNetIncome,proto3" json:"class_curr_net_income,omitempty"`
	// Quoted NAV (Net Asset Value) for OEIC funds
	QuotedNavForOeicFunds *wrapperspb.DoubleValue `protobuf:"bytes,11,opt,name=quoted_nav_for_oeic_funds,json=quotedNavForOeicFunds,proto3" json:"quoted_nav_for_oeic_funds,omitempty"`
	// NAV of OEIC
	OeicNav *wrapperspb.DoubleValue `protobuf:"bytes,12,opt,name=oeic_nav,json=oeicNav,proto3" json:"oeic_nav,omitempty"`
	// Outstanding units
	UnitsOutstanding *wrapperspb.DoubleValue `protobuf:"bytes,13,opt,name=units_outstanding,json=unitsOutstanding,proto3" json:"units_outstanding,omitempty"`
	// Total assets
	TotalAssets *wrapperspb.DoubleValue `protobuf:"bytes,14,opt,name=total_assets,json=totalAssets,proto3" json:"total_assets,omitempty"`
	// Total liabilities
	TotalLiabilities *wrapperspb.DoubleValue `protobuf:"bytes,15,opt,name=total_liabilities,json=totalLiabilities,proto3" json:"total_liabilities,omitempty"`
	// Capital value of OEIC
	OeicCapitalValue *wrapperspb.DoubleValue `protobuf:"bytes,16,opt,name=oeic_capital_value,json=oeicCapitalValue,proto3" json:"oeic_capital_value,omitempty"`
	// Amount of net income
	NetIncomeAmount *wrapperspb.DoubleValue `protobuf:"bytes,17,opt,name=net_income_amount,json=netIncomeAmount,proto3" json:"net_income_amount,omitempty"`
	// Unrealized gain/loss
	UnrealizedGainloss *wrapperspb.DoubleValue `protobuf:"bytes,18,opt,name=unrealized_gainloss,json=unrealizedGainloss,proto3" json:"unrealized_gainloss,omitempty"`
	// Value of securities
	SecurityValue *wrapperspb.DoubleValue `protobuf:"bytes,19,opt,name=security_value,json=securityValue,proto3" json:"security_value,omitempty"`
	// Cash balance
	Cash *wrapperspb.DoubleValue `protobuf:"bytes,20,opt,name=cash,proto3" json:"cash,omitempty"`
	// Foreign currency
	ForeignCurrency *wrapperspb.DoubleValue `protobuf:"bytes,21,opt,name=foreign_currency,json=foreignCurrency,proto3" json:"foreign_currency,omitempty"`
	// Accrued income
	AccruedIncome *wrapperspb.DoubleValue `protobuf:"bytes,22,opt,name=accrued_income,json=accruedIncome,proto3" json:"accrued_income,omitempty"`
	// Accrued withholding
	AccruedWithholding *wrapperspb.DoubleValue `protobuf:"bytes,23,opt,name=accrued_withholding,json=accruedWithholding,proto3" json:"accrued_withholding,omitempty"`
	// Net accrued income after withholding
	AccruedIncomeNetAccruedWithholding *wrapperspb.DoubleValue `protobuf:"bytes,24,opt,name=accrued_income_net_accrued_withholding,json=accruedIncomeNetAccruedWithholding,proto3" json:"accrued_income_net_accrued_withholding,omitempty"`
	// Amount to reclaim from accrued income
	ReclaimAccrued *wrapperspb.DoubleValue `protobuf:"bytes,25,opt,name=reclaim_accrued,json=reclaimAccrued,proto3" json:"reclaim_accrued,omitempty"`
	// Capital assets receivable
	CapitalAssetsReceivable *wrapperspb.DoubleValue `protobuf:"bytes,26,opt,name=capital_assets_receivable,json=capitalAssetsReceivable,proto3" json:"capital_assets_receivable,omitempty"`
	// Capital shares receivable
	CapitalSharesReceivable *wrapperspb.DoubleValue `protobuf:"bytes,27,opt,name=capital_shares_receivable,json=capitalSharesReceivable,proto3" json:"capital_shares_receivable,omitempty"`
	// Currency receivable less forwards
	CurrencyRecvLessForwards *wrapperspb.DoubleValue `protobuf:"bytes,28,opt,name=currency_recv_less_forwards,json=currencyRecvLessForwards,proto3" json:"currency_recv_less_forwards,omitempty"`
	// Spot receivable
	SpotReceivable *wrapperspb.DoubleValue `protobuf:"bytes,29,opt,name=spot_receivable,json=spotReceivable,proto3" json:"spot_receivable,omitempty"`
	// Securities sold receivable
	SecuritiesSoldReceivable *wrapperspb.DoubleValue `protobuf:"bytes,30,opt,name=securities_sold_receivable,json=securitiesSoldReceivable,proto3" json:"securities_sold_receivable,omitempty"`
	// Net reclaim receivable after accrued
	ReclaimReceivableNetAccrued *wrapperspb.DoubleValue `protobuf:"bytes,31,opt,name=reclaim_receivable_net_accrued,json=reclaimReceivableNetAccrued,proto3" json:"reclaim_receivable_net_accrued,omitempty"`
	// Short income receivable in foreign currency
	CurrencyShortIncomeRecv *wrapperspb.DoubleValue `protobuf:"bytes,32,opt,name=currency_short_income_recv,json=currencyShortIncomeRecv,proto3" json:"currency_short_income_recv,omitempty"`
	// Short sale receivable in foreign currency
	CurrencyShortSaleRecv *wrapperspb.DoubleValue `protobuf:"bytes,33,opt,name=currency_short_sale_recv,json=currencyShortSaleRecv,proto3" json:"currency_short_sale_recv,omitempty"`
	// Unrealized gain on foreign exchange contracts
	UnrealizedGainOnFec *wrapperspb.DoubleValue `protobuf:"bytes,34,opt,name=unrealized_gain_on_fec,json=unrealizedGainOnFec,proto3" json:"unrealized_gain_on_fec,omitempty"`
	// Variation margins receivable
	VariationMarginsReceivable *wrapperspb.DoubleValue `protobuf:"bytes,35,opt,name=variation_margins_receivable,json=variationMarginsReceivable,proto3" json:"variation_margins_receivable,omitempty"`
	// Other receivables (true amount)
	OtherReceivablesTrue *wrapperspb.DoubleValue `protobuf:"bytes,36,opt,name=other_receivables_true,json=otherReceivablesTrue,proto3" json:"other_receivables_true,omitempty"`
	// Appreciation/depreciation of futures
	FuturesApprecdeprec *wrapperspb.DoubleValue `protobuf:"bytes,37,opt,name=futures_apprecdeprec,json=futuresApprecdeprec,proto3" json:"futures_apprecdeprec,omitempty"`
	// Appreciation/depreciation of futures transactions
	FuturesApprecdeprecTrans *wrapperspb.DoubleValue `protobuf:"bytes,38,opt,name=futures_apprecdeprec_trans,json=futuresApprecdeprecTrans,proto3" json:"futures_apprecdeprec_trans,omitempty"`
	// Margin deposits
	MarginDeposits *wrapperspb.DoubleValue `protobuf:"bytes,39,opt,name=margin_deposits,json=marginDeposits,proto3" json:"margin_deposits,omitempty"`
	// Accrued expenses
	AccruedExpense *wrapperspb.DoubleValue `protobuf:"bytes,40,opt,name=accrued_expense,json=accruedExpense,proto3" json:"accrued_expense,omitempty"`
	// Prepaid expenses
	PrepaidExpense *wrapperspb.DoubleValue `protobuf:"bytes,41,opt,name=prepaid_expense,json=prepaidExpense,proto3" json:"prepaid_expense,omitempty"`
	// Expenses paid during the period
	ExpensesPaidDuringPeriod *wrapperspb.DoubleValue `protobuf:"bytes,42,opt,name=expenses_paid_during_period,json=expensesPaidDuringPeriod,proto3" json:"expenses_paid_during_period,omitempty"`
	// Total class-specific expenses for the fund
	FundTotalClassSpecificExpCurr *wrapperspb.DoubleValue `protobuf:"bytes,43,opt,name=fund_total_class_specific_exp_curr,json=fundTotalClassSpecificExpCurr,proto3" json:"fund_total_class_specific_exp_curr,omitempty"`
	// Variation margins for positions
	VariationMarginsPositions *wrapperspb.DoubleValue `protobuf:"bytes,44,opt,name=variation_margins_positions,json=variationMarginsPositions,proto3" json:"variation_margins_positions,omitempty"`
	// Variation margins for assets transactions
	VariationMarginsAssetsTransactions *wrapperspb.DoubleValue `protobuf:"bytes,45,opt,name=variation_margins_assets_transactions,json=variationMarginsAssetsTransactions,proto3" json:"variation_margins_assets_transactions,omitempty"`
	// Other assets that are true
	OtherAssetsTrue *wrapperspb.DoubleValue `protobuf:"bytes,46,opt,name=other_assets_true,json=otherAssetsTrue,proto3" json:"other_assets_true,omitempty"`
	// Other payables
	OtherPayables *wrapperspb.DoubleValue `protobuf:"bytes,47,opt,name=other_payables,json=otherPayables,proto3" json:"other_payables,omitempty"`
	// Other receivables
	OtherReceivables *wrapperspb.DoubleValue `protobuf:"bytes,48,opt,name=other_receivables,json=otherReceivables,proto3" json:"other_receivables,omitempty"`
	// Accrued capital expenses
	AccruedCapitalExpense *wrapperspb.DoubleValue `protobuf:"bytes,49,opt,name=accrued_capital_expense,json=accruedCapitalExpense,proto3" json:"accrued_capital_expense,omitempty"`
	// Broker commissions payable
	BrokerCommissionsPayable *wrapperspb.DoubleValue `protobuf:"bytes,50,opt,name=broker_commissions_payable,json=brokerCommissionsPayable,proto3" json:"broker_commissions_payable,omitempty"`
	// Capital gains payable
	CapitalGainsPayable *wrapperspb.DoubleValue `protobuf:"bytes,51,opt,name=capital_gains_payable,json=capitalGainsPayable,proto3" json:"capital_gains_payable,omitempty"`
	// Capital assets payable
	CapitalAssetsPayable *wrapperspb.DoubleValue `protobuf:"bytes,52,opt,name=capital_assets_payable,json=capitalAssetsPayable,proto3" json:"capital_assets_payable,omitempty"`
	// Total inflation compensation earned
	TotalInflatCompEarned *wrapperspb.DoubleValue `protobuf:"bytes,53,opt,name=total_inflat_comp_earned,json=totalInflatCompEarned,proto3" json:"total_inflat_comp_earned,omitempty"`
	// Capital shares payable
	CapitalSharesPayable *wrapperspb.DoubleValue `protobuf:"bytes,54,opt,name=capital_shares_payable,json=capitalSharesPayable,proto3" json:"capital_shares_payable,omitempty"`
	// Currency payable less forwards
	CurrencyPayableLessForwards *wrapperspb.DoubleValue `protobuf:"bytes,55,opt,name=currency_payable_less_forwards,json=currencyPayableLessForwards,proto3" json:"currency_payable_less_forwards,omitempty"`
	// Spot payable
	SpotPayable *wrapperspb.DoubleValue `protobuf:"bytes,56,opt,name=spot_payable,json=spotPayable,proto3" json:"spot_payable,omitempty"`
	// Income payable
	IncomePayable *wrapperspb.DoubleValue `protobuf:"bytes,57,opt,name=income_payable,json=incomePayable,proto3" json:"income_payable,omitempty"`
	// Securities purchased payable
	SecuritiesPurchasedPayable *wrapperspb.DoubleValue `protobuf:"bytes,58,opt,name=securities_purchased_payable,json=securitiesPurchasedPayable,proto3" json:"securities_purchased_payable,omitempty"`
	// Unrealized loss on fair value estimates
	UnrealizedLossOnFec *wrapperspb.DoubleValue `protobuf:"bytes,59,opt,name=unrealized_loss_on_fec,json=unrealizedLossOnFec,proto3" json:"unrealized_loss_on_fec,omitempty"`
	// Variation margins payable
	VariationMarginsPayable *wrapperspb.DoubleValue `protobuf:"bytes,60,opt,name=variation_margins_payable,json=variationMarginsPayable,proto3" json:"variation_margins_payable,omitempty"`
	// Other payables that are true
	OtherPayablesTrue *wrapperspb.DoubleValue `protobuf:"bytes,61,opt,name=other_payables_true,json=otherPayablesTrue,proto3" json:"other_payables_true,omitempty"`
	// Short securities market value
	ShortSctyMarket *wrapperspb.DoubleValue `protobuf:"bytes,62,opt,name=short_scty_market,json=shortSctyMarket,proto3" json:"short_scty_market,omitempty"`
	// Valuation period end date ()
	ValuationPeriodEndDate *date.Date `protobuf:"bytes,63,opt,name=valuation_period_end_date,json=valuationPeriodEndDate,proto3" json:"valuation_period_end_date,omitempty"`
	// Full offer valuation ()
	FullOfferValuation *wrapperspb.DoubleValue `protobuf:"bytes,64,opt,name=full_offer_valuation,json=fullOfferValuation,proto3" json:"full_offer_valuation,omitempty"`
	// Rounded mid price ()
	RoundedMidPrice *wrapperspb.DoubleValue `protobuf:"bytes,65,opt,name=rounded_mid_price,json=roundedMidPrice,proto3" json:"rounded_mid_price,omitempty"`
	// OEIC quoted NAV ()
	OeicQuotedNav *wrapperspb.DoubleValue `protobuf:"bytes,66,opt,name=oeic_quoted_nav,json=oeicQuotedNav,proto3" json:"oeic_quoted_nav,omitempty"`
	// Class current NAV ()
	ClassCurrNav *wrapperspb.DoubleValue `protobuf:"bytes,67,opt,name=class_curr_nav,json=classCurrNav,proto3" json:"class_curr_nav,omitempty"`
	// Class current net assets (current) ()
	ClassCurrNetAssetsCurrent *wrapperspb.DoubleValue `protobuf:"bytes,68,opt,name=class_curr_net_assets_current,json=classCurrNetAssetsCurrent,proto3" json:"class_curr_net_assets_current,omitempty"`
	// Net assets ()
	NetAssets *wrapperspb.DoubleValue `protobuf:"bytes,69,opt,name=net_assets,json=netAssets,proto3" json:"net_assets,omitempty"`
	// Account base currency ()
	AccountBaseCurrency string `protobuf:"bytes,70,opt,name=account_base_currency,json=accountBaseCurrency,proto3" json:"account_base_currency,omitempty"`
	// UK security value offer ()
	UkSecurityValueOffer *wrapperspb.DoubleValue `protobuf:"bytes,71,opt,name=uk_security_value_offer,json=ukSecurityValueOffer,proto3" json:"uk_security_value_offer,omitempty"`
	// Units in issue total ()
	UnitsInIssueTotal *wrapperspb.DoubleValue `protobuf:"bytes,72,opt,name=units_in_issue_total,json=unitsInIssueTotal,proto3" json:"units_in_issue_total,omitempty"`
	// Income collected during the period ()
	IncomeCollectedDuringPeriod *wrapperspb.DoubleValue `protobuf:"bytes,73,opt,name=income_collected_during_period,json=incomeCollectedDuringPeriod,proto3" json:"income_collected_during_period,omitempty"`
	// Creation value ()
	CreationValue *wrapperspb.DoubleValue `protobuf:"bytes,74,opt,name=creation_value,json=creationValue,proto3" json:"creation_value,omitempty"`
	// Class current redemptions (local) ()
	ClassCurrRedemptionsLocal *wrapperspb.DoubleValue `protobuf:"bytes,75,opt,name=class_curr_redemptions_local,json=classCurrRedemptionsLocal,proto3" json:"class_curr_redemptions_local,omitempty"`
	// Class current subscriptions (local) ()
	ClassCurrSubscriptionsLocal *wrapperspb.DoubleValue `protobuf:"bytes,76,opt,name=class_curr_subscriptions_local,json=classCurrSubscriptionsLocal,proto3" json:"class_curr_subscriptions_local,omitempty"`
	// Class current equalization rate (local) ()
	ClassCurrEqualizationRateLocal *wrapperspb.DoubleValue `protobuf:"bytes,77,opt,name=class_curr_equalization_rate_local,json=classCurrEqualizationRateLocal,proto3" json:"class_curr_equalization_rate_local,omitempty"`
	// Class current income rate (local) ()
	ClassCurrIncomeRateLocal *wrapperspb.DoubleValue `protobuf:"bytes,78,opt,name=class_curr_income_rate_local,json=classCurrIncomeRateLocal,proto3" json:"class_curr_income_rate_local,omitempty"`
	// Account base country ()
	AccountBaseCountry string `protobuf:"bytes,79,opt,name=account_base_country,json=accountBaseCountry,proto3" json:"account_base_country,omitempty"`
	// Unrealized exchange gain/loss ()
	UnrealizedExchangeGl *wrapperspb.DoubleValue `protobuf:"bytes,80,opt,name=unrealized_exchange_gl,json=unrealizedExchangeGl,proto3" json:"unrealized_exchange_gl,omitempty"`
	// Unrealized security gain/loss
	UnrealSecurityGainloss *wrapperspb.DoubleValue `protobuf:"bytes,81,opt,name=unreal_security_gainloss,json=unrealSecurityGainloss,proto3" json:"unreal_security_gainloss,omitempty"`
	// Unrealized FX gain/loss (receivable/payable)
	UnrealizedFxGlRecvblpaybl *wrapperspb.DoubleValue `protobuf:"bytes,82,opt,name=unrealized_fx_gl_recvblpaybl,json=unrealizedFxGlRecvblpaybl,proto3" json:"unrealized_fx_gl_recvblpaybl,omitempty"`
	// Class currency unrealized FX gain/loss (prior period)
	ClassCurrencyUnrealFxGlPrior *wrapperspb.DoubleValue `protobuf:"bytes,83,opt,name=class_currency_unreal_fx_gl_prior,json=classCurrencyUnrealFxGlPrior,proto3" json:"class_currency_unreal_fx_gl_prior,omitempty"`
	// Class currency unrealized FX gain/loss (current period)
	ClassCurrUnrealFxGlCurrent *wrapperspb.DoubleValue `protobuf:"bytes,84,opt,name=class_curr_unreal_fx_gl_current,json=classCurrUnrealFxGlCurrent,proto3" json:"class_curr_unreal_fx_gl_current,omitempty"`
	// Capital offer price
	CapitalOfferPrice *wrapperspb.DoubleValue `protobuf:"bytes,85,opt,name=capital_offer_price,json=capitalOfferPrice,proto3" json:"capital_offer_price,omitempty"`
	// Account sub-type
	AccountSubType string `protobuf:"bytes,86,opt,name=account_sub_type,json=accountSubType,proto3" json:"account_sub_type,omitempty"`
	// Prior creation amount
	PriorCreationAmt *wrapperspb.DoubleValue `protobuf:"bytes,87,opt,name=prior_creation_amt,json=priorCreationAmt,proto3" json:"prior_creation_amt,omitempty"`
	// Prior creation price
	PriorCreationPrice *wrapperspb.DoubleValue `protobuf:"bytes,88,opt,name=prior_creation_price,json=priorCreationPrice,proto3" json:"prior_creation_price,omitempty"`
	// Report account short name
	ReportAcctShortName string `protobuf:"bytes,89,opt,name=report_acct_short_name,json=reportAcctShortName,proto3" json:"report_acct_short_name,omitempty"`
	// NAV with 8 decimal places
	NavPrev_8Decimals *wrapperspb.DoubleValue `protobuf:"bytes,90,opt,name=nav_prev_8_decimals,json=navPrev8Decimals,proto3" json:"nav_prev_8_decimals,omitempty"`
	// Prior valuation date
	PriorValuationDate *date.Date `protobuf:"bytes,91,opt,name=prior_valuation_date,json=priorValuationDate,proto3" json:"prior_valuation_date,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *APEX_FTRDIST_Record) Reset() {
	*x = APEX_FTRDIST_Record{}
	mi := &file_standards_open_fundholdings_v1_apex_ftrdist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APEX_FTRDIST_Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APEX_FTRDIST_Record) ProtoMessage() {}

func (x *APEX_FTRDIST_Record) ProtoReflect() protoreflect.Message {
	mi := &file_standards_open_fundholdings_v1_apex_ftrdist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APEX_FTRDIST_Record.ProtoReflect.Descriptor instead.
func (*APEX_FTRDIST_Record) Descriptor() ([]byte, []int) {
	return file_standards_open_fundholdings_v1_apex_ftrdist_proto_rawDescGZIP(), []int{0, 0}
}

func (x *APEX_FTRDIST_Record) GetRequestDate() *date.Date {
	if x != nil {
		return x.RequestDate
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *APEX_FTRDIST_Record) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *APEX_FTRDIST_Record) GetAccountVerificationDate() *date.Date {
	if x != nil {
		return x.AccountVerificationDate
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetAccountClass() string {
	if x != nil {
		return x.AccountClass
	}
	return ""
}

func (x *APEX_FTRDIST_Record) GetOeicNetAssets() *wrapperspb.DoubleValue {
	if x != nil {
		return x.OeicNetAssets
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetShareholderEquity() *wrapperspb.DoubleValue {
	if x != nil {
		return x.ShareholderEquity
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetClassOwnershipPercent() *wrapperspb.DoubleValue {
	if x != nil {
		return x.ClassOwnershipPercent
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetClassCurr() string {
	if x != nil {
		return x.ClassCurr
	}
	return ""
}

func (x *APEX_FTRDIST_Record) GetClassCurrNetIncome() *wrapperspb.DoubleValue {
	if x != nil {
		return x.ClassCurrNetIncome
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetQuotedNavForOeicFunds() *wrapperspb.DoubleValue {
	if x != nil {
		return x.QuotedNavForOeicFunds
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetOeicNav() *wrapperspb.DoubleValue {
	if x != nil {
		return x.OeicNav
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetUnitsOutstanding() *wrapperspb.DoubleValue {
	if x != nil {
		return x.UnitsOutstanding
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetTotalAssets() *wrapperspb.DoubleValue {
	if x != nil {
		return x.TotalAssets
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetTotalLiabilities() *wrapperspb.DoubleValue {
	if x != nil {
		return x.TotalLiabilities
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetOeicCapitalValue() *wrapperspb.DoubleValue {
	if x != nil {
		return x.OeicCapitalValue
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetNetIncomeAmount() *wrapperspb.DoubleValue {
	if x != nil {
		return x.NetIncomeAmount
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetUnrealizedGainloss() *wrapperspb.DoubleValue {
	if x != nil {
		return x.UnrealizedGainloss
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetSecurityValue() *wrapperspb.DoubleValue {
	if x != nil {
		return x.SecurityValue
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetCash() *wrapperspb.DoubleValue {
	if x != nil {
		return x.Cash
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetForeignCurrency() *wrapperspb.DoubleValue {
	if x != nil {
		return x.ForeignCurrency
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetAccruedIncome() *wrapperspb.DoubleValue {
	if x != nil {
		return x.AccruedIncome
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetAccruedWithholding() *wrapperspb.DoubleValue {
	if x != nil {
		return x.AccruedWithholding
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetAccruedIncomeNetAccruedWithholding() *wrapperspb.DoubleValue {
	if x != nil {
		return x.AccruedIncomeNetAccruedWithholding
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetReclaimAccrued() *wrapperspb.DoubleValue {
	if x != nil {
		return x.ReclaimAccrued
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetCapitalAssetsReceivable() *wrapperspb.DoubleValue {
	if x != nil {
		return x.CapitalAssetsReceivable
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetCapitalSharesReceivable() *wrapperspb.DoubleValue {
	if x != nil {
		return x.CapitalSharesReceivable
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetCurrencyRecvLessForwards() *wrapperspb.DoubleValue {
	if x != nil {
		return x.CurrencyRecvLessForwards
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetSpotReceivable() *wrapperspb.DoubleValue {
	if x != nil {
		return x.SpotReceivable
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetSecuritiesSoldReceivable() *wrapperspb.DoubleValue {
	if x != nil {
		return x.SecuritiesSoldReceivable
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetReclaimReceivableNetAccrued() *wrapperspb.DoubleValue {
	if x != nil {
		return x.ReclaimReceivableNetAccrued
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetCurrencyShortIncomeRecv() *wrapperspb.DoubleValue {
	if x != nil {
		return x.CurrencyShortIncomeRecv
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetCurrencyShortSaleRecv() *wrapperspb.DoubleValue {
	if x != nil {
		return x.CurrencyShortSaleRecv
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetUnrealizedGainOnFec() *wrapperspb.DoubleValue {
	if x != nil {
		return x.UnrealizedGainOnFec
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetVariationMarginsReceivable() *wrapperspb.DoubleValue {
	if x != nil {
		return x.VariationMarginsReceivable
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetOtherReceivablesTrue() *wrapperspb.DoubleValue {
	if x != nil {
		return x.OtherReceivablesTrue
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetFuturesApprecdeprec() *wrapperspb.DoubleValue {
	if x != nil {
		return x.FuturesApprecdeprec
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetFuturesApprecdeprecTrans() *wrapperspb.DoubleValue {
	if x != nil {
		return x.FuturesApprecdeprecTrans
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetMarginDeposits() *wrapperspb.DoubleValue {
	if x != nil {
		return x.MarginDeposits
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetAccruedExpense() *wrapperspb.DoubleValue {
	if x != nil {
		return x.AccruedExpense
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetPrepaidExpense() *wrapperspb.DoubleValue {
	if x != nil {
		return x.PrepaidExpense
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetExpensesPaidDuringPeriod() *wrapperspb.DoubleValue {
	if x != nil {
		return x.ExpensesPaidDuringPeriod
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetFundTotalClassSpecificExpCurr() *wrapperspb.DoubleValue {
	if x != nil {
		return x.FundTotalClassSpecificExpCurr
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetVariationMarginsPositions() *wrapperspb.DoubleValue {
	if x != nil {
		return x.VariationMarginsPositions
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetVariationMarginsAssetsTransactions() *wrapperspb.DoubleValue {
	if x != nil {
		return x.VariationMarginsAssetsTransactions
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetOtherAssetsTrue() *wrapperspb.DoubleValue {
	if x != nil {
		return x.OtherAssetsTrue
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetOtherPayables() *wrapperspb.DoubleValue {
	if x != nil {
		return x.OtherPayables
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetOtherReceivables() *wrapperspb.DoubleValue {
	if x != nil {
		return x.OtherReceivables
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetAccruedCapitalExpense() *wrapperspb.DoubleValue {
	if x != nil {
		return x.AccruedCapitalExpense
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetBrokerCommissionsPayable() *wrapperspb.DoubleValue {
	if x != nil {
		return x.BrokerCommissionsPayable
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetCapitalGainsPayable() *wrapperspb.DoubleValue {
	if x != nil {
		return x.CapitalGainsPayable
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetCapitalAssetsPayable() *wrapperspb.DoubleValue {
	if x != nil {
		return x.CapitalAssetsPayable
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetTotalInflatCompEarned() *wrapperspb.DoubleValue {
	if x != nil {
		return x.TotalInflatCompEarned
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetCapitalSharesPayable() *wrapperspb.DoubleValue {
	if x != nil {
		return x.CapitalSharesPayable
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetCurrencyPayableLessForwards() *wrapperspb.DoubleValue {
	if x != nil {
		return x.CurrencyPayableLessForwards
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetSpotPayable() *wrapperspb.DoubleValue {
	if x != nil {
		return x.SpotPayable
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetIncomePayable() *wrapperspb.DoubleValue {
	if x != nil {
		return x.IncomePayable
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetSecuritiesPurchasedPayable() *wrapperspb.DoubleValue {
	if x != nil {
		return x.SecuritiesPurchasedPayable
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetUnrealizedLossOnFec() *wrapperspb.DoubleValue {
	if x != nil {
		return x.UnrealizedLossOnFec
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetVariationMarginsPayable() *wrapperspb.DoubleValue {
	if x != nil {
		return x.VariationMarginsPayable
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetOtherPayablesTrue() *wrapperspb.DoubleValue {
	if x != nil {
		return x.OtherPayablesTrue
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetShortSctyMarket() *wrapperspb.DoubleValue {
	if x != nil {
		return x.ShortSctyMarket
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetValuationPeriodEndDate() *date.Date {
	if x != nil {
		return x.ValuationPeriodEndDate
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetFullOfferValuation() *wrapperspb.DoubleValue {
	if x != nil {
		return x.FullOfferValuation
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetRoundedMidPrice() *wrapperspb.DoubleValue {
	if x != nil {
		return x.RoundedMidPrice
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetOeicQuotedNav() *wrapperspb.DoubleValue {
	if x != nil {
		return x.OeicQuotedNav
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetClassCurrNav() *wrapperspb.DoubleValue {
	if x != nil {
		return x.ClassCurrNav
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetClassCurrNetAssetsCurrent() *wrapperspb.DoubleValue {
	if x != nil {
		return x.ClassCurrNetAssetsCurrent
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetNetAssets() *wrapperspb.DoubleValue {
	if x != nil {
		return x.NetAssets
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetAccountBaseCurrency() string {
	if x != nil {
		return x.AccountBaseCurrency
	}
	return ""
}

func (x *APEX_FTRDIST_Record) GetUkSecurityValueOffer() *wrapperspb.DoubleValue {
	if x != nil {
		return x.UkSecurityValueOffer
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetUnitsInIssueTotal() *wrapperspb.DoubleValue {
	if x != nil {
		return x.UnitsInIssueTotal
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetIncomeCollectedDuringPeriod() *wrapperspb.DoubleValue {
	if x != nil {
		return x.IncomeCollectedDuringPeriod
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetCreationValue() *wrapperspb.DoubleValue {
	if x != nil {
		return x.CreationValue
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetClassCurrRedemptionsLocal() *wrapperspb.DoubleValue {
	if x != nil {
		return x.ClassCurrRedemptionsLocal
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetClassCurrSubscriptionsLocal() *wrapperspb.DoubleValue {
	if x != nil {
		return x.ClassCurrSubscriptionsLocal
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetClassCurrEqualizationRateLocal() *wrapperspb.DoubleValue {
	if x != nil {
		return x.ClassCurrEqualizationRateLocal
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetClassCurrIncomeRateLocal() *wrapperspb.DoubleValue {
	if x != nil {
		return x.ClassCurrIncomeRateLocal
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetAccountBaseCountry() string {
	if x != nil {
		return x.AccountBaseCountry
	}
	return ""
}

func (x *APEX_FTRDIST_Record) GetUnrealizedExchangeGl() *wrapperspb.DoubleValue {
	if x != nil {
		return x.UnrealizedExchangeGl
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetUnrealSecurityGainloss() *wrapperspb.DoubleValue {
	if x != nil {
		return x.UnrealSecurityGainloss
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetUnrealizedFxGlRecvblpaybl() *wrapperspb.DoubleValue {
	if x != nil {
		return x.UnrealizedFxGlRecvblpaybl
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetClassCurrencyUnrealFxGlPrior() *wrapperspb.DoubleValue {
	if x != nil {
		return x.ClassCurrencyUnrealFxGlPrior
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetClassCurrUnrealFxGlCurrent() *wrapperspb.DoubleValue {
	if x != nil {
		return x.ClassCurrUnrealFxGlCurrent
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetCapitalOfferPrice() *wrapperspb.DoubleValue {
	if x != nil {
		return x.CapitalOfferPrice
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetAccountSubType() string {
	if x != nil {
		return x.AccountSubType
	}
	return ""
}

func (x *APEX_FTRDIST_Record) GetPriorCreationAmt() *wrapperspb.DoubleValue {
	if x != nil {
		return x.PriorCreationAmt
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetPriorCreationPrice() *wrapperspb.DoubleValue {
	if x != nil {
		return x.PriorCreationPrice
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetReportAcctShortName() string {
	if x != nil {
		return x.ReportAcctShortName
	}
	return ""
}

func (x *APEX_FTRDIST_Record) GetNavPrev_8Decimals() *wrapperspb.DoubleValue {
	if x != nil {
		return x.NavPrev_8Decimals
	}
	return nil
}

func (x *APEX_FTRDIST_Record) GetPriorValuationDate() *date.Date {
	if x != nil {
		return x.PriorValuationDate
	}
	return nil
}

var File_standards_open_fundholdings_v1_apex_ftrdist_proto protoreflect.FileDescriptor

const file_standards_open_fundholdings_v1_apex_ftrdist_proto_rawDesc = "" +
	"\n" +
	"1standards/open/fundholdings/v1/apex_ftrdist.proto\x12\x1estandards.open.fundholdings.v1\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x16google/type/date.proto\"\x969\n" +
	"\fAPEX_FTRDIST\x128\n" +
	"\x0eeffective_date\x18\x01 \x01(\v2\x11.google.type.DateR\reffectiveDate\x12M\n" +
	"\arecords\x18\x02 \x03(\v23.standards.open.fundholdings.v1.APEX_FTRDIST.RecordR\arecords\x1a\xfc7\n" +
	"\x06Record\x124\n" +
	"\frequest_date\x18\x01 \x01(\v2\x11.google.type.DateR\vrequestDate\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\tR\raccountNumber\x12!\n" +
	"\faccount_name\x18\x03 \x01(\tR\vaccountName\x12M\n" +
	"\x19account_verification_date\x18\x04 \x01(\v2\x11.google.type.DateR\x17accountVerificationDate\x12#\n" +
	"\raccount_class\x18\x05 \x01(\tR\faccountClass\x12D\n" +
	"\x0foeic_net_assets\x18\x06 \x01(\v2\x1c.google.protobuf.DoubleValueR\roeicNetAssets\x12K\n" +
	"\x12shareholder_equity\x18\a \x01(\v2\x1c.google.protobuf.DoubleValueR\x11shareholderEquity\x12T\n" +
	"\x17class_ownership_percent\x18\b \x01(\v2\x1c.google.protobuf.DoubleValueR\x15classOwnershipPercent\x12\x1d\n" +
	"\n" +
	"class_curr\x18\t \x01(\tR\tclassCurr\x12O\n" +
	"\x15class_curr_net_income\x18\n" +
	" \x01(\v2\x1c.google.protobuf.DoubleValueR\x12classCurrNetIncome\x12V\n" +
	"\x19quoted_nav_for_oeic_funds\x18\v \x01(\v2\x1c.google.protobuf.DoubleValueR\x15quotedNavForOeicFunds\x127\n" +
	"\boeic_nav\x18\f \x01(\v2\x1c.google.protobuf.DoubleValueR\aoeicNav\x12I\n" +
	"\x11units_outstanding\x18\r \x01(\v2\x1c.google.protobuf.DoubleValueR\x10unitsOutstanding\x12?\n" +
	"\ftotal_assets\x18\x0e \x01(\v2\x1c.google.protobuf.DoubleValueR\vtotalAssets\x12I\n" +
	"\x11total_liabilities\x18\x0f \x01(\v2\x1c.google.protobuf.DoubleValueR\x10totalLiabilities\x12J\n" +
	"\x12oeic_capital_value\x18\x10 \x01(\v2\x1c.google.protobuf.DoubleValueR\x10oeicCapitalValue\x12H\n" +
	"\x11net_income_amount\x18\x11 \x01(\v2\x1c.google.protobuf.DoubleValueR\x0fnetIncomeAmount\x12M\n" +
	"\x13unrealized_gainloss\x18\x12 \x01(\v2\x1c.google.protobuf.DoubleValueR\x12unrealizedGainloss\x12C\n" +
	"\x0esecurity_value\x18\x13 \x01(\v2\x1c.google.protobuf.DoubleValueR\rsecurityValue\x120\n" +
	"\x04cash\x18\x14 \x01(\v2\x1c.google.protobuf.DoubleValueR\x04cash\x12G\n" +
	"\x10foreign_currency\x18\x15 \x01(\v2\x1c.google.protobuf.DoubleValueR\x0fforeignCurrency\x12C\n" +
	"\x0eaccrued_income\x18\x16 \x01(\v2\x1c.google.protobuf.DoubleValueR\raccruedIncome\x12M\n" +
	"\x13accrued_withholding\x18\x17 \x01(\v2\x1c.google.protobuf.DoubleValueR\x12accruedWithholding\x12p\n" +
	"&accrued_income_net_accrued_withholding\x18\x18 \x01(\v2\x1c.google.protobuf.DoubleValueR\"accruedIncomeNetAccruedWithholding\x12E\n" +
	"\x0freclaim_accrued\x18\x19 \x01(\v2\x1c.google.protobuf.DoubleValueR\x0ereclaimAccrued\x12X\n" +
	"\x19capital_assets_receivable\x18\x1a \x01(\v2\x1c.google.protobuf.DoubleValueR\x17capitalAssetsReceivable\x12X\n" +
	"\x19capital_shares_receivable\x18\x1b \x01(\v2\x1c.google.protobuf.DoubleValueR\x17capitalSharesReceivable\x12[\n" +
	"\x1bcurrency_recv_less_forwards\x18\x1c \x01(\v2\x1c.google.protobuf.DoubleValueR\x18currencyRecvLessForwards\x12E\n" +
	"\x0fspot_receivable\x18\x1d \x01(\v2\x1c.google.protobuf.DoubleValueR\x0espotReceivable\x12Z\n" +
	"\x1asecurities_sold_receivable\x18\x1e \x01(\v2\x1c.google.protobuf.DoubleValueR\x18securitiesSoldReceivable\x12a\n" +
	"\x1ereclaim_receivable_net_accrued\x18\x1f \x01(\v2\x1c.google.protobuf.DoubleValueR\x1breclaimReceivableNetAccrued\x12Y\n" +
	"\x1acurrency_short_income_recv\x18  \x01(\v2\x1c.google.protobuf.DoubleValueR\x17currencyShortIncomeRecv\x12U\n" +
	"\x18currency_short_sale_recv\x18! \x01(\v2\x1c.google.protobuf.DoubleValueR\x15currencyShortSaleRecv\x12Q\n" +
	"\x16unrealized_gain_on_fec\x18\" \x01(\v2\x1c.google.protobuf.DoubleValueR\x13unrealizedGainOnFec\x12^\n" +
	"\x1cvariation_margins_receivable\x18# \x01(\v2\x1c.google.protobuf.DoubleValueR\x1avariationMarginsReceivable\x12R\n" +
	"\x16other_receivables_true\x18$ \x01(\v2\x1c.google.protobuf.DoubleValueR\x14otherReceivablesTrue\x12O\n" +
	"\x14futures_apprecdeprec\x18% \x01(\v2\x1c.google.protobuf.DoubleValueR\x13futuresApprecdeprec\x12Z\n" +
	"\x1afutures_apprecdeprec_trans\x18& \x01(\v2\x1c.google.protobuf.DoubleValueR\x18futuresApprecdeprecTrans\x12E\n" +
	"\x0fmargin_deposits\x18' \x01(\v2\x1c.google.protobuf.DoubleValueR\x0emarginDeposits\x12E\n" +
	"\x0faccrued_expense\x18( \x01(\v2\x1c.google.protobuf.DoubleValueR\x0eaccruedExpense\x12E\n" +
	"\x0fprepaid_expense\x18) \x01(\v2\x1c.google.protobuf.DoubleValueR\x0eprepaidExpense\x12[\n" +
	"\x1bexpenses_paid_during_period\x18* \x01(\v2\x1c.google.protobuf.DoubleValueR\x18expensesPaidDuringPeriod\x12g\n" +
	"\"fund_total_class_specific_exp_curr\x18+ \x01(\v2\x1c.google.protobuf.DoubleValueR\x1dfundTotalClassSpecificExpCurr\x12\\\n" +
	"\x1bvariation_margins_positions\x18, \x01(\v2\x1c.google.protobuf.DoubleValueR\x19variationMarginsPositions\x12o\n" +
	"%variation_margins_assets_transactions\x18- \x01(\v2\x1c.google.protobuf.DoubleValueR\"variationMarginsAssetsTransactions\x12H\n" +
	"\x11other_assets_true\x18. \x01(\v2\x1c.google.protobuf.DoubleValueR\x0fotherAssetsTrue\x12C\n" +
	"\x0eother_payables\x18/ \x01(\v2\x1c.google.protobuf.DoubleValueR\rotherPayables\x12I\n" +
	"\x11other_receivables\x180 \x01(\v2\x1c.google.protobuf.DoubleValueR\x10otherReceivables\x12T\n" +
	"\x17accrued_capital_expense\x181 \x01(\v2\x1c.google.protobuf.DoubleValueR\x15accruedCapitalExpense\x12Z\n" +
	"\x1abroker_commissions_payable\x182 \x01(\v2\x1c.google.protobuf.DoubleValueR\x18brokerCommissionsPayable\x12P\n" +
	"\x15capital_gains_payable\x183 \x01(\v2\x1c.google.protobuf.DoubleValueR\x13capitalGainsPayable\x12R\n" +
	"\x16capital_assets_payable\x184 \x01(\v2\x1c.google.protobuf.DoubleValueR\x14capitalAssetsPayable\x12U\n" +
	"\x18total_inflat_comp_earned\x185 \x01(\v2\x1c.google.protobuf.DoubleValueR\x15totalInflatCompEarned\x12R\n" +
	"\x16capital_shares_payable\x186 \x01(\v2\x1c.google.protobuf.DoubleValueR\x14capitalSharesPayable\x12a\n" +
	"\x1ecurrency_payable_less_forwards\x187 \x01(\v2\x1c.google.protobuf.DoubleValueR\x1bcurrencyPayableLessForwards\x12?\n" +
	"\fspot_payable\x188 \x01(\v2\x1c.google.protobuf.DoubleValueR\vspotPayable\x12C\n" +
	"\x0eincome_payable\x189 \x01(\v2\x1c.google.protobuf.DoubleValueR\rincomePayable\x12^\n" +
	"\x1csecurities_purchased_payable\x18: \x01(\v2\x1c.google.protobuf.DoubleValueR\x1asecuritiesPurchasedPayable\x12Q\n" +
	"\x16unrealized_loss_on_fec\x18; \x01(\v2\x1c.google.protobuf.DoubleValueR\x13unrealizedLossOnFec\x12X\n" +
	"\x19variation_margins_payable\x18< \x01(\v2\x1c.google.protobuf.DoubleValueR\x17variationMarginsPayable\x12L\n" +
	"\x13other_payables_true\x18= \x01(\v2\x1c.google.protobuf.DoubleValueR\x11otherPayablesTrue\x12H\n" +
	"\x11short_scty_market\x18> \x01(\v2\x1c.google.protobuf.DoubleValueR\x0fshortSctyMarket\x12L\n" +
	"\x19valuation_period_end_date\x18? \x01(\v2\x11.google.type.DateR\x16valuationPeriodEndDate\x12N\n" +
	"\x14full_offer_valuation\x18@ \x01(\v2\x1c.google.protobuf.DoubleValueR\x12fullOfferValuation\x12H\n" +
	"\x11rounded_mid_price\x18A \x01(\v2\x1c.google.protobuf.DoubleValueR\x0froundedMidPrice\x12D\n" +
	"\x0foeic_quoted_nav\x18B \x01(\v2\x1c.google.protobuf.DoubleValueR\roeicQuotedNav\x12B\n" +
	"\x0eclass_curr_nav\x18C \x01(\v2\x1c.google.protobuf.DoubleValueR\fclassCurrNav\x12^\n" +
	"\x1dclass_curr_net_assets_current\x18D \x01(\v2\x1c.google.protobuf.DoubleValueR\x19classCurrNetAssetsCurrent\x12;\n" +
	"\n" +
	"net_assets\x18E \x01(\v2\x1c.google.protobuf.DoubleValueR\tnetAssets\x122\n" +
	"\x15account_base_currency\x18F \x01(\tR\x13accountBaseCurrency\x12S\n" +
	"\x17uk_security_value_offer\x18G \x01(\v2\x1c.google.protobuf.DoubleValueR\x14ukSecurityValueOffer\x12M\n" +
	"\x14units_in_issue_total\x18H \x01(\v2\x1c.google.protobuf.DoubleValueR\x11unitsInIssueTotal\x12a\n" +
	"\x1eincome_collected_during_period\x18I \x01(\v2\x1c.google.protobuf.DoubleValueR\x1bincomeCollectedDuringPeriod\x12C\n" +
	"\x0ecreation_value\x18J \x01(\v2\x1c.google.protobuf.DoubleValueR\rcreationValue\x12]\n" +
	"\x1cclass_curr_redemptions_local\x18K \x01(\v2\x1c.google.protobuf.DoubleValueR\x19classCurrRedemptionsLocal\x12a\n" +
	"\x1eclass_curr_subscriptions_local\x18L \x01(\v2\x1c.google.protobuf.DoubleValueR\x1bclassCurrSubscriptionsLocal\x12h\n" +
	"\"class_curr_equalization_rate_local\x18M \x01(\v2\x1c.google.protobuf.DoubleValueR\x1eclassCurrEqualizationRateLocal\x12\\\n" +
	"\x1cclass_curr_income_rate_local\x18N \x01(\v2\x1c.google.protobuf.DoubleValueR\x18classCurrIncomeRateLocal\x120\n" +
	"\x14account_base_country\x18O \x01(\tR\x12accountBaseCountry\x12R\n" +
	"\x16unrealized_exchange_gl\x18P \x01(\v2\x1c.google.protobuf.DoubleValueR\x14unrealizedExchangeGl\x12V\n" +
	"\x18unreal_security_gainloss\x18Q \x01(\v2\x1c.google.protobuf.DoubleValueR\x16unrealSecurityGainloss\x12]\n" +
	"\x1cunrealized_fx_gl_recvblpaybl\x18R \x01(\v2\x1c.google.protobuf.DoubleValueR\x19unrealizedFxGlRecvblpaybl\x12e\n" +
	"!class_currency_unreal_fx_gl_prior\x18S \x01(\v2\x1c.google.protobuf.DoubleValueR\x1cclassCurrencyUnrealFxGlPrior\x12a\n" +
	"\x1fclass_curr_unreal_fx_gl_current\x18T \x01(\v2\x1c.google.protobuf.DoubleValueR\x1aclassCurrUnrealFxGlCurrent\x12L\n" +
	"\x13capital_offer_price\x18U \x01(\v2\x1c.google.protobuf.DoubleValueR\x11capitalOfferPrice\x12(\n" +
	"\x10account_sub_type\x18V \x01(\tR\x0eaccountSubType\x12J\n" +
	"\x12prior_creation_amt\x18W \x01(\v2\x1c.google.protobuf.DoubleValueR\x10priorCreationAmt\x12N\n" +
	"\x14prior_creation_price\x18X \x01(\v2\x1c.google.protobuf.DoubleValueR\x12priorCreationPrice\x123\n" +
	"\x16report_acct_short_name\x18Y \x01(\tR\x13reportAcctShortName\x12K\n" +
	"\x13nav_prev_8_decimals\x18Z \x01(\v2\x1c.google.protobuf.DoubleValueR\x10navPrev8Decimals\x12C\n" +
	"\x14prior_valuation_date\x18[ \x01(\v2\x11.google.type.DateR\x12priorValuationDateB5Z3go.alis.build/common/standards/open/fundholdings/v1b\x06proto3"

var (
	file_standards_open_fundholdings_v1_apex_ftrdist_proto_rawDescOnce sync.Once
	file_standards_open_fundholdings_v1_apex_ftrdist_proto_rawDescData []byte
)

func file_standards_open_fundholdings_v1_apex_ftrdist_proto_rawDescGZIP() []byte {
	file_standards_open_fundholdings_v1_apex_ftrdist_proto_rawDescOnce.Do(func() {
		file_standards_open_fundholdings_v1_apex_ftrdist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_standards_open_fundholdings_v1_apex_ftrdist_proto_rawDesc), len(file_standards_open_fundholdings_v1_apex_ftrdist_proto_rawDesc)))
	})
	return file_standards_open_fundholdings_v1_apex_ftrdist_proto_rawDescData
}

var file_standards_open_fundholdings_v1_apex_ftrdist_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_standards_open_fundholdings_v1_apex_ftrdist_proto_goTypes = []any{
	(*APEX_FTRDIST)(nil),           // 0: standards.open.fundholdings.v1.APEX_FTRDIST
	(*APEX_FTRDIST_Record)(nil),    // 1: standards.open.fundholdings.v1.APEX_FTRDIST.Record
	(*date.Date)(nil),              // 2: google.type.Date
	(*wrapperspb.DoubleValue)(nil), // 3: google.protobuf.DoubleValue
}
var file_standards_open_fundholdings_v1_apex_ftrdist_proto_depIdxs = []int32{
	2,  // 0: standards.open.fundholdings.v1.APEX_FTRDIST.effective_date:type_name -> google.type.Date
	1,  // 1: standards.open.fundholdings.v1.APEX_FTRDIST.records:type_name -> standards.open.fundholdings.v1.APEX_FTRDIST.Record
	2,  // 2: standards.open.fundholdings.v1.APEX_FTRDIST.Record.request_date:type_name -> google.type.Date
	2,  // 3: standards.open.fundholdings.v1.APEX_FTRDIST.Record.account_verification_date:type_name -> google.type.Date
	3,  // 4: standards.open.fundholdings.v1.APEX_FTRDIST.Record.oeic_net_assets:type_name -> google.protobuf.DoubleValue
	3,  // 5: standards.open.fundholdings.v1.APEX_FTRDIST.Record.shareholder_equity:type_name -> google.protobuf.DoubleValue
	3,  // 6: standards.open.fundholdings.v1.APEX_FTRDIST.Record.class_ownership_percent:type_name -> google.protobuf.DoubleValue
	3,  // 7: standards.open.fundholdings.v1.APEX_FTRDIST.Record.class_curr_net_income:type_name -> google.protobuf.DoubleValue
	3,  // 8: standards.open.fundholdings.v1.APEX_FTRDIST.Record.quoted_nav_for_oeic_funds:type_name -> google.protobuf.DoubleValue
	3,  // 9: standards.open.fundholdings.v1.APEX_FTRDIST.Record.oeic_nav:type_name -> google.protobuf.DoubleValue
	3,  // 10: standards.open.fundholdings.v1.APEX_FTRDIST.Record.units_outstanding:type_name -> google.protobuf.DoubleValue
	3,  // 11: standards.open.fundholdings.v1.APEX_FTRDIST.Record.total_assets:type_name -> google.protobuf.DoubleValue
	3,  // 12: standards.open.fundholdings.v1.APEX_FTRDIST.Record.total_liabilities:type_name -> google.protobuf.DoubleValue
	3,  // 13: standards.open.fundholdings.v1.APEX_FTRDIST.Record.oeic_capital_value:type_name -> google.protobuf.DoubleValue
	3,  // 14: standards.open.fundholdings.v1.APEX_FTRDIST.Record.net_income_amount:type_name -> google.protobuf.DoubleValue
	3,  // 15: standards.open.fundholdings.v1.APEX_FTRDIST.Record.unrealized_gainloss:type_name -> google.protobuf.DoubleValue
	3,  // 16: standards.open.fundholdings.v1.APEX_FTRDIST.Record.security_value:type_name -> google.protobuf.DoubleValue
	3,  // 17: standards.open.fundholdings.v1.APEX_FTRDIST.Record.cash:type_name -> google.protobuf.DoubleValue
	3,  // 18: standards.open.fundholdings.v1.APEX_FTRDIST.Record.foreign_currency:type_name -> google.protobuf.DoubleValue
	3,  // 19: standards.open.fundholdings.v1.APEX_FTRDIST.Record.accrued_income:type_name -> google.protobuf.DoubleValue
	3,  // 20: standards.open.fundholdings.v1.APEX_FTRDIST.Record.accrued_withholding:type_name -> google.protobuf.DoubleValue
	3,  // 21: standards.open.fundholdings.v1.APEX_FTRDIST.Record.accrued_income_net_accrued_withholding:type_name -> google.protobuf.DoubleValue
	3,  // 22: standards.open.fundholdings.v1.APEX_FTRDIST.Record.reclaim_accrued:type_name -> google.protobuf.DoubleValue
	3,  // 23: standards.open.fundholdings.v1.APEX_FTRDIST.Record.capital_assets_receivable:type_name -> google.protobuf.DoubleValue
	3,  // 24: standards.open.fundholdings.v1.APEX_FTRDIST.Record.capital_shares_receivable:type_name -> google.protobuf.DoubleValue
	3,  // 25: standards.open.fundholdings.v1.APEX_FTRDIST.Record.currency_recv_less_forwards:type_name -> google.protobuf.DoubleValue
	3,  // 26: standards.open.fundholdings.v1.APEX_FTRDIST.Record.spot_receivable:type_name -> google.protobuf.DoubleValue
	3,  // 27: standards.open.fundholdings.v1.APEX_FTRDIST.Record.securities_sold_receivable:type_name -> google.protobuf.DoubleValue
	3,  // 28: standards.open.fundholdings.v1.APEX_FTRDIST.Record.reclaim_receivable_net_accrued:type_name -> google.protobuf.DoubleValue
	3,  // 29: standards.open.fundholdings.v1.APEX_FTRDIST.Record.currency_short_income_recv:type_name -> google.protobuf.DoubleValue
	3,  // 30: standards.open.fundholdings.v1.APEX_FTRDIST.Record.currency_short_sale_recv:type_name -> google.protobuf.DoubleValue
	3,  // 31: standards.open.fundholdings.v1.APEX_FTRDIST.Record.unrealized_gain_on_fec:type_name -> google.protobuf.DoubleValue
	3,  // 32: standards.open.fundholdings.v1.APEX_FTRDIST.Record.variation_margins_receivable:type_name -> google.protobuf.DoubleValue
	3,  // 33: standards.open.fundholdings.v1.APEX_FTRDIST.Record.other_receivables_true:type_name -> google.protobuf.DoubleValue
	3,  // 34: standards.open.fundholdings.v1.APEX_FTRDIST.Record.futures_apprecdeprec:type_name -> google.protobuf.DoubleValue
	3,  // 35: standards.open.fundholdings.v1.APEX_FTRDIST.Record.futures_apprecdeprec_trans:type_name -> google.protobuf.DoubleValue
	3,  // 36: standards.open.fundholdings.v1.APEX_FTRDIST.Record.margin_deposits:type_name -> google.protobuf.DoubleValue
	3,  // 37: standards.open.fundholdings.v1.APEX_FTRDIST.Record.accrued_expense:type_name -> google.protobuf.DoubleValue
	3,  // 38: standards.open.fundholdings.v1.APEX_FTRDIST.Record.prepaid_expense:type_name -> google.protobuf.DoubleValue
	3,  // 39: standards.open.fundholdings.v1.APEX_FTRDIST.Record.expenses_paid_during_period:type_name -> google.protobuf.DoubleValue
	3,  // 40: standards.open.fundholdings.v1.APEX_FTRDIST.Record.fund_total_class_specific_exp_curr:type_name -> google.protobuf.DoubleValue
	3,  // 41: standards.open.fundholdings.v1.APEX_FTRDIST.Record.variation_margins_positions:type_name -> google.protobuf.DoubleValue
	3,  // 42: standards.open.fundholdings.v1.APEX_FTRDIST.Record.variation_margins_assets_transactions:type_name -> google.protobuf.DoubleValue
	3,  // 43: standards.open.fundholdings.v1.APEX_FTRDIST.Record.other_assets_true:type_name -> google.protobuf.DoubleValue
	3,  // 44: standards.open.fundholdings.v1.APEX_FTRDIST.Record.other_payables:type_name -> google.protobuf.DoubleValue
	3,  // 45: standards.open.fundholdings.v1.APEX_FTRDIST.Record.other_receivables:type_name -> google.protobuf.DoubleValue
	3,  // 46: standards.open.fundholdings.v1.APEX_FTRDIST.Record.accrued_capital_expense:type_name -> google.protobuf.DoubleValue
	3,  // 47: standards.open.fundholdings.v1.APEX_FTRDIST.Record.broker_commissions_payable:type_name -> google.protobuf.DoubleValue
	3,  // 48: standards.open.fundholdings.v1.APEX_FTRDIST.Record.capital_gains_payable:type_name -> google.protobuf.DoubleValue
	3,  // 49: standards.open.fundholdings.v1.APEX_FTRDIST.Record.capital_assets_payable:type_name -> google.protobuf.DoubleValue
	3,  // 50: standards.open.fundholdings.v1.APEX_FTRDIST.Record.total_inflat_comp_earned:type_name -> google.protobuf.DoubleValue
	3,  // 51: standards.open.fundholdings.v1.APEX_FTRDIST.Record.capital_shares_payable:type_name -> google.protobuf.DoubleValue
	3,  // 52: standards.open.fundholdings.v1.APEX_FTRDIST.Record.currency_payable_less_forwards:type_name -> google.protobuf.DoubleValue
	3,  // 53: standards.open.fundholdings.v1.APEX_FTRDIST.Record.spot_payable:type_name -> google.protobuf.DoubleValue
	3,  // 54: standards.open.fundholdings.v1.APEX_FTRDIST.Record.income_payable:type_name -> google.protobuf.DoubleValue
	3,  // 55: standards.open.fundholdings.v1.APEX_FTRDIST.Record.securities_purchased_payable:type_name -> google.protobuf.DoubleValue
	3,  // 56: standards.open.fundholdings.v1.APEX_FTRDIST.Record.unrealized_loss_on_fec:type_name -> google.protobuf.DoubleValue
	3,  // 57: standards.open.fundholdings.v1.APEX_FTRDIST.Record.variation_margins_payable:type_name -> google.protobuf.DoubleValue
	3,  // 58: standards.open.fundholdings.v1.APEX_FTRDIST.Record.other_payables_true:type_name -> google.protobuf.DoubleValue
	3,  // 59: standards.open.fundholdings.v1.APEX_FTRDIST.Record.short_scty_market:type_name -> google.protobuf.DoubleValue
	2,  // 60: standards.open.fundholdings.v1.APEX_FTRDIST.Record.valuation_period_end_date:type_name -> google.type.Date
	3,  // 61: standards.open.fundholdings.v1.APEX_FTRDIST.Record.full_offer_valuation:type_name -> google.protobuf.DoubleValue
	3,  // 62: standards.open.fundholdings.v1.APEX_FTRDIST.Record.rounded_mid_price:type_name -> google.protobuf.DoubleValue
	3,  // 63: standards.open.fundholdings.v1.APEX_FTRDIST.Record.oeic_quoted_nav:type_name -> google.protobuf.DoubleValue
	3,  // 64: standards.open.fundholdings.v1.APEX_FTRDIST.Record.class_curr_nav:type_name -> google.protobuf.DoubleValue
	3,  // 65: standards.open.fundholdings.v1.APEX_FTRDIST.Record.class_curr_net_assets_current:type_name -> google.protobuf.DoubleValue
	3,  // 66: standards.open.fundholdings.v1.APEX_FTRDIST.Record.net_assets:type_name -> google.protobuf.DoubleValue
	3,  // 67: standards.open.fundholdings.v1.APEX_FTRDIST.Record.uk_security_value_offer:type_name -> google.protobuf.DoubleValue
	3,  // 68: standards.open.fundholdings.v1.APEX_FTRDIST.Record.units_in_issue_total:type_name -> google.protobuf.DoubleValue
	3,  // 69: standards.open.fundholdings.v1.APEX_FTRDIST.Record.income_collected_during_period:type_name -> google.protobuf.DoubleValue
	3,  // 70: standards.open.fundholdings.v1.APEX_FTRDIST.Record.creation_value:type_name -> google.protobuf.DoubleValue
	3,  // 71: standards.open.fundholdings.v1.APEX_FTRDIST.Record.class_curr_redemptions_local:type_name -> google.protobuf.DoubleValue
	3,  // 72: standards.open.fundholdings.v1.APEX_FTRDIST.Record.class_curr_subscriptions_local:type_name -> google.protobuf.DoubleValue
	3,  // 73: standards.open.fundholdings.v1.APEX_FTRDIST.Record.class_curr_equalization_rate_local:type_name -> google.protobuf.DoubleValue
	3,  // 74: standards.open.fundholdings.v1.APEX_FTRDIST.Record.class_curr_income_rate_local:type_name -> google.protobuf.DoubleValue
	3,  // 75: standards.open.fundholdings.v1.APEX_FTRDIST.Record.unrealized_exchange_gl:type_name -> google.protobuf.DoubleValue
	3,  // 76: standards.open.fundholdings.v1.APEX_FTRDIST.Record.unreal_security_gainloss:type_name -> google.protobuf.DoubleValue
	3,  // 77: standards.open.fundholdings.v1.APEX_FTRDIST.Record.unrealized_fx_gl_recvblpaybl:type_name -> google.protobuf.DoubleValue
	3,  // 78: standards.open.fundholdings.v1.APEX_FTRDIST.Record.class_currency_unreal_fx_gl_prior:type_name -> google.protobuf.DoubleValue
	3,  // 79: standards.open.fundholdings.v1.APEX_FTRDIST.Record.class_curr_unreal_fx_gl_current:type_name -> google.protobuf.DoubleValue
	3,  // 80: standards.open.fundholdings.v1.APEX_FTRDIST.Record.capital_offer_price:type_name -> google.protobuf.DoubleValue
	3,  // 81: standards.open.fundholdings.v1.APEX_FTRDIST.Record.prior_creation_amt:type_name -> google.protobuf.DoubleValue
	3,  // 82: standards.open.fundholdings.v1.APEX_FTRDIST.Record.prior_creation_price:type_name -> google.protobuf.DoubleValue
	3,  // 83: standards.open.fundholdings.v1.APEX_FTRDIST.Record.nav_prev_8_decimals:type_name -> google.protobuf.DoubleValue
	2,  // 84: standards.open.fundholdings.v1.APEX_FTRDIST.Record.prior_valuation_date:type_name -> google.type.Date
	85, // [85:85] is the sub-list for method output_type
	85, // [85:85] is the sub-list for method input_type
	85, // [85:85] is the sub-list for extension type_name
	85, // [85:85] is the sub-list for extension extendee
	0,  // [0:85] is the sub-list for field type_name
}

func init() { file_standards_open_fundholdings_v1_apex_ftrdist_proto_init() }
func file_standards_open_fundholdings_v1_apex_ftrdist_proto_init() {
	if File_standards_open_fundholdings_v1_apex_ftrdist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_standards_open_fundholdings_v1_apex_ftrdist_proto_rawDesc), len(file_standards_open_fundholdings_v1_apex_ftrdist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_standards_open_fundholdings_v1_apex_ftrdist_proto_goTypes,
		DependencyIndexes: file_standards_open_fundholdings_v1_apex_ftrdist_proto_depIdxs,
		MessageInfos:      file_standards_open_fundholdings_v1_apex_ftrdist_proto_msgTypes,
	}.Build()
	File_standards_open_fundholdings_v1_apex_ftrdist_proto = out.File
	file_standards_open_fundholdings_v1_apex_ftrdist_proto_goTypes = nil
	file_standards_open_fundholdings_v1_apex_ftrdist_proto_depIdxs = nil
}
