// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: google/api/servicecontrol/v1/http_request.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-03-23 15:17:29 UTC

package v1

const ()
