// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.4
// source: alis/a2a/extension/history/v1/history.proto

package v1

import (
	v12 "go.alis.build/common/alis/open/iam/v1"
	v1 "go.alis.build/common/lf/a2a/v1"
	v11 "google.golang.org/genproto/googleapis/iam/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An Thread resource
type Thread struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the Thread.
	// threads/{context_id}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Generated display name from the first event in a Thread.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The agent_id, e.g. finance-agent-v1
	AgentId string `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// The agent display name, e.g. Finance Agent
	AgentDisplayName string `protobuf:"bytes,4,opt,name=agent_display_name,json=agentDisplayName,proto3" json:"agent_display_name,omitempty"`
	// Internal monotonic counter for assigning event sequence numbers.
	NextSequence int64 `protobuf:"varint,5,opt,name=next_sequence,json=nextSequence,proto3" json:"next_sequence,omitempty"`
	// Highest event sequence currently present in the thread.
	// This is shared thread state and is the source of truth for unread calculations.
	LatestSequence int64 `protobuf:"varint,6,opt,name=latest_sequence,json=latestSequence,proto3" json:"latest_sequence,omitempty"`
	// Caller-specific read cursor for the thread.
	// This is a response projection, not shared thread state.
	// It is populated on read APIs that have caller context, such as ListThreads.
	// Future multi-user implementations may expose per-user read state separately.
	ReadSequence int64 `protobuf:"varint,7,opt,name=read_sequence,json=readSequence,proto3" json:"read_sequence,omitempty"`
	// True when the caller has unread events in this thread.
	// This is a response projection derived from latest_sequence and read_sequence.
	HasUnread bool `protobuf:"varint,8,opt,name=has_unread,json=hasUnread,proto3" json:"has_unread,omitempty"`
	// When this Thread was created.
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,98,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Thread) Reset() {
	*x = Thread{}
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Thread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thread) ProtoMessage() {}

func (x *Thread) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thread.ProtoReflect.Descriptor instead.
func (*Thread) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_history_proto_rawDescGZIP(), []int{0}
}

func (x *Thread) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Thread) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Thread) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Thread) GetAgentDisplayName() string {
	if x != nil {
		return x.AgentDisplayName
	}
	return ""
}

func (x *Thread) GetNextSequence() int64 {
	if x != nil {
		return x.NextSequence
	}
	return 0
}

func (x *Thread) GetLatestSequence() int64 {
	if x != nil {
		return x.LatestSequence
	}
	return 0
}

func (x *Thread) GetReadSequence() int64 {
	if x != nil {
		return x.ReadSequence
	}
	return 0
}

func (x *Thread) GetHasUnread() bool {
	if x != nil {
		return x.HasUnread
	}
	return false
}

func (x *Thread) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

// An ThreadEvent resource
type ThreadEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the event.
	// threads/{context_id}/events/{event_id}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ThreadEvent_Task
	//	*ThreadEvent_Message
	//	*ThreadEvent_StatusUpdate
	//	*ThreadEvent_ArtifactUpdate
	Payload isThreadEvent_Payload `protobuf_oneof:"payload"`
	// Monotonic sequence number within a thread.
	// Clients can use this as a stable read cursor.
	Sequence int64 `protobuf:"varint,6,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// When this event was created.
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,98,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadEvent) Reset() {
	*x = ThreadEvent{}
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadEvent) ProtoMessage() {}

func (x *ThreadEvent) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadEvent.ProtoReflect.Descriptor instead.
func (*ThreadEvent) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_history_proto_rawDescGZIP(), []int{1}
}

func (x *ThreadEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ThreadEvent) GetPayload() isThreadEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ThreadEvent) GetTask() *v1.Task {
	if x != nil {
		if x, ok := x.Payload.(*ThreadEvent_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *ThreadEvent) GetMessage() *v1.Message {
	if x != nil {
		if x, ok := x.Payload.(*ThreadEvent_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *ThreadEvent) GetStatusUpdate() *v1.TaskStatusUpdateEvent {
	if x != nil {
		if x, ok := x.Payload.(*ThreadEvent_StatusUpdate); ok {
			return x.StatusUpdate
		}
	}
	return nil
}

func (x *ThreadEvent) GetArtifactUpdate() *v1.TaskArtifactUpdateEvent {
	if x != nil {
		if x, ok := x.Payload.(*ThreadEvent_ArtifactUpdate); ok {
			return x.ArtifactUpdate
		}
	}
	return nil
}

func (x *ThreadEvent) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ThreadEvent) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type isThreadEvent_Payload interface {
	isThreadEvent_Payload()
}

type ThreadEvent_Task struct {
	// A Task object containing the current state of the task.
	Task *v1.Task `protobuf:"bytes,2,opt,name=task,proto3,oneof"`
}

type ThreadEvent_Message struct {
	// A Message object containing a message from the client/user.
	Message *v1.Message `protobuf:"bytes,3,opt,name=message,proto3,oneof"`
}

type ThreadEvent_StatusUpdate struct {
	// An event indicating a task status update.
	StatusUpdate *v1.TaskStatusUpdateEvent `protobuf:"bytes,4,opt,name=status_update,json=statusUpdate,proto3,oneof"`
}

type ThreadEvent_ArtifactUpdate struct {
	// An event indicating a task artifact update.
	ArtifactUpdate *v1.TaskArtifactUpdateEvent `protobuf:"bytes,5,opt,name=artifact_update,json=artifactUpdate,proto3,oneof"`
}

func (*ThreadEvent_Task) isThreadEvent_Payload() {}

func (*ThreadEvent_Message) isThreadEvent_Payload() {}

func (*ThreadEvent_StatusUpdate) isThreadEvent_Payload() {}

func (*ThreadEvent_ArtifactUpdate) isThreadEvent_Payload() {}

// Request to get an Thread.
type GetThreadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the Thread to retrieve.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A read mask to specify which fields to return.
	// If not specified, view will determine the fields returned.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThreadRequest) Reset() {
	*x = GetThreadRequest{}
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreadRequest) ProtoMessage() {}

func (x *GetThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreadRequest.ProtoReflect.Descriptor instead.
func (*GetThreadRequest) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_history_proto_rawDescGZIP(), []int{2}
}

func (x *GetThreadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetThreadRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

// Request to delete an Thread.
type DeleteThreadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the Thread to delete.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteThreadRequest) Reset() {
	*x = DeleteThreadRequest{}
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteThreadRequest) ProtoMessage() {}

func (x *DeleteThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteThreadRequest.ProtoReflect.Descriptor instead.
func (*DeleteThreadRequest) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_history_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteThreadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request to list Threads.
type ListThreadsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum number of A2A Threads to return.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A page token to retrieve the next page of results.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional filtering of Threads by the "agent_id" who produced the underlying Events.
	// Example: my-agent-v1. However, this can be any unique identifier that client decides to use.
	AgentId string `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// A read mask to specify which fields to return.
	// If not specified, view will determine the fields returned.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,5,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListThreadsRequest) Reset() {
	*x = ListThreadsRequest{}
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListThreadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListThreadsRequest) ProtoMessage() {}

func (x *ListThreadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListThreadsRequest.ProtoReflect.Descriptor instead.
func (*ListThreadsRequest) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_history_proto_rawDescGZIP(), []int{4}
}

func (x *ListThreadsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListThreadsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListThreadsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ListThreadsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

// Response for ListThreads.
type ListThreadsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of a2a treads.
	Threads []*Thread `protobuf:"bytes,1,rep,name=threads,proto3" json:"threads,omitempty"`
	// A token to retrieve the next page of results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListThreadsResponse) Reset() {
	*x = ListThreadsResponse{}
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListThreadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListThreadsResponse) ProtoMessage() {}

func (x *ListThreadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListThreadsResponse.ProtoReflect.Descriptor instead.
func (*ListThreadsResponse) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_history_proto_rawDescGZIP(), []int{5}
}

func (x *ListThreadsResponse) GetThreads() []*Thread {
	if x != nil {
		return x.Threads
	}
	return nil
}

func (x *ListThreadsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Request to get an event.
type GetThreadEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the event to retrieve.
	// Format: threads/{context_id}/events/{event_id}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A read mask to specify which fields to return.
	// If not specified, view will determine the fields returned.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThreadEventRequest) Reset() {
	*x = GetThreadEventRequest{}
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreadEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreadEventRequest) ProtoMessage() {}

func (x *GetThreadEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreadEventRequest.ProtoReflect.Descriptor instead.
func (*GetThreadEventRequest) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_history_proto_rawDescGZIP(), []int{6}
}

func (x *GetThreadEventRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetThreadEventRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

// Request to list events.
type ListThreadEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parent Thread resource name.
	// Format: threads/{context_id}
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The maximum number of events to return.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A page token to retrieve the next page of results.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// A read mask to specify which fields to return.
	// If not specified, view will determine the fields returned.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,5,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListThreadEventsRequest) Reset() {
	*x = ListThreadEventsRequest{}
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListThreadEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListThreadEventsRequest) ProtoMessage() {}

func (x *ListThreadEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListThreadEventsRequest.ProtoReflect.Descriptor instead.
func (*ListThreadEventsRequest) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_history_proto_rawDescGZIP(), []int{7}
}

func (x *ListThreadEventsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListThreadEventsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListThreadEventsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListThreadEventsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

// Response for ListThreadEvents.
type ListThreadEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of events.
	Events []*ThreadEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	// A token to retrieve the next page of results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListThreadEventsResponse) Reset() {
	*x = ListThreadEventsResponse{}
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListThreadEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListThreadEventsResponse) ProtoMessage() {}

func (x *ListThreadEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListThreadEventsResponse.ProtoReflect.Descriptor instead.
func (*ListThreadEventsResponse) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_history_proto_rawDescGZIP(), []int{8}
}

func (x *ListThreadEventsResponse) GetEvents() []*ThreadEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListThreadEventsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Request to stream events.
type StreamThreadEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parent Thread resource name
	// Format: threads/{context_id}
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// A read mask to specify which fields to return.
	// If not specified, view will determine the fields returned.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamThreadEventsRequest) Reset() {
	*x = StreamThreadEventsRequest{}
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamThreadEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamThreadEventsRequest) ProtoMessage() {}

func (x *StreamThreadEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamThreadEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamThreadEventsRequest) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_history_proto_rawDescGZIP(), []int{9}
}

func (x *StreamThreadEventsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *StreamThreadEventsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

// Request to appending an event.
type AppendThreadEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The event to create.
	// Parent Thread deduced from the event-provided context_id.
	Event *ThreadEvent `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	// The agent_id, e.g. finance-agent-v1
	// Only used on first event in a Thread.
	AgentId       string `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendThreadEventRequest) Reset() {
	*x = AppendThreadEventRequest{}
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendThreadEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendThreadEventRequest) ProtoMessage() {}

func (x *AppendThreadEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendThreadEventRequest.ProtoReflect.Descriptor instead.
func (*AppendThreadEventRequest) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_history_proto_rawDescGZIP(), []int{10}
}

func (x *AppendThreadEventRequest) GetEvent() *ThreadEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AppendThreadEventRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// Response to appending an event.
type AppendThreadEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendThreadEventResponse) Reset() {
	*x = AppendThreadEventResponse{}
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendThreadEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendThreadEventResponse) ProtoMessage() {}

func (x *AppendThreadEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendThreadEventResponse.ProtoReflect.Descriptor instead.
func (*AppendThreadEventResponse) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_history_proto_rawDescGZIP(), []int{11}
}

var File_alis_a2a_extension_history_v1_history_proto protoreflect.FileDescriptor

const file_alis_a2a_extension_history_v1_history_proto_rawDesc = "" +
	"\n" +
	"+alis/a2a/extension/history/v1/history.proto\x12\x1dalis.a2a.extension.history.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\x1a\x1agoogle/iam/v1/policy.proto\x1a\x1egoogle/iam/v1/iam_policy.proto\x1a\x1aalis/open/iam/v1/iam.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x13lf/a2a/v1/a2a.proto\"\xd7\x02\n" +
	"\x06Thread\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12,\n" +
	"\x12agent_display_name\x18\x04 \x01(\tR\x10agentDisplayName\x12#\n" +
	"\rnext_sequence\x18\x05 \x01(\x03R\fnextSequence\x12'\n" +
	"\x0flatest_sequence\x18\x06 \x01(\x03R\x0elatestSequence\x12#\n" +
	"\rread_sequence\x18\a \x01(\x03R\freadSequence\x12\x1d\n" +
	"\n" +
	"has_unread\x18\b \x01(\bR\thasUnread\x12;\n" +
	"\vcreate_time\x18b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\"\xf4\x02\n" +
	"\vThreadEvent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x04task\x18\x02 \x01(\v2\x0f.lf.a2a.v1.TaskH\x00R\x04task\x12.\n" +
	"\amessage\x18\x03 \x01(\v2\x12.lf.a2a.v1.MessageH\x00R\amessage\x12G\n" +
	"\rstatus_update\x18\x04 \x01(\v2 .lf.a2a.v1.TaskStatusUpdateEventH\x00R\fstatusUpdate\x12M\n" +
	"\x0fartifact_update\x18\x05 \x01(\v2\".lf.a2a.v1.TaskArtifactUpdateEventH\x00R\x0eartifactUpdate\x12\x1a\n" +
	"\bsequence\x18\x06 \x01(\x03R\bsequence\x12;\n" +
	"\vcreate_time\x18b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTimeB\t\n" +
	"\apayload\"_\n" +
	"\x10GetThreadRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\tread_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\")\n" +
	"\x13DeleteThreadRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xaa\x01\n" +
	"\x12ListThreadsRequest\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x127\n" +
	"\tread_mask\x18\x05 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMaskJ\x04\b\x01\x10\x02\"~\n" +
	"\x13ListThreadsResponse\x12?\n" +
	"\athreads\x18\x01 \x03(\v2%.alis.a2a.extension.history.v1.ThreadR\athreads\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"d\n" +
	"\x15GetThreadEventRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\tread_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\"\xa6\x01\n" +
	"\x17ListThreadEventsRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x127\n" +
	"\tread_mask\x18\x05 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\"\x86\x01\n" +
	"\x18ListThreadEventsResponse\x12B\n" +
	"\x06events\x18\x01 \x03(\v2*.alis.a2a.extension.history.v1.ThreadEventR\x06events\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"l\n" +
	"\x19StreamThreadEventsRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x127\n" +
	"\tread_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\"}\n" +
	"\x18AppendThreadEventRequest\x12@\n" +
	"\x05event\x18\x02 \x01(\v2*.alis.a2a.extension.history.v1.ThreadEventR\x05event\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentIdJ\x04\b\x01\x10\x02\"\x1b\n" +
	"\x19AppendThreadEventResponse2\xa7\b\n" +
	"\rThreadService\x12K\n" +
	"\fGetIamPolicy\x12\".google.iam.v1.GetIamPolicyRequest\x1a\x15.google.iam.v1.Policy\"\x00\x12K\n" +
	"\fSetIamPolicy\x12\".google.iam.v1.SetIamPolicyRequest\x1a\x15.google.iam.v1.Policy\"\x00\x12R\n" +
	"\x0eAddIamBindings\x12'.alis.open.iam.v1.AddIamBindingsRequest\x1a\x15.google.iam.v1.Policy\"\x00\x12X\n" +
	"\x11RemoveIamBindings\x12*.alis.open.iam.v1.RemoveIamBindingsRequest\x1a\x15.google.iam.v1.Policy\"\x00\x12v\n" +
	"\vListThreads\x121.alis.a2a.extension.history.v1.ListThreadsRequest\x1a2.alis.a2a.extension.history.v1.ListThreadsResponse\"\x00\x12e\n" +
	"\tGetThread\x12/.alis.a2a.extension.history.v1.GetThreadRequest\x1a%.alis.a2a.extension.history.v1.Thread\"\x00\x12\\\n" +
	"\fDeleteThread\x122.alis.a2a.extension.history.v1.DeleteThreadRequest\x1a\x16.google.protobuf.Empty\"\x00\x12\x88\x01\n" +
	"\x11AppendThreadEvent\x127.alis.a2a.extension.history.v1.AppendThreadEventRequest\x1a8.alis.a2a.extension.history.v1.AppendThreadEventResponse\"\x00\x12\x85\x01\n" +
	"\x10ListThreadEvents\x126.alis.a2a.extension.history.v1.ListThreadEventsRequest\x1a7.alis.a2a.extension.history.v1.ListThreadEventsResponse\"\x00\x12~\n" +
	"\x12StreamThreadEvents\x128.alis.a2a.extension.history.v1.StreamThreadEventsRequest\x1a*.alis.a2a.extension.history.v1.ThreadEvent\"\x000\x01B4Z2go.alis.build/common/alis/a2a/extension/history/v1b\x06proto3"

var (
	file_alis_a2a_extension_history_v1_history_proto_rawDescOnce sync.Once
	file_alis_a2a_extension_history_v1_history_proto_rawDescData []byte
)

func file_alis_a2a_extension_history_v1_history_proto_rawDescGZIP() []byte {
	file_alis_a2a_extension_history_v1_history_proto_rawDescOnce.Do(func() {
		file_alis_a2a_extension_history_v1_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alis_a2a_extension_history_v1_history_proto_rawDesc), len(file_alis_a2a_extension_history_v1_history_proto_rawDesc)))
	})
	return file_alis_a2a_extension_history_v1_history_proto_rawDescData
}

var file_alis_a2a_extension_history_v1_history_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_alis_a2a_extension_history_v1_history_proto_goTypes = []any{
	(*Thread)(nil),                       // 0: alis.a2a.extension.history.v1.Thread
	(*ThreadEvent)(nil),                  // 1: alis.a2a.extension.history.v1.ThreadEvent
	(*GetThreadRequest)(nil),             // 2: alis.a2a.extension.history.v1.GetThreadRequest
	(*DeleteThreadRequest)(nil),          // 3: alis.a2a.extension.history.v1.DeleteThreadRequest
	(*ListThreadsRequest)(nil),           // 4: alis.a2a.extension.history.v1.ListThreadsRequest
	(*ListThreadsResponse)(nil),          // 5: alis.a2a.extension.history.v1.ListThreadsResponse
	(*GetThreadEventRequest)(nil),        // 6: alis.a2a.extension.history.v1.GetThreadEventRequest
	(*ListThreadEventsRequest)(nil),      // 7: alis.a2a.extension.history.v1.ListThreadEventsRequest
	(*ListThreadEventsResponse)(nil),     // 8: alis.a2a.extension.history.v1.ListThreadEventsResponse
	(*StreamThreadEventsRequest)(nil),    // 9: alis.a2a.extension.history.v1.StreamThreadEventsRequest
	(*AppendThreadEventRequest)(nil),     // 10: alis.a2a.extension.history.v1.AppendThreadEventRequest
	(*AppendThreadEventResponse)(nil),    // 11: alis.a2a.extension.history.v1.AppendThreadEventResponse
	(*timestamppb.Timestamp)(nil),        // 12: google.protobuf.Timestamp
	(*v1.Task)(nil),                      // 13: lf.a2a.v1.Task
	(*v1.Message)(nil),                   // 14: lf.a2a.v1.Message
	(*v1.TaskStatusUpdateEvent)(nil),     // 15: lf.a2a.v1.TaskStatusUpdateEvent
	(*v1.TaskArtifactUpdateEvent)(nil),   // 16: lf.a2a.v1.TaskArtifactUpdateEvent
	(*fieldmaskpb.FieldMask)(nil),        // 17: google.protobuf.FieldMask
	(*v11.GetIamPolicyRequest)(nil),      // 18: google.iam.v1.GetIamPolicyRequest
	(*v11.SetIamPolicyRequest)(nil),      // 19: google.iam.v1.SetIamPolicyRequest
	(*v12.AddIamBindingsRequest)(nil),    // 20: alis.open.iam.v1.AddIamBindingsRequest
	(*v12.RemoveIamBindingsRequest)(nil), // 21: alis.open.iam.v1.RemoveIamBindingsRequest
	(*v11.Policy)(nil),                   // 22: google.iam.v1.Policy
	(*emptypb.Empty)(nil),                // 23: google.protobuf.Empty
}
var file_alis_a2a_extension_history_v1_history_proto_depIdxs = []int32{
	12, // 0: alis.a2a.extension.history.v1.Thread.create_time:type_name -> google.protobuf.Timestamp
	13, // 1: alis.a2a.extension.history.v1.ThreadEvent.task:type_name -> lf.a2a.v1.Task
	14, // 2: alis.a2a.extension.history.v1.ThreadEvent.message:type_name -> lf.a2a.v1.Message
	15, // 3: alis.a2a.extension.history.v1.ThreadEvent.status_update:type_name -> lf.a2a.v1.TaskStatusUpdateEvent
	16, // 4: alis.a2a.extension.history.v1.ThreadEvent.artifact_update:type_name -> lf.a2a.v1.TaskArtifactUpdateEvent
	12, // 5: alis.a2a.extension.history.v1.ThreadEvent.create_time:type_name -> google.protobuf.Timestamp
	17, // 6: alis.a2a.extension.history.v1.GetThreadRequest.read_mask:type_name -> google.protobuf.FieldMask
	17, // 7: alis.a2a.extension.history.v1.ListThreadsRequest.read_mask:type_name -> google.protobuf.FieldMask
	0,  // 8: alis.a2a.extension.history.v1.ListThreadsResponse.threads:type_name -> alis.a2a.extension.history.v1.Thread
	17, // 9: alis.a2a.extension.history.v1.GetThreadEventRequest.read_mask:type_name -> google.protobuf.FieldMask
	17, // 10: alis.a2a.extension.history.v1.ListThreadEventsRequest.read_mask:type_name -> google.protobuf.FieldMask
	1,  // 11: alis.a2a.extension.history.v1.ListThreadEventsResponse.events:type_name -> alis.a2a.extension.history.v1.ThreadEvent
	17, // 12: alis.a2a.extension.history.v1.StreamThreadEventsRequest.read_mask:type_name -> google.protobuf.FieldMask
	1,  // 13: alis.a2a.extension.history.v1.AppendThreadEventRequest.event:type_name -> alis.a2a.extension.history.v1.ThreadEvent
	18, // 14: alis.a2a.extension.history.v1.ThreadService.GetIamPolicy:input_type -> google.iam.v1.GetIamPolicyRequest
	19, // 15: alis.a2a.extension.history.v1.ThreadService.SetIamPolicy:input_type -> google.iam.v1.SetIamPolicyRequest
	20, // 16: alis.a2a.extension.history.v1.ThreadService.AddIamBindings:input_type -> alis.open.iam.v1.AddIamBindingsRequest
	21, // 17: alis.a2a.extension.history.v1.ThreadService.RemoveIamBindings:input_type -> alis.open.iam.v1.RemoveIamBindingsRequest
	4,  // 18: alis.a2a.extension.history.v1.ThreadService.ListThreads:input_type -> alis.a2a.extension.history.v1.ListThreadsRequest
	2,  // 19: alis.a2a.extension.history.v1.ThreadService.GetThread:input_type -> alis.a2a.extension.history.v1.GetThreadRequest
	3,  // 20: alis.a2a.extension.history.v1.ThreadService.DeleteThread:input_type -> alis.a2a.extension.history.v1.DeleteThreadRequest
	10, // 21: alis.a2a.extension.history.v1.ThreadService.AppendThreadEvent:input_type -> alis.a2a.extension.history.v1.AppendThreadEventRequest
	7,  // 22: alis.a2a.extension.history.v1.ThreadService.ListThreadEvents:input_type -> alis.a2a.extension.history.v1.ListThreadEventsRequest
	9,  // 23: alis.a2a.extension.history.v1.ThreadService.StreamThreadEvents:input_type -> alis.a2a.extension.history.v1.StreamThreadEventsRequest
	22, // 24: alis.a2a.extension.history.v1.ThreadService.GetIamPolicy:output_type -> google.iam.v1.Policy
	22, // 25: alis.a2a.extension.history.v1.ThreadService.SetIamPolicy:output_type -> google.iam.v1.Policy
	22, // 26: alis.a2a.extension.history.v1.ThreadService.AddIamBindings:output_type -> google.iam.v1.Policy
	22, // 27: alis.a2a.extension.history.v1.ThreadService.RemoveIamBindings:output_type -> google.iam.v1.Policy
	5,  // 28: alis.a2a.extension.history.v1.ThreadService.ListThreads:output_type -> alis.a2a.extension.history.v1.ListThreadsResponse
	0,  // 29: alis.a2a.extension.history.v1.ThreadService.GetThread:output_type -> alis.a2a.extension.history.v1.Thread
	23, // 30: alis.a2a.extension.history.v1.ThreadService.DeleteThread:output_type -> google.protobuf.Empty
	11, // 31: alis.a2a.extension.history.v1.ThreadService.AppendThreadEvent:output_type -> alis.a2a.extension.history.v1.AppendThreadEventResponse
	8,  // 32: alis.a2a.extension.history.v1.ThreadService.ListThreadEvents:output_type -> alis.a2a.extension.history.v1.ListThreadEventsResponse
	1,  // 33: alis.a2a.extension.history.v1.ThreadService.StreamThreadEvents:output_type -> alis.a2a.extension.history.v1.ThreadEvent
	24, // [24:34] is the sub-list for method output_type
	14, // [14:24] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_alis_a2a_extension_history_v1_history_proto_init() }
func file_alis_a2a_extension_history_v1_history_proto_init() {
	if File_alis_a2a_extension_history_v1_history_proto != nil {
		return
	}
	file_alis_a2a_extension_history_v1_history_proto_msgTypes[1].OneofWrappers = []any{
		(*ThreadEvent_Task)(nil),
		(*ThreadEvent_Message)(nil),
		(*ThreadEvent_StatusUpdate)(nil),
		(*ThreadEvent_ArtifactUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alis_a2a_extension_history_v1_history_proto_rawDesc), len(file_alis_a2a_extension_history_v1_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alis_a2a_extension_history_v1_history_proto_goTypes,
		DependencyIndexes: file_alis_a2a_extension_history_v1_history_proto_depIdxs,
		MessageInfos:      file_alis_a2a_extension_history_v1_history_proto_msgTypes,
	}.Build()
	File_alis_a2a_extension_history_v1_history_proto = out.File
	file_alis_a2a_extension_history_v1_history_proto_goTypes = nil
	file_alis_a2a_extension_history_v1_history_proto_depIdxs = nil
}
