// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/open/validation/v1/validation.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-03-24 07:46:07 UTC

package v1

const (
	// ValidationService_RetrieveRules_FullMethodDescription returns the description of the alis.open.validation.v1.ValidationService.RetrieveRules method.
	ValidationService_RetrieveRules_FullMethodDescription = "Retrieve the validation rules for a given message type."
	// ValidationService_ValidateMessage_FullMethodDescription returns the description of the alis.open.validation.v1.ValidationService.ValidateMessage method.
	ValidationService_ValidateMessage_FullMethodDescription = "Validates if the given bytes are valid for the given message type.\n If the bytes cannot be marshalled into the message type, the rpc will return an error instead of the violations."
)
