// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.4
// source: alis/open/options/v1/options.proto

package v1

import (
	protobuf "go.alis.build/common/google/protobuf"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FileOptions
type FileOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Options for the JSON schema generation.
	JsonSchema    *FileOptions_JsonSchema `protobuf:"bytes,1,opt,name=json_schema,json=jsonSchema,proto3" json:"json_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileOptions) Reset() {
	*x = FileOptions{}
	mi := &file_alis_open_options_v1_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOptions) ProtoMessage() {}

func (x *FileOptions) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_options_v1_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOptions.ProtoReflect.Descriptor instead.
func (*FileOptions) Descriptor() ([]byte, []int) {
	return file_alis_open_options_v1_options_proto_rawDescGZIP(), []int{0}
}

func (x *FileOptions) GetJsonSchema() *FileOptions_JsonSchema {
	if x != nil {
		return x.JsonSchema
	}
	return nil
}

// Message Options
type MessageOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Options for the JSON schema generation.
	JsonSchema    *MessageOptions_JsonSchema `protobuf:"bytes,1,opt,name=json_schema,json=jsonSchema,proto3" json:"json_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	mi := &file_alis_open_options_v1_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_options_v1_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOptions.ProtoReflect.Descriptor instead.
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return file_alis_open_options_v1_options_proto_rawDescGZIP(), []int{1}
}

func (x *MessageOptions) GetJsonSchema() *MessageOptions_JsonSchema {
	if x != nil {
		return x.JsonSchema
	}
	return nil
}

// Field Options
type FieldOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Options for the JSON schema generation.
	JsonSchema    *FieldOptions_JsonSchema `protobuf:"bytes,1,opt,name=json_schema,json=jsonSchema,proto3" json:"json_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_alis_open_options_v1_options_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_options_v1_options_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_alis_open_options_v1_options_proto_rawDescGZIP(), []int{2}
}

func (x *FieldOptions) GetJsonSchema() *FieldOptions_JsonSchema {
	if x != nil {
		return x.JsonSchema
	}
	return nil
}

type FileOptions_JsonSchema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If true, schemas will be generated for all messages in this file, unless
	// explicitly disabled on the message.
	Generate      bool `protobuf:"varint,1,opt,name=generate,proto3" json:"generate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileOptions_JsonSchema) Reset() {
	*x = FileOptions_JsonSchema{}
	mi := &file_alis_open_options_v1_options_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOptions_JsonSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOptions_JsonSchema) ProtoMessage() {}

func (x *FileOptions_JsonSchema) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_options_v1_options_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOptions_JsonSchema.ProtoReflect.Descriptor instead.
func (*FileOptions_JsonSchema) Descriptor() ([]byte, []int) {
	return file_alis_open_options_v1_options_proto_rawDescGZIP(), []int{0, 0}
}

func (x *FileOptions_JsonSchema) GetGenerate() bool {
	if x != nil {
		return x.Generate
	}
	return false
}

type MessageOptions_JsonSchema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If true, a JSON schema will be generated for this message.
	Generate      bool `protobuf:"varint,1,opt,name=generate,proto3" json:"generate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageOptions_JsonSchema) Reset() {
	*x = MessageOptions_JsonSchema{}
	mi := &file_alis_open_options_v1_options_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOptions_JsonSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions_JsonSchema) ProtoMessage() {}

func (x *MessageOptions_JsonSchema) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_options_v1_options_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOptions_JsonSchema.ProtoReflect.Descriptor instead.
func (*MessageOptions_JsonSchema) Descriptor() ([]byte, []int) {
	return file_alis_open_options_v1_options_proto_rawDescGZIP(), []int{1, 0}
}

func (x *MessageOptions_JsonSchema) GetGenerate() bool {
	if x != nil {
		return x.Generate
	}
	return false
}

type FieldOptions_JsonSchema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The title of the field.
	Title *string `protobuf:"bytes,1,opt,name=title,proto3,oneof" json:"title,omitempty"`
	// The description of the field.
	Description *string `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Hides this field from the generated JSON schema entirely.
	Ignore *bool `protobuf:"varint,3,opt,name=ignore,proto3,oneof" json:"ignore,omitempty"`
	// Regex pattern (e.g. "^[A-Z]+$")
	Pattern *string `protobuf:"bytes,4,opt,name=pattern,proto3,oneof" json:"pattern,omitempty"`
	// Standard formats (email, uuid, ipv4, uri, etc.)
	Format *string `protobuf:"bytes,5,opt,name=format,proto3,oneof" json:"format,omitempty"`
	// The content encoding of the field.
	ContentEncoding *string `protobuf:"bytes,6,opt,name=content_encoding,json=contentEncoding,proto3,oneof" json:"content_encoding,omitempty"`
	// The content media type of the field.
	ContentMediaType *string `protobuf:"bytes,7,opt,name=content_media_type,json=contentMediaType,proto3,oneof" json:"content_media_type,omitempty"`
	// The minimum length of the field.
	MinLength *int64 `protobuf:"varint,8,opt,name=min_length,json=minLength,proto3,oneof" json:"min_length,omitempty"`
	// The maximum length of the field.
	MaxLength *int64 `protobuf:"varint,9,opt,name=max_length,json=maxLength,proto3,oneof" json:"max_length,omitempty"`
	// The minimum value of the field.
	Minimum *float64 `protobuf:"fixed64,10,opt,name=minimum,proto3,oneof" json:"minimum,omitempty"`
	// The maximum value of the field.
	Maximum *float64 `protobuf:"fixed64,11,opt,name=maximum,proto3,oneof" json:"maximum,omitempty"`
	// Whether the minimum value is exclusive.
	ExclusiveMinimum *bool `protobuf:"varint,12,opt,name=exclusive_minimum,json=exclusiveMinimum,proto3,oneof" json:"exclusive_minimum,omitempty"`
	// Whether the maximum value is exclusive.
	ExclusiveMaximum *bool `protobuf:"varint,13,opt,name=exclusive_maximum,json=exclusiveMaximum,proto3,oneof" json:"exclusive_maximum,omitempty"`
	// The minimum number of items in the field.
	MinItems *int64 `protobuf:"varint,14,opt,name=min_items,json=minItems,proto3,oneof" json:"min_items,omitempty"`
	// The maximum number of items in the field.
	MaxItems *int64 `protobuf:"varint,15,opt,name=max_items,json=maxItems,proto3,oneof" json:"max_items,omitempty"`
	// Whether the items in the field are unique.
	UniqueItems *bool `protobuf:"varint,16,opt,name=unique_items,json=uniqueItems,proto3,oneof" json:"unique_items,omitempty"`
	// The minimum number of properties in the field.
	MinProperties *int64 `protobuf:"varint,17,opt,name=min_properties,json=minProperties,proto3,oneof" json:"min_properties,omitempty"`
	// The maximum number of properties in the field.
	MaxProperties *int64 `protobuf:"varint,18,opt,name=max_properties,json=maxProperties,proto3,oneof" json:"max_properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldOptions_JsonSchema) Reset() {
	*x = FieldOptions_JsonSchema{}
	mi := &file_alis_open_options_v1_options_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions_JsonSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions_JsonSchema) ProtoMessage() {}

func (x *FieldOptions_JsonSchema) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_options_v1_options_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions_JsonSchema.ProtoReflect.Descriptor instead.
func (*FieldOptions_JsonSchema) Descriptor() ([]byte, []int) {
	return file_alis_open_options_v1_options_proto_rawDescGZIP(), []int{2, 0}
}

func (x *FieldOptions_JsonSchema) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *FieldOptions_JsonSchema) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *FieldOptions_JsonSchema) GetIgnore() bool {
	if x != nil && x.Ignore != nil {
		return *x.Ignore
	}
	return false
}

func (x *FieldOptions_JsonSchema) GetPattern() string {
	if x != nil && x.Pattern != nil {
		return *x.Pattern
	}
	return ""
}

func (x *FieldOptions_JsonSchema) GetFormat() string {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return ""
}

func (x *FieldOptions_JsonSchema) GetContentEncoding() string {
	if x != nil && x.ContentEncoding != nil {
		return *x.ContentEncoding
	}
	return ""
}

func (x *FieldOptions_JsonSchema) GetContentMediaType() string {
	if x != nil && x.ContentMediaType != nil {
		return *x.ContentMediaType
	}
	return ""
}

func (x *FieldOptions_JsonSchema) GetMinLength() int64 {
	if x != nil && x.MinLength != nil {
		return *x.MinLength
	}
	return 0
}

func (x *FieldOptions_JsonSchema) GetMaxLength() int64 {
	if x != nil && x.MaxLength != nil {
		return *x.MaxLength
	}
	return 0
}

func (x *FieldOptions_JsonSchema) GetMinimum() float64 {
	if x != nil && x.Minimum != nil {
		return *x.Minimum
	}
	return 0
}

func (x *FieldOptions_JsonSchema) GetMaximum() float64 {
	if x != nil && x.Maximum != nil {
		return *x.Maximum
	}
	return 0
}

func (x *FieldOptions_JsonSchema) GetExclusiveMinimum() bool {
	if x != nil && x.ExclusiveMinimum != nil {
		return *x.ExclusiveMinimum
	}
	return false
}

func (x *FieldOptions_JsonSchema) GetExclusiveMaximum() bool {
	if x != nil && x.ExclusiveMaximum != nil {
		return *x.ExclusiveMaximum
	}
	return false
}

func (x *FieldOptions_JsonSchema) GetMinItems() int64 {
	if x != nil && x.MinItems != nil {
		return *x.MinItems
	}
	return 0
}

func (x *FieldOptions_JsonSchema) GetMaxItems() int64 {
	if x != nil && x.MaxItems != nil {
		return *x.MaxItems
	}
	return 0
}

func (x *FieldOptions_JsonSchema) GetUniqueItems() bool {
	if x != nil && x.UniqueItems != nil {
		return *x.UniqueItems
	}
	return false
}

func (x *FieldOptions_JsonSchema) GetMinProperties() int64 {
	if x != nil && x.MinProperties != nil {
		return *x.MinProperties
	}
	return 0
}

func (x *FieldOptions_JsonSchema) GetMaxProperties() int64 {
	if x != nil && x.MaxProperties != nil {
		return *x.MaxProperties
	}
	return 0
}

var file_alis_open_options_v1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*protobuf.FileOptions)(nil),
		ExtensionType: (*FileOptions)(nil),
		Field:         1001,
		Name:          "alis.open.options.v1.file",
		Tag:           "bytes,1001,opt,name=file",
		Filename:      "alis/open/options/v1/options.proto",
	},
	{
		ExtendedType:  (*protobuf.MessageOptions)(nil),
		ExtensionType: (*MessageOptions)(nil),
		Field:         1001,
		Name:          "alis.open.options.v1.message",
		Tag:           "bytes,1001,opt,name=message",
		Filename:      "alis/open/options/v1/options.proto",
	},
	{
		ExtendedType:  (*protobuf.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         1001,
		Name:          "alis.open.options.v1.field",
		Tag:           "bytes,1001,opt,name=field",
		Filename:      "alis/open/options/v1/options.proto",
	},
}

// Extension fields to protobuf.FileOptions.
var (
	// Usage: option (alis.open.options.v1.file).json_schema.generate = true;
	//
	// optional alis.open.options.v1.FileOptions file = 1001;
	E_File = &file_alis_open_options_v1_options_proto_extTypes[0]
)

// Extension fields to protobuf.MessageOptions.
var (
	// Usage: option (alis.open.options.v1.message).json_schema.generate = true;
	//
	// optional alis.open.options.v1.MessageOptions message = 1001;
	E_Message = &file_alis_open_options_v1_options_proto_extTypes[1]
)

// Extension fields to protobuf.FieldOptions.
var (
	// Usage:
	// string email = 1 [
	//
	//	(alis.open.options.v1.field).json_schema = {
	//	  required: true,
	//	  format: "email",
	//	  title: "Primary Email"
	//	}
	//
	// ];
	//
	// optional alis.open.options.v1.FieldOptions field = 1001;
	E_Field = &file_alis_open_options_v1_options_proto_extTypes[2]
)

var File_alis_open_options_v1_options_proto protoreflect.FileDescriptor

const file_alis_open_options_v1_options_proto_rawDesc = "" +
	"\n" +
	"\"alis/open/options/v1/options.proto\x12\x14alis.open.options.v1\x1a google/protobuf/descriptor.proto\"\x86\x01\n" +
	"\vFileOptions\x12M\n" +
	"\vjson_schema\x18\x01 \x01(\v2,.alis.open.options.v1.FileOptions.JsonSchemaR\n" +
	"jsonSchema\x1a(\n" +
	"\n" +
	"JsonSchema\x12\x1a\n" +
	"\bgenerate\x18\x01 \x01(\bR\bgenerate\"\x8c\x01\n" +
	"\x0eMessageOptions\x12P\n" +
	"\vjson_schema\x18\x01 \x01(\v2/.alis.open.options.v1.MessageOptions.JsonSchemaR\n" +
	"jsonSchema\x1a(\n" +
	"\n" +
	"JsonSchema\x12\x1a\n" +
	"\bgenerate\x18\x01 \x01(\bR\bgenerate\"\xb6\b\n" +
	"\fFieldOptions\x12N\n" +
	"\vjson_schema\x18\x01 \x01(\v2-.alis.open.options.v1.FieldOptions.JsonSchemaR\n" +
	"jsonSchema\x1a\xd5\a\n" +
	"\n" +
	"JsonSchema\x12\x19\n" +
	"\x05title\x18\x01 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\x06ignore\x18\x03 \x01(\bH\x02R\x06ignore\x88\x01\x01\x12\x1d\n" +
	"\apattern\x18\x04 \x01(\tH\x03R\apattern\x88\x01\x01\x12\x1b\n" +
	"\x06format\x18\x05 \x01(\tH\x04R\x06format\x88\x01\x01\x12.\n" +
	"\x10content_encoding\x18\x06 \x01(\tH\x05R\x0fcontentEncoding\x88\x01\x01\x121\n" +
	"\x12content_media_type\x18\a \x01(\tH\x06R\x10contentMediaType\x88\x01\x01\x12\"\n" +
	"\n" +
	"min_length\x18\b \x01(\x03H\aR\tminLength\x88\x01\x01\x12\"\n" +
	"\n" +
	"max_length\x18\t \x01(\x03H\bR\tmaxLength\x88\x01\x01\x12\x1d\n" +
	"\aminimum\x18\n" +
	" \x01(\x01H\tR\aminimum\x88\x01\x01\x12\x1d\n" +
	"\amaximum\x18\v \x01(\x01H\n" +
	"R\amaximum\x88\x01\x01\x120\n" +
	"\x11exclusive_minimum\x18\f \x01(\bH\vR\x10exclusiveMinimum\x88\x01\x01\x120\n" +
	"\x11exclusive_maximum\x18\r \x01(\bH\fR\x10exclusiveMaximum\x88\x01\x01\x12 \n" +
	"\tmin_items\x18\x0e \x01(\x03H\rR\bminItems\x88\x01\x01\x12 \n" +
	"\tmax_items\x18\x0f \x01(\x03H\x0eR\bmaxItems\x88\x01\x01\x12&\n" +
	"\funique_items\x18\x10 \x01(\bH\x0fR\vuniqueItems\x88\x01\x01\x12*\n" +
	"\x0emin_properties\x18\x11 \x01(\x03H\x10R\rminProperties\x88\x01\x01\x12*\n" +
	"\x0emax_properties\x18\x12 \x01(\x03H\x11R\rmaxProperties\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_ignoreB\n" +
	"\n" +
	"\b_patternB\t\n" +
	"\a_formatB\x13\n" +
	"\x11_content_encodingB\x15\n" +
	"\x13_content_media_typeB\r\n" +
	"\v_min_lengthB\r\n" +
	"\v_max_lengthB\n" +
	"\n" +
	"\b_minimumB\n" +
	"\n" +
	"\b_maximumB\x14\n" +
	"\x12_exclusive_minimumB\x14\n" +
	"\x12_exclusive_maximumB\f\n" +
	"\n" +
	"_min_itemsB\f\n" +
	"\n" +
	"_max_itemsB\x0f\n" +
	"\r_unique_itemsB\x11\n" +
	"\x0f_min_propertiesB\x11\n" +
	"\x0f_max_properties:T\n" +
	"\x04file\x12\x1c.google.protobuf.FileOptions\x18\xe9\a \x01(\v2!.alis.open.options.v1.FileOptionsR\x04file:`\n" +
	"\amessage\x12\x1f.google.protobuf.MessageOptions\x18\xe9\a \x01(\v2$.alis.open.options.v1.MessageOptionsR\amessage:X\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\xe9\a \x01(\v2\".alis.open.options.v1.FieldOptionsR\x05fieldB+Z)go.alis.build/common/alis/open/options/v1b\x06proto3"

var (
	file_alis_open_options_v1_options_proto_rawDescOnce sync.Once
	file_alis_open_options_v1_options_proto_rawDescData []byte
)

func file_alis_open_options_v1_options_proto_rawDescGZIP() []byte {
	file_alis_open_options_v1_options_proto_rawDescOnce.Do(func() {
		file_alis_open_options_v1_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alis_open_options_v1_options_proto_rawDesc), len(file_alis_open_options_v1_options_proto_rawDesc)))
	})
	return file_alis_open_options_v1_options_proto_rawDescData
}

var file_alis_open_options_v1_options_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_alis_open_options_v1_options_proto_goTypes = []any{
	(*FileOptions)(nil),               // 0: alis.open.options.v1.FileOptions
	(*MessageOptions)(nil),            // 1: alis.open.options.v1.MessageOptions
	(*FieldOptions)(nil),              // 2: alis.open.options.v1.FieldOptions
	(*FileOptions_JsonSchema)(nil),    // 3: alis.open.options.v1.FileOptions.JsonSchema
	(*MessageOptions_JsonSchema)(nil), // 4: alis.open.options.v1.MessageOptions.JsonSchema
	(*FieldOptions_JsonSchema)(nil),   // 5: alis.open.options.v1.FieldOptions.JsonSchema
	(*protobuf.FileOptions)(nil),      // 6: google.protobuf.FileOptions
	(*protobuf.MessageOptions)(nil),   // 7: google.protobuf.MessageOptions
	(*protobuf.FieldOptions)(nil),     // 8: google.protobuf.FieldOptions
}
var file_alis_open_options_v1_options_proto_depIdxs = []int32{
	3, // 0: alis.open.options.v1.FileOptions.json_schema:type_name -> alis.open.options.v1.FileOptions.JsonSchema
	4, // 1: alis.open.options.v1.MessageOptions.json_schema:type_name -> alis.open.options.v1.MessageOptions.JsonSchema
	5, // 2: alis.open.options.v1.FieldOptions.json_schema:type_name -> alis.open.options.v1.FieldOptions.JsonSchema
	6, // 3: alis.open.options.v1.file:extendee -> google.protobuf.FileOptions
	7, // 4: alis.open.options.v1.message:extendee -> google.protobuf.MessageOptions
	8, // 5: alis.open.options.v1.field:extendee -> google.protobuf.FieldOptions
	0, // 6: alis.open.options.v1.file:type_name -> alis.open.options.v1.FileOptions
	1, // 7: alis.open.options.v1.message:type_name -> alis.open.options.v1.MessageOptions
	2, // 8: alis.open.options.v1.field:type_name -> alis.open.options.v1.FieldOptions
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	6, // [6:9] is the sub-list for extension type_name
	3, // [3:6] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_alis_open_options_v1_options_proto_init() }
func file_alis_open_options_v1_options_proto_init() {
	if File_alis_open_options_v1_options_proto != nil {
		return
	}
	file_alis_open_options_v1_options_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alis_open_options_v1_options_proto_rawDesc), len(file_alis_open_options_v1_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_alis_open_options_v1_options_proto_goTypes,
		DependencyIndexes: file_alis_open_options_v1_options_proto_depIdxs,
		MessageInfos:      file_alis_open_options_v1_options_proto_msgTypes,
		ExtensionInfos:    file_alis_open_options_v1_options_proto_extTypes,
	}.Build()
	File_alis_open_options_v1_options_proto = out.File
	file_alis_open_options_v1_options_proto_goTypes = nil
	file_alis_open_options_v1_options_proto_depIdxs = nil
}
