// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: alis/iam/v1/iam.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message for the AddIamBindings method
type AddIamBindingsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The iam protected resource to add the bindings to
	Resource string `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// The principals (users, service accounts or groups)
	// E.g: user:123456789, serviceAccount:alis-build@..., builders,builders:alis,builders:alis.os,admins,admins:alis.os
	Principals []string `protobuf:"bytes,2,rep,name=principals,proto3" json:"principals,omitempty"`
	// The roles Resource to give the principals. At least one role must be provided.
	// Format: ['roles/*', ...]
	// Example: ['roles/owner', 'roles/admin']
	Roles []string `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	// Whether to remove each principal from any other roles they have
	RemoveFromOtherRoles bool `protobuf:"varint,4,opt,name=remove_from_other_roles,json=removeFromOtherRoles,proto3" json:"remove_from_other_roles,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AddIamBindingsRequest) Reset() {
	*x = AddIamBindingsRequest{}
	mi := &file_alis_iam_v1_iam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddIamBindingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddIamBindingsRequest) ProtoMessage() {}

func (x *AddIamBindingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_iam_v1_iam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddIamBindingsRequest.ProtoReflect.Descriptor instead.
func (*AddIamBindingsRequest) Descriptor() ([]byte, []int) {
	return file_alis_iam_v1_iam_proto_rawDescGZIP(), []int{0}
}

func (x *AddIamBindingsRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AddIamBindingsRequest) GetPrincipals() []string {
	if x != nil {
		return x.Principals
	}
	return nil
}

func (x *AddIamBindingsRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *AddIamBindingsRequest) GetRemoveFromOtherRoles() bool {
	if x != nil {
		return x.RemoveFromOtherRoles
	}
	return false
}

// The request message for the RemoveIamBindings method
type RemoveIamBindingsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The iam protected resource to remove the bindings from
	Resource string `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// The principals (users, service accounts or groups)
	// E.g: user:123456789, serviceAccount:alis-build@..., builders,builders:alis,builders:alis.os,admins,admins:alis.os
	Principals []string `protobuf:"bytes,2,rep,name=principals,proto3" json:"principals,omitempty"`
	// The roles to remove the principals from
	// If empty, the principals will be removed from all roles
	// Format: ['roles/*', ...]
	// Example: ['roles/owner', 'roles/admin']
	Roles         []string `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveIamBindingsRequest) Reset() {
	*x = RemoveIamBindingsRequest{}
	mi := &file_alis_iam_v1_iam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveIamBindingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveIamBindingsRequest) ProtoMessage() {}

func (x *RemoveIamBindingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_iam_v1_iam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveIamBindingsRequest.ProtoReflect.Descriptor instead.
func (*RemoveIamBindingsRequest) Descriptor() ([]byte, []int) {
	return file_alis_iam_v1_iam_proto_rawDescGZIP(), []int{1}
}

func (x *RemoveIamBindingsRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *RemoveIamBindingsRequest) GetPrincipals() []string {
	if x != nil {
		return x.Principals
	}
	return nil
}

func (x *RemoveIamBindingsRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

// Request message for `BatchTestIamPermissions` method.
type BatchTestIamPermissionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// REQUIRED: The resources for which the policy detail is being requested.
	// See the operation documentation for the appropriate value for this field.
	Resources []string `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	// The set of permissions to check for the `resources`. Permissions with
	// wildcards (such as '*' or 'storage.*') are not allowed. For more
	// information see
	// [IAM Overview](https://cloud.google.com/iam/docs/overview#permissions).
	Permissions   []string `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchTestIamPermissionsRequest) Reset() {
	*x = BatchTestIamPermissionsRequest{}
	mi := &file_alis_iam_v1_iam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTestIamPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTestIamPermissionsRequest) ProtoMessage() {}

func (x *BatchTestIamPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_iam_v1_iam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTestIamPermissionsRequest.ProtoReflect.Descriptor instead.
func (*BatchTestIamPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_alis_iam_v1_iam_proto_rawDescGZIP(), []int{2}
}

func (x *BatchTestIamPermissionsRequest) GetResources() []string {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *BatchTestIamPermissionsRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// Response message for `BatchTestIamPermissions` method.
type BatchTestIamPermissionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The permissions the requester has for each requested resource.
	ResourcePermissions []*BatchTestIamPermissionsResponse_ResourcePermissions `protobuf:"bytes,1,rep,name=resource_permissions,json=resourcePermissions,proto3" json:"resource_permissions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BatchTestIamPermissionsResponse) Reset() {
	*x = BatchTestIamPermissionsResponse{}
	mi := &file_alis_iam_v1_iam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTestIamPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTestIamPermissionsResponse) ProtoMessage() {}

func (x *BatchTestIamPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alis_iam_v1_iam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTestIamPermissionsResponse.ProtoReflect.Descriptor instead.
func (*BatchTestIamPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_alis_iam_v1_iam_proto_rawDescGZIP(), []int{3}
}

func (x *BatchTestIamPermissionsResponse) GetResourcePermissions() []*BatchTestIamPermissionsResponse_ResourcePermissions {
	if x != nil {
		return x.ResourcePermissions
	}
	return nil
}

// The permissions the requester has on a resource.
type BatchTestIamPermissionsResponse_ResourcePermissions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource.
	Resource string `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// The permissions.
	Permissions   []string `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchTestIamPermissionsResponse_ResourcePermissions) Reset() {
	*x = BatchTestIamPermissionsResponse_ResourcePermissions{}
	mi := &file_alis_iam_v1_iam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTestIamPermissionsResponse_ResourcePermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTestIamPermissionsResponse_ResourcePermissions) ProtoMessage() {}

func (x *BatchTestIamPermissionsResponse_ResourcePermissions) ProtoReflect() protoreflect.Message {
	mi := &file_alis_iam_v1_iam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTestIamPermissionsResponse_ResourcePermissions.ProtoReflect.Descriptor instead.
func (*BatchTestIamPermissionsResponse_ResourcePermissions) Descriptor() ([]byte, []int) {
	return file_alis_iam_v1_iam_proto_rawDescGZIP(), []int{3, 0}
}

func (x *BatchTestIamPermissionsResponse_ResourcePermissions) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *BatchTestIamPermissionsResponse_ResourcePermissions) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

var File_alis_iam_v1_iam_proto protoreflect.FileDescriptor

const file_alis_iam_v1_iam_proto_rawDesc = "" +
	"\n" +
	"\x15alis/iam/v1/iam.proto\x12\valis.iam.v1\"\xa0\x01\n" +
	"\x15AddIamBindingsRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x1e\n" +
	"\n" +
	"principals\x18\x02 \x03(\tR\n" +
	"principals\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\x125\n" +
	"\x17remove_from_other_roles\x18\x04 \x01(\bR\x14removeFromOtherRoles\"l\n" +
	"\x18RemoveIamBindingsRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x1e\n" +
	"\n" +
	"principals\x18\x02 \x03(\tR\n" +
	"principals\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\"`\n" +
	"\x1eBatchTestIamPermissionsRequest\x12\x1c\n" +
	"\tresources\x18\x01 \x03(\tR\tresources\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\"\xeb\x01\n" +
	"\x1fBatchTestIamPermissionsResponse\x12s\n" +
	"\x14resource_permissions\x18\x01 \x03(\v2@.alis.iam.v1.BatchTestIamPermissionsResponse.ResourcePermissionsR\x13resourcePermissions\x1aS\n" +
	"\x13ResourcePermissions\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissionsB\"Z go.alis.build/common/alis/iam/v1b\x06proto3"

var (
	file_alis_iam_v1_iam_proto_rawDescOnce sync.Once
	file_alis_iam_v1_iam_proto_rawDescData []byte
)

func file_alis_iam_v1_iam_proto_rawDescGZIP() []byte {
	file_alis_iam_v1_iam_proto_rawDescOnce.Do(func() {
		file_alis_iam_v1_iam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alis_iam_v1_iam_proto_rawDesc), len(file_alis_iam_v1_iam_proto_rawDesc)))
	})
	return file_alis_iam_v1_iam_proto_rawDescData
}

var file_alis_iam_v1_iam_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_alis_iam_v1_iam_proto_goTypes = []any{
	(*AddIamBindingsRequest)(nil),                               // 0: alis.iam.v1.AddIamBindingsRequest
	(*RemoveIamBindingsRequest)(nil),                            // 1: alis.iam.v1.RemoveIamBindingsRequest
	(*BatchTestIamPermissionsRequest)(nil),                      // 2: alis.iam.v1.BatchTestIamPermissionsRequest
	(*BatchTestIamPermissionsResponse)(nil),                     // 3: alis.iam.v1.BatchTestIamPermissionsResponse
	(*BatchTestIamPermissionsResponse_ResourcePermissions)(nil), // 4: alis.iam.v1.BatchTestIamPermissionsResponse.ResourcePermissions
}
var file_alis_iam_v1_iam_proto_depIdxs = []int32{
	4, // 0: alis.iam.v1.BatchTestIamPermissionsResponse.resource_permissions:type_name -> alis.iam.v1.BatchTestIamPermissionsResponse.ResourcePermissions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_alis_iam_v1_iam_proto_init() }
func file_alis_iam_v1_iam_proto_init() {
	if File_alis_iam_v1_iam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alis_iam_v1_iam_proto_rawDesc), len(file_alis_iam_v1_iam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alis_iam_v1_iam_proto_goTypes,
		DependencyIndexes: file_alis_iam_v1_iam_proto_depIdxs,
		MessageInfos:      file_alis_iam_v1_iam_proto_msgTypes,
	}.Build()
	File_alis_iam_v1_iam_proto = out.File
	file_alis_iam_v1_iam_proto_goTypes = nil
	file_alis_iam_v1_iam_proto_depIdxs = nil
}
