// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/iam/v1/iam.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-07-08 08:07:13 UTC

package v1

const ()
